### ISSUE TITLE
Text component inside TextInput won'd display any text

### ISSUE THREAD

**Issue by zurex** [microsoft/react-native-macos#1011]
### Environment

```markdown
react-native -v:5.0.1
npm ls react-native-macos: 0.64.25
node -v: v14.17.6
npm -v:8.1.4
yarn --version: 1.22.4
xcodebuild -version:
Xcode 13.2.1
Build version 13C100
```

### Steps to reproduce the bug

```
<TextInput>
  <Text>React</Text>
  <Text>Native</Text>
</TextInput>
```

### Expected Behavior

it should be like `ReactNative`

### Actual Behavior

It shows nothing.

**Comment by Saadnajmi** [comment]
Hello, I looked a bit at the `<TextInput>` source code in React Native, and I think you can only specify text as children if you're on Android< https://github.com/facebook/react-native/blob/3eddc9abb70eb54209c68aab7dbd69e363cc7b29/Libraries/Components/TextInput/TextInput.js#L1264

The macOS TextInput component would most closely follow the iOS one, where you must specify the `value` or placeholder` prop. Would that work for your scenario?

**Comment by vaivai130** [comment]
Seconding @Saadnajmi, may be best to follow the value props instead of nesting Text children if you can.

**Comment by HeyImChris** [comment]
This seems like expected behavior for the macOS platform with the potential solution Saad proposed fixing your scenario.
