### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by misbell** [microsoft/react-native-macos#1019]
### Environment

```markdown
react-native -v:➜   
react-native-cli: 2.0.1
react-native: 0.67.2
npm ls react-native-macos:
macosapp@0.0.1 /Users/mpi/projects/rn/macosapp
└── react-native-macos@0.66.10
node -v:v16.5.0
npm -v:8.3.0
yarn --version:1.22.11
xcodebuild -version:Xcode 13.2.1
Build version 13C100
```

### Steps to reproduce the bug

just build the app and try to start it. it builds fine. cocoapods install fine, runs fine, but then:
<img width="3138" alt="Screen Shot 2022-02-12 at 10 36 51 PM" src="https://user-images.githubusercontent.com/356572/153737921-7e89f152-81be-4bb3-b207-bee5722d6d90.png">

### Expected Behavior

app window should open with example text

### Actual Behavior

app window opens with no text, error window opens beside it

### Reproducible Demo

happens every time for me. I have no idea how to reproduce for you. I built the app three times from scratch, same result every time.

**Comment by HeyImChris** [comment]
@misbell Could you share a link to a repo with this failure? We're consuming RN 0.64 successfully for our use cases. Another alternative is you could try using the 0.66 release. That came out recently and may fix your issues as well.
