### ISSUE TITLE
is there any navigation libs for react-native-macos?

### ISSUE THREAD

**Issue by shadow-boy** [microsoft/react-native-macos#1041]
### Environment

```markdown
react-native -v:
npm ls react-native-macos:
node -v:
npm -v:
yarn --version:
xcodebuild -version:
```

### Steps to reproduce the bug

is there any navigation libs for react-native-macos?

### Expected Behavior

is there any navigation libs for react-native-macos?

### Actual Behavior

is there any navigation libs for react-native-macos?

### Reproducible Demo

is there any navigation libs for react-native-macos?

### Additional context

is there any navigation libs for react-native-macos?

**Comment by k1mmm** [comment]
https://reactnative.directory is a good place to start when asking questions regarding third party libs, there you can filter by macOS (https://reactnative.directory/?macos=true) and it shows that react-navigation is the recommended one (and only one). 

I cannot testify myself to how good it is, but atleast it's somewhere to start.
