### ISSUE TITLE
TextInput cursor position when manipulating text

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-macos#1057]
### Environment

```markdown
react-native 0.64.0:
npm ls react-native-macos: 0.64.13
node: 17.0.1
npm: 8.1.0
yarn: N/A
xcodebuild: 13A1030d
```

### Steps to reproduce the bug

Create the following element, add some text. Then, move cursor to the beginning of the text and add more characters.
This will cause the cursor to move to the end of the text input.

<TextInput style={{flex: 1, height: 40}} value={this.state.Txt} onChangeText={(e) => {this.setState({Txt: e.toUpperCase()});}}></TextInput>

### Expected Behavior

Cursor should not change position on text change.

### Actual Behavior

Cursor moves to the end of the text when the element updates.

**Comment by Saadnajmi** [comment]
Could you attach a video of the behavior you're seeing?

**Comment by jbcullis** [comment]
@Saadnajmi
https://user-images.githubusercontent.com/27532334/155849334-663fee2d-0b2c-4c8f-8851-d7cbf35dc61e.mov

**Comment by chrisglein** [comment]
Related issue on Windows: https://github.com/microsoft/react-native-windows/issues/9615
