### ISSUE TITLE
TextInput selection color implemented incorrectly (wrong caret + highlight color)

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#1096]
### Environment

```markdown
react-native -v:6.4.0
npm ls react-native-macos: 0.66.33
node -v: 16
npm -v: -
yarn --version: 1
xcodebuild -version: 13.3
```

### Steps to reproduce the bug

On some backgrounds (and especially when macOS is using a light theme) the default text input caret is really hard to see. The only possible solution right now is to use the `selectionColor` prop, but this not only changes the caret color, but also the highlight color, which means if one tries to select either white or black colors, then the text completely disappears:

Default caret color on white background ❌:
<img width="448" alt="Screenshot 000018" src="https://user-images.githubusercontent.com/1634213/159214228-a8e7b7f9-f9bc-498f-8529-7f08c6df3c44.png">

Default highlight color on white background ✅:
<img width="334" alt="Screenshot 000019" src="https://user-images.githubusercontent.com/1634213/159214262-de935401-e8a9-4c6f-b71c-4e25dd49bcae.png">

Caret when setting `selectionColor="black"` ✅:
<img width="394" alt="Screenshot 000022" src="https://user-images.githubusercontent.com/1634213/159214459-df9f48bf-4489-4369-8231-6e9336410745.png">

Highlight when setting `selectionColor="black"` ❌:
<img width="397" alt="Screenshot 000021" src="https://user-images.githubusercontent.com/1634213/159214318-5d30d7bd-0e9e-4de1-bd8f-8b29cad92364.png">

### Actual Behavior

The behavior is just broken atm, at the very least we should be able to select different values for the caret and the highlight. I would gladly try to provide a PR if you could point me to the correct file where the TextInput is implemented.

**Comment by Saadnajmi** [comment]
This seems to be the documented behavior for `selectionColor` (https://reactnative.dev/docs/textinput#selectioncolor), relative to other platforms (comparing iOS and Android). Worth noting that iOS does lower the opacity of the selection so you can still read the test. 
You would need to open an issue on React Native itself to ask for a new prop for just the caret color. https://github.com/facebook/react-native/issues 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/6722175/162266829-869e9f91-3f33-46e7-9224-626bfce3a958.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6722175/162266841-614d0918-c318-4ab0-8239-1e9ba7a46335.png)
