### ISSUE TITLE
Transforming a view doesn't transform its interaction area

### ISSUE THREAD

**Issue by icestraw** [microsoft/react-native-macos#1099]
### Environment

```markdown
react-native -v:0.66.31
npm ls react-native-macos:0.66.37
node -v:17.3.0
npm -v:8.3.0
yarn --version:not installed
xcodebuild -version:Xcode 13.3 Build version 13E113
```

### Steps to reproduce the bug

1. Write a scrollView
2. Apply transform such as translateX translateY scale
3. Interact with that scrollView

### Expected Behavior

ScrollView is scrollable when mouse is hovering on all area of the ScrollView

### Actual Behavior

ScrollView is only scrollable when mouse is hovering on the area defined in "style" but not transformed area.

### Reproducible Demo

git@github.com:icestraw/ReportMacosBug.git

### Additional context

TouchableOpacity and other components seems to be the same.

**Comment by Saadnajmi** [comment]
Can you give more details about your specific scenario and what you are trying to achieve?

**Comment by icestraw** [comment]
macos demo:
https://user-images.githubusercontent.com/7201592/162604476-a27b1a08-052e-481a-b958-73846bafeca2.mp4

windows demo:
https://user-images.githubusercontent.com/7201592/162604482-03d1b50e-6aea-4271-9702-126d53b21e86.mp4

On the demo I transformed the scrollview to the right.
On Windows, when I move cursor right on the scrollview, I can scroll it using touch-pad.
However on macos, when I move cursor on the scrollview, I cannot scroll it. But when I move the cursor on the left side of the scrollview (the position before transforming), I can scroll it use the touch-pad. I think it's unexpected behavior.

**Comment by xyzAndReM** [comment]
@icestraw , I am actually surprised the windows one still works. As you said, the touch area stays where it was, the transformation only move the pixels.

The workaround I have for this is to change the xstyle according to the transformation that was executed. If you used an animation, when it finished you reset the transformation to default value and change the xstyle to position the element exactly where the transformation led to.

But that tip is only for animations, if you are trying to style using the transformation then the issue remains.

**Comment by jdk** [comment]
@Saadnajmi 

Can we reopen this? It is still an issue.
