### ISSUE TITLE
Xcode produces errors when building new project

### ISSUE THREAD

**Issue by objectiveSee** [microsoft/react-native-macos#1104]
<img width="487" alt="Screen Shot 2022-03-26 at 3 30 03 PM" src="https://user-images.githubusercontent.com/1684106/160257819-294126ca-8b34-40eb-8d44-bedf879ff88b.png">

### Environment

```markdown
react-native -v: N/A I have it installed through npx
**npx react-native --version**
5.0.1

npm ls react-native-macos: empty
node -v: v14.18.1
npm -v: 6.14.15
yarn --version: 1.22.18
xcodebuild -version: Xcode 13.3
Build version 13E113
```

### Steps to reproduce the bug

1. `npx react-native init project --template react-native@^0.64.0`
2. Try to run from CLI or via Xcode. I get 7,000 warnings and 25 errors (see screenshot)
`npx react-native run-macos`

### Expected Behavior

The template app should compile.

### Actual Behavior

Running the Mac OS launch command gives:
```
🍿 npx react-native run-macos
```

Running as an iOS app gives:

<img width="1840" alt="Screen Shot 2022-03-26 at 2 54 22 PM" src="https://user-images.githubusercontent.com/1684106/160256903-13a1aa3d-ae91-4d6d-b7b3-0d65382ab864.png">

Gist of build errors from iOS build (similar errors): https://gist.github.com/objectiveSee/9fa0159b2b58cb8b6c5fe3b9c834756f

### Reproducible Demo

I am using this site (https://microsoft.github.io/react-native-windows/docs/rnm-getting-started) as a guide, but it does not have a lot of information.

### Additional context

Running on MacBook with Apple silicone

**Comment by Saadnajmi** [comment]
Can you repro this using just standard React Native, and not React Native macOS?
