### ISSUE TITLE
Deep linking support

### ISSUE THREAD

**Issue by hsjoberg** [microsoft/react-native-macos#1128]
### Summary

Hi.
I'm trying to figure out how deep linking from a web browser would work with react-native-macos.
I've been looking some at `RCTLinkingManager.h` and saw this custom macOS code:
https://github.com/microsoft/react-native-macos/blob/97a7e106d6d73f0f1b253a7b3e1452e03778c38a/Libraries/LinkingIOS/RCTLinkingManager.h#L16-L18

...but I am not sure exactly how this is supposed to be used.
I don't see any method from `NSApplication` that fits in, supposedly [`openURLs`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/2887193-application?language=objc) is called when a deep linking occurs.

### Motivation

Deeplinking is an essential UX or usability functionality.

### Open Questions

Is deep linking supported right already?

**Comment by Saadnajmi** [comment]
The general answer for "is this supported" is we support whatever iOS supports in React Native. It looks like there is deep linking support in iOS (https://reactnative.dev/docs/linking). To get it working for macOS, you would call the equivalent Appkit API (AKA, [NSApplication ...] instead of [UIApplication ...]

**Comment by hsjoberg** [comment]
Hey @Saadnajmi, thank you for your reply.

> To get it working for macOS, you would call the equivalent Appkit API (AKA, [NSApplication ...] instead of [UIApplication ...]

Indeed, I managed to figure it out* eventually, though it differs substantially from how you do it in iOS/UIKit, so the upstream docs does not really help here.

```ObjectiveC
- (void)applicationDidFinishLaunching:(NSNotification *)aNotification
{
  [[NSAppleEventManager sharedAppleEventManager]
   setEventHandler:self
   andSelector:@selector(getURL:withReplyEvent:)
   forEventClass:kInternetEventClass andEventID:kAEGetURL
  ];
}

- (void)getURL:(NSAppleEventDescriptor *)event withReplyEvent:(NSAppleEventDescriptor *)reply
{
  [RCTLinkingManager getUrlEventHandler:event withReplyEvent:reply];
}
```

*) Code above works when the app is already running, it does not work if you start the app via a deeplink.

**Comment by christophpurrer** [comment]
There is actually an example in RNTester-macOS how to integrate deep-link support
https://github.com/microsoft/react-native-macos/blame/main/packages/rn-tester/RNTester-macOS/AppDelegate.mm#L71-L82

**Comment by hsjoberg** [comment]
I've concluded that this isn't actually an issue and the current react-native-macos handles things just fine.

Thank you @christophpurrer.

**Comment by AdrianFahrbach** [comment]
If anyone finds this issue while looking for a way to add deep link support to the Swift version of react-native-macos then here is how:

You need to add this function to you `AppDelegate.swift`. Has to come before `applicationDidFinishLaunching`. If I got this correctly then this function is basically the deep link event handler:
```swift
@objc public func getUrl(_ event: NSAppleEventDescriptor, withReplyEvent reply: NSAppleEventDescriptor) -> Void {
  return RCTLinkingManager.getUrlEventHandler(event, withReplyEvent: reply)
}
```

Inside your `applicationDidFinishLaunching` function you need to assign the handler with this code:
```swift
func applicationDidFinishLaunching(_ aNotification: Notification) {
  var em = NSAppleEventManager.shared()
  em.setEventHandler(self, andSelector: #selector(self.getUrl(_:withReplyEvent:)), forEventClass: AEEventClass(kInternetEventClass), andEventID: AEEventID(kAEGetURL))

  // The rest of you applicationDidFinishLaunching...
}
```

I got close to zero swift and objective-c knowledge, but this seems to be working when the app is running. I don't know if it works on startup (not needed for my use case), but it is basically the same as above. I got this answer by adjust this [this stackoverflow answer](https://stackoverflow.com/a/43149460/11613411).

**Comment by manvi-ivnam** [comment]
I'll add my two cents to the previous answer. If you want `Linking.getInitialURL()` to work, you need to move `setEventHandler` to `applicationWillFinishLaunching`. It looks like this:

```
  func applicationWillFinishLaunching(_ notification: Notification) {
    NSAppleEventManager.shared().setEventHandler(self, andSelector: #selector(self.getUrl(_:withReplyEvent:)), forEventClass: AEEventClass(kInternetEventClass), andEventID: AEEventID(kAEGetURL))
  }
```
