### ISSUE TITLE
background view lags when Stretching window

### ISSUE THREAD

**Issue by elmcapp** [microsoft/react-native-macos#1144]
### Environment

```markdown
react-native -v:
npm ls react-native-macos:
node -v:
npm -v:
yarn --version:
xcodebuild -version:
node v17.5.0
npm 8.4.1
"react": "17.0.2",
"react-native": "0.68.1",
"react-native-macos": "^0.66.0-0"
xcodebuild Xcode 13.2.1
yarn 1.22.17
```

### Steps to reproduce the bug

1 click then drag the right bottom corn of the window to make the window bigger (stretch the window view)
You will see the view lags and have to catch up to the window size

### Expected Behavior

Expect the view to srectch with the same timing as the window size. s

### Actual Behavior

I attached a video to show issue

### Reproducible Demo

https://user-images.githubusercontent.com/64275658/166131249-8b7a95aa-fb52-45e9-8717-0bbb8ace8dbd.mov

**Comment by Bijiabo** [comment]
Yes, I also have the same problem, even in release build.
