### ISSUE TITLE
add Touch Bar support

### ISSUE THREAD

**Issue by jihoobyeon** [microsoft/react-native-macos#1211]
### Summary

Add [Touch Bar](https://developer.apple.com/documentation/appkit/nstouchbar?language=objc) support on React Native for macOS.

### Motivation

I wanted to add Touch Bar support for my RN app and I found [this repo](https://github.com/ptmt/react-native-touchbar) from NPM and installed it but did not work.

Some part of the code seems to be outdated (since original author's last work on repo was 2018),
so I [tried to modify](https://github.com/jihoobyeon/react-native-touchbar/tree/reboot) the code and made every error disappear, but stil cannot make to appear my code on XCode's Touch Bar Simulator.
(Note that I am using macOS Monterey on M1 Mac mini)

I also tried completely rewrite from scratch, but that also would not run properly.
That also neither throws error nor show expected components.

So I suggest - Despite feeling sorry for giving you a new burden - it will be better to integrate Touch Bar support in `react-native-macos`,
since Touch Bar is only available on some MacBook Pro models,
(Yeah, there is iCUE Nexus for Windows... but that one seems quite different from Touch Bar)
and you guys are expert in native macOS programming, so it will be better to maintenance it.

### Basic Example

Maybe we can use like this:

```
import * as React from 'react';
import { Button, Text, TouchBar, View } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View>
        <TouchBar>
          <Button title="Esc" onClick={() => alert('This is Touch Bar responding...')} />
          <Text>This App supports Touch Bar!</Text>
        </TouchBar>
        <Text>The App supports Touch Bar</Text>
      </View>
    );
  }
}
```

**Comment by jbcullis** [comment]
Better suited as a native module.

RN core has been scaling back to essentials and it's our job to extend on that in each of our apps.
