### ISSUE TITLE
0.66.58 android-patches/patches/Hermes/package.json file format error

### ISSUE THREAD

**Issue by zmj520** [microsoft/react-native-macos#1231]
### Description

I clone 0.66.56 to local and depend on it, finally after building and running the macOS application, throw an exception.

Here is the path json file content.
`diff --git a/package.json b/package.json
index 6fc4c801f1..3ad2acfd1c 100644
--- a/package.json
+++ b/package.json
@@ -106,7 +106,7 @@
     "anser": "^1.4.9",
     "base64-js": "^1.1.2",
     "event-target-shim": "^5.0.1",
-    "hermes-engine": "~0.9.0",
+    "hermes-engine": "~0.11.0",
     "invariant": "^2.2.4",
     "jsc-android": "^250230.2.1",
     "metro-babel-register": "0.66.2",
`

### Version

0.66.58

### Output of `npx react-native info`

`
Error: Cannot parse ~/react-native-macos-0.66.58/android-patches/patches/Hermes/package.json as JSON: Unexpected token d in JSON at Potision ....
`

### Steps to reproduce

- clone 0.66.58 to local
- local dependency
- yarn react-native-macos run

**Comment by jbcullis** [comment]
RN MacOS is still at .64
