### ISSUE TITLE
Root package.json has stale dependencies (prettier 1, etc..)

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-macos#1326]
While talking with @christophpurrer , we noticed that the root package.json uses `prettier v1`, while the one in repo-config use v2. This meant that running `yarn prettier --fix` would do different things on our machines. Looking deeper, it seems that our root package.json has some stale changes.

This commit removed prettier from the root package.json and put it in repo-config: https://github.com/facebook/react-native/commit/f3930a93d5cf5f19058b0bfe453c7b9324eb8552

But our 0.66-merge commit seems to have brought it back. https://github.com/microsoft/react-native-macos/commit/793ebb8ba8260ced7df87f8f3e90a46b04ee2bf6

**Comment by christophpurrer** [comment]
Here is a prettier 2.x fix > https://github.com/microsoft/react-native-macos/pull/1327
