### ISSUE TITLE
"Fix inconsistent shadows (#1357)" Appearance switching color issue

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-macos#1363]
### Environment

```markdown
react-native-macos: 0.68.25
```

### Steps to reproduce the bug

Switch form light-mode to dark-mode and the shadow color wont update, it's too dark after switching appearance

### Expected Behavior

[NSColor colorWithCGColor:layer.shadowColor] needs to re-initialize every time the appearance change, as its a static color

**Comment by Saadnajmi** [comment]
If I understand correctly, the shadow isn't recalculated when the appearance changed. As a result, you could run into a scenario like this?

```
<View 
  Style={{
      shadowColor: DynamicColorMacOS(
        light: 'red',
        dark; 'blue'
      )
    }}>
  
// start app in light mode, shadow color is red

// Switch to dark, shadow stays red

```

**Comment by k1mmm** [comment]
After some investigation it seems that it's the opactiy that changes between appearance change.

Heres when starting the app
![image](https://user-images.githubusercontent.com/10708276/185113793-9400dc10-9908-4b96-99db-83ca376d1906.png)

And this is after switching to dark appearance and back to light appearance
![image](https://user-images.githubusercontent.com/10708276/185113864-aee387b4-3e84-4f7c-aa55-222c520dabab.png)


`        shadowRadius: 1,
        shadowColor: DynamicColorMacOS({
            light: 'red',
            dark: 'blue',
        }),
        shadowOpacity: 0.2,
        shadowOffset: {
            height: 2,
            width: 0,
        },`

**Comment by k1mmm** [comment]
@Saadnajmi Also native views whom extends RCTView gets shadow applied by default

**Comment by Saadnajmi** [comment]
> @Saadnajmi Also native views whom extends RCTView gets shadow applied by default

Native subclasses of RCTView get a shadow when you set them on that view? Or you get unwanted shadows on them when you set a shadow on some random other RCTView?

**Comment by k1mmm** [comment]
@Saadnajmi In my case the parent (<View />) of a custom native view (RCTView) has shadow set in the javascript, so the child of that parent that's a native view extending RCTView gets an unwanted shadow, but not at first render, only after a second update of the component.

**Comment by k1mmm** [comment]
@Saadnajmi Regarding the opactiy problem it seems the old code for adding shadows is still in use, and randomly it will apply those old shadows randomly like it used to

**Comment by k1mmm** [comment]
This issue has been resolved
