### ISSUE TITLE
zIndex not working?

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#1389]
### Environment

```markdown
react-native -v: 0.68.1
npm ls react-native-macos: 0.66.70
node -v: 16
npm -v:
yarn --version: 1
xcodebuild -version:
```

### Steps to reproduce the bug

I'm trying to set the zIndex on a absolutely positioned view:

```ts
{isOpen && (
  <View
    style={
      (tw.style(
        `w-32 rounded justify-center items-center border border-gray-500 absolute top-7 dark:bg-black bg-red`,
      ),
      {
        zIndex: 1000,
      })
    }>
    {options.map(o => (
      <TouchableOpacity
        style={tw`py-1`}
        onPress={() => {
          onValueChange(o.value)
        }}>
        <Text>{o.label}</Text>
      </TouchableOpacity>
    ))}
  </View>
)}
```

<img width="334" alt="Screenshot 000911" src="https://user-images.githubusercontent.com/1634213/186841111-dd042f74-763e-4b85-8601-ac1d8abdbc75.png">

Yet it doesn't seem to be working and the view rendered afterwards still overlaps. Is there any know issue regarding this?

**Comment by ospfranco** [comment]
I just tried using a Portal to hoist my component above other Views and it still doesn't work. I also tried the absolute rendering to the top (to check if the overlap still happens) and there the dialog is rendered correctly (above the previous component) so it seems `zIndex` is indeed not working... (also portals are not working?)

**Comment by Saadnajmi** [comment]
ZIndex is one of the props listed here as potentially having weird behavior.. but iirc it seemed fine when I looked last in RNTester? 

https://github.com/microsoft/react-native-macos/issues/466

Might be worth a double check. Your views look transparent, what happens if they all have solid colored backgrounds? Also curious, how did you use a portal?

**Comment by ospfranco** [comment]
- Yeah, sorry in the snippet I copied there is an error with the tailwind class, but I already placed a solid color as the background and the problem persists
- I used this [react-native-portal](https://github.com/gorhom/react-native-portal)

**Comment by ospfranco** [comment]
I'm definitely seeing some strange behavior, here is what happens when I use zIndex: 1000

<img width="1342" alt="Screenshot 000913" src="https://user-images.githubusercontent.com/1634213/187015282-1c50f0f7-aaa1-4e20-a7cb-0893a93d12df.png">

**Comment by Saadnajmi** [comment]
Here's the live example of z-index in RNTester on the main branch right now
https://user-images.githubusercontent.com/6722175/187872175-4a79373c-ba5b-47d5-a519-c01d1da15b5f.mov


So in this case.. it's working. I know that on iOS, z-index is a bit quirky in that the siblings need the same z-index and/or the parent view also needs a z-index?
https://reactnative.dev/docs/layout-props#zindex
I'm wondering if macOS shares the same quirk (or a similar quirk) that's causing the issue you see

**Comment by ospfranco** [comment]
I can give it a try later, thanks!

**Comment by ospfranco** [comment]
I tried and it is working, indeed, only siblings (Components at the same level in the JSX for those facing the problem in the future) seem to work properly! Thanks a lot Saad!
