### ISSUE TITLE
RNSScreenStackHeaderConfig was not found in UIManager

### ISSUE THREAD

**Issue by yaozhang-this** [microsoft/react-native-macos#1390]
### Environment

```markdown
react-native -v: 5.0.1
npm ls react-native-macos: react-native-macos@0.64.30
node -v: v18.8.0
npm -v: 8.18.0
yarn --version: 1.22.18
xcodebuild -version: Xcode 13.3
Build version 13E113
```

### Steps to reproduce the bug

1. Initialize a macOS project following the steps listed in the react-native-macos website until the new app screen is built and run
2. Copy and paste the navigation sample code from official react-native doc page https://reactnative.dev/docs/navigation
3. follow the steps to install `npm install @react-navigation/native @react-navigation/native-stack` `npm install react-native-screens react-native-safe-area-context`
4. do pod install on macos/ folder
5. build and run the app, error reported when run.` ERROR  Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.`

### Expected Behavior

There should not be any error.

### Actual Behavior

` ERROR  Invariant Violation: requireNativeComponent: "RNSScreenStackHeaderConfig" was not found in the UIManager.
`

**Comment by danilaplee** [comment]
i also have same issue, i was able to rewrite the bottom navigation tab library to not use the RNSScreenStackHeaderConfig but not for the stack navigator

**Comment by mustafaskyer** [comment]
any updates about this !

**Comment by Saadnajmi** [comment]
React Native Navigation doesn't support macOS, as it has some native dependencies. To use with a React Native macOS project, you would have to be careful that you use the Javascript only parts of it, if possible.

**Comment by qd-wl** [comment]
I have same issue, how to resolve it?

**Comment by Saadnajmi** [comment]
I think you'd have to open an issue for macOS support in react native navigation repo.

**Comment by kaiyes** [comment]
@qd-wl & @yaozhang-this , Please Use `@react-navigation/stack`, & not `@react-navigation/native-stack`. Like @Saadnajmi said, libraries with js parts work fine. 

I faced the same error today & solved it via using `@react-navigation/stack` instead of `@react-navigation/native-stack`

**Comment by ElangoPrince** [comment]
@kaiyes Your right. I have tried many options but nothing works. But replacing import for stack navigator works well. 
 ```
-import { createNativeStackNavigator } from '@react-navigation/native-stack';
+import { createStackNavigator } from '@react-navigation/stack'
```
