### ISSUE TITLE
0.68.3x new project template has wrong constraints on RootView

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#1397]
### Environment

```markdown
react-native -v:
npm ls react-native-macos: 0.68.3
node -v:
npm -v:
yarn --version:
xcodebuild -version:
```

### Steps to reproduce the bug

I created a new project using the latest version of RN-macOS and when I took a look at the code inside the AppDelegate I saw the `NSViewMinXMargin` is repeated twice:

![QG1Jx4MR jpg-large](https://user-images.githubusercontent.com/1634213/187349749-2503faa7-f45a-4e26-96c1-8cac4805a99a.jpeg)

**Comment by Saadnajmi** [comment]
Seems this was wrong since this repo's inception. I did a quick Cmd+F for that template code and fixed it in #1413. Will update when that PR lands.

**Comment by jbcullis** [comment]
Is there an ETA on latest stable moving to .68?

**Comment by Saadnajmi** [comment]
> @Saadnajmi Is there an ETA on latest stable moving beyond .64?

We're on 0.68 now?

**Comment by jbcullis** [comment]
@Saadnajmi Ahhh, I've been keeping my eye on this page - https://microsoft.github.io/react-native-windows/docs/rnm-getting-started

**Comment by Saadnajmi** [comment]
Yeah, we should be better about updating that page 😅 
I suppose the best place right now is looking at the actual npm releases: https://www.npmjs.com/package/react-native-macos or the "tags" (but not releases...) part of our GitHub repo https://github.com/microsoft/react-native-macos/tags

Hopefully we can have some better public knowledge of our next release, 0.70 =)
