### ISSUE TITLE
Build error: 'React/RCTDynamicTypeRamp.h' file not found

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-macos#1462]
### Environment

```markdown
react-native -v: 0.68.56
xcodebuild -version: 14.0.1
```

### Steps to reproduce the bug

Build using xcode

macos/Pods/Headers/Public/React-Core/React/RCTTextAttributes.h:11:9: error build: 'React/RCTDynamicTypeRamp.h' file not found

**Comment by Saadnajmi** [comment]
@amgleitman Could you help?

@k1mmm Have you tried doing a clean pod install / build?

**Comment by k1mmm** [comment]
I reinstalled xcode and now its working, might be the pod install och clean build folders failed when i tried it earlier or something. I'll close this, thanks!
