### ISSUE TITLE
Support react-native-image-picker

### ISSUE THREAD

**Issue by aniketgupta8960** [microsoft/react-native-macos#1593]
### Module

react-native-image-picker

### Module repo url

https://github.com/react-native-image-picker/react-native-image-picker

### Target Version

0.64

### Which app/customer is requesting this module?

for internal use

### In what scenarios will this module be used?

For picking the image from local device and camera

**Comment by Saadnajmi** [comment]
You would have to open an issue on the module itself to support macOS.
