### ISSUE TITLE
Remove `API_AVAILABLE(ios(12.0))` uses

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-macos#1605]
The latest React Native iOS minimum is 12.4, so we don't need this. One use is in RCTTextInputUtils.h

**Comment by christophpurrer** [comment]
See -> https://github.com/facebook/react-native/pull/35835 ;-)

**Comment by Saadnajmi** [comment]
Thanks @christophpurrer! Closing this issue since we should just pick this up in the next merge now
