### ISSUE TITLE
Make RCTUIKit more modular

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-macos#1611]
Currently, each shim (RCTUISwitch, RCTUISlider) is getting appended to RCTUIKit.h/.m. It would be nice if they were each in their own file and `RCTUIKit.h` just became an aggregate header that imported all of them. 

Additionally, many libraries can't depend on RCTUIKit here, bcause this file's podspec (say, React-RCTImage) don't take a dependency on RCTUIKit's pod `React-Core`. That may encourage making RCTUIKit into it's own pod.

**Comment by christophpurrer** [comment]
Sounds like a good idea.
We follow the same approach for our C++/JSI bridging layer
https://github.com/facebook/react-native/blob/main/ReactCommon/react/bridging/Bridging.h
