### ISSUE TITLE
please update the document

### ISSUE THREAD

**Issue by shifenhutu** [microsoft/react-native-macos#1631]
### Summary

the document do not have the latest react-native tutorial, it's only have `0.64`

https://microsoft.github.io/react-native-windows/docs/rnm-getting-started

![image](https://user-images.githubusercontent.com/104620424/211722891-09607f80-4a9f-4332-9b93-c92ec713a28a.png)

------

  long time do not update   (than two years old)

https://microsoft.github.io/react-native-windows/docs/winui3#current-status

![image](https://user-images.githubusercontent.com/104620424/211723209-e6414f40-0899-44bf-bc3a-608aa2ff5e1d.png)

### Motivation

no

**Comment by Saadnajmi** [comment]
This is updated!
