### ISSUE TITLE
RCTTouchHandler has flipped Y-coordinate

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-macos#1723]
### Environment

```markdown
react-native: 0.68.6
react-native-macos: 0.68.64
```

### Steps to reproduce the bug

When using RCTTouchHandler to add add gestures to a native component the Y-coordinate is flipped, due to iOS and macOS differences.

ex: RCTView.addGestureRecognizer(RCTTouchHandler(bridge: bridge))

**Comment by Saadnajmi** [comment]
Thanks for the bug! Are you by any chance attaching the touch handler to a custom native component? I think you have to make sure to override 'isFlipped' to true. I had a similar bug that I solved that way.

**Comment by k1mmm** [comment]
@Saadnajmi isFlipped did the trick, Thanks allot!
