### ISSUE TITLE
How can I disable remote debugging?

### ISSUE THREAD

**Issue by jihoobyeon** [microsoft/react-native-macos#1743]
### Summary

Enable to disable remote debugging manually as `Command+D` for mobile simulators.

### Motivation

I'm trying to make [@babylonjs/react-native](https://github.com/BabylonJS/BabylonReactNative) to work at macOS, so I modified some code of it, and tested - but this screen appears.
![스크린샷 2023-03-15 오후 9 53 41](https://user-images.githubusercontent.com/77971249/225315531-10e975e4-b12d-49d0-be90-82930faa7b41.png)

Yes, I already saw that on [React Native for Windows](https://github.com/microsoft/react-native-windows), but I was able to disable remote debugging easily by editing `InstanceSettings().UseWebDebugger(true)` to `InstanceSettings().UseWebDebugger(false)` in `App.cpp`.

But, in macOS version, I cannot find where to disable it.
I tried editing `methodMap_["setIsDebuggingRemotely"] = MethodMetadata {1, __hostFunction_NativeDevSettingsSpecJSI_setIsDebuggingRemotely};` to `methodMap_["setIsDebuggingRemotely"] = MethodMetadata {0, __hostFunction_NativeDevSettingsSpecJSI_setIsDebuggingRemotely};`, but it automatically returns to `1` when app has restarted.

Is there any way to disable remote debugging? if there isn't, may you add it?

**Comment by Saadnajmi** [comment]
Does `[bridge.devSettings setIsDebuggingRemotely:NO];` not work? That's how you do it for iOS, which should extend to macOS.

**Comment by jihoobyeon** [comment]
> Does `[bridge.devSettings setIsDebuggingRemotely:NO];` not work? That's how you do it for iOS, which should extend to macOS.

No, it throws `property 'devSettings' not found on object of type 'RCTBridge *'` error.
I think the command has moved elsewhere, but I cannot find it from docs.

**Comment by Saadnajmi** [comment]
For you import the header?
```#import <React/RCTDecSettings.h>```

The property is implemented in a category, so it's not visible unless you import the header I think

https://github.com/microsoft/react-native-macos/blob/main/React/CoreModules/RCTDevSettings.h#L126-L130

**Comment by jihoobyeon** [comment]
> For you import the header? `#import <React/RCTDevSettings.h>`
> 
> The property is implemented in a category, so it's not visible unless you import the header I think
> 
> https://github.com/microsoft/react-native-macos/blob/main/React/CoreModules/RCTDevSettings.h#L126-L130

Okay, I imported the header, but now "Could not initialize Babylon Native" screen appears again.
maybe it's problem of Babylon.js part

**Comment by jihoobyeon** [comment]
No, I tried to modify code of @babylonjs/react-native to skip checking remote debugging, but still not working.
seems to be remote debugging not disabled

**Comment by jihoobyeon** [comment]
Okay, I finally found a way!
it was simple. just add `self.` before `bridge`: `[self.bridge.devSettings setIsDebuggingRemotely:NO];`
