### ISSUE TITLE
I want to thank you all for your incredible and intense support for this lib, maintaining something at this level is not easy, and now that version 0.71 has arrived I will be able to distribute my company's software for macOS now, my most sincere thanks!!!

### ISSUE THREAD

**Issue by Victor0814gui** [microsoft/react-native-macos#1772]
### Environment

```markdown
react-native -v:
npm ls react-native-macos:
node -v:
npm -v:
yarn --version:
xcodebuild -version:
```

### Steps to reproduce the bug

1

### Actual Behavior

1

**Comment by Saadnajmi** [comment]
0.71 is not published to NPM just yet, but working on it 😅

Thank you for the note! Out of curiosity, what company / product do you use react-native-macos for? You can email/DM me if that's better :)

**Comment by widersky** [comment]
@Saadnajmi is there any ETA for this? The difference between versioning React Native for Windows and macOS is huge :|

**Comment by Saadnajmi** [comment]
> @Saadnajmi is there any ETA for this? The difference between versioning React Native for Windows and macOS is huge :|

Keep and eye on this PR: https://github.com/microsoft/react-native-macos/pull/1748

If all goes right, that should publish our 0.71 npm package when it lands

**Comment by Saadnajmi** [comment]
https://www.npmjs.com/package/react-native-macos/v/0.71.0

That was... quite difficult 😵

**Comment by gabrieldonadel** [comment]
@Saadnajmi are you going to tag 0.71.0 as `latest`?

**Comment by Saadnajmi** [comment]
> @Saadnajmi are you going to tag 0.71.0 as `latest`?

Working on it.. It will probably be `0.71.1` that gets tagged. There was a bug in our automation that skipped tagging `latest` for `0.71.0` :/

**Comment by jdk** [comment]
> > @Saadnajmi is there any ETA for this? The difference between versioning React Native for Windows and macOS is huge :|
> 
> Keep and eye on this PR: #1748
> 
> If all goes right, that should publish our 0.71 npm package when it lands

Not OP, but we too have shipped our hardware product with react native desktop, and are incredibly grateful for all your hard work and support. Thank you so much with endless gratitude. 

Here is ours: https://flirc.tv/products/skip1s-remote

**Comment by Saadnajmi** [comment]
@jdk thank you for sharing! I've been meaning to find out where all React Native macOS is used. So.. of other read this, please comment :D
