### ISSUE TITLE
TextInput with multiline not triggering onChangeText callback in 0.71.2

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-macos#1788]
### Environment

```markdown
react-native -v: 0.71.6
npm ls react-native-macos: 0.71.2
```

### Steps to reproduce the bug

<TextInput multiline onChangeText={(text) => console.log(text)} />

### Additional context

Works perfectly without 'multiline' prop

**Comment by Saadnajmi** [comment]
@shwanton FYI

**Comment by Saadnajmi** [comment]
It seems others have hit this too, and it seems pretty bad. We'll try to take a look at it and find a fix.

**Comment by k1mmm** [comment]
@Saadnajmi Awesome thanks! Can't wait to use 0.71, especially with that smooth content resizing =)

**Comment by k1mmm** [comment]
@shwanton this seem to be resolved now in the upstream repo
https://github.com/facebook/react-native/commit/a804c0f22b4b11b3d9632dc59a6da14f6c4325e3

**Comment by Saadnajmi** [comment]
> @shwanton this seem to be resolved now in the upstream repo
> https://github.com/facebook/react-native/commit/a804c0f22b4b11b3d9632dc59a6da14f6c4325e3

Looks like it should be picked for a future patch release, at which point we can merge it into our repo as well. 
https://github.com/reactwg/react-native-releases/discussions/61#discussioncomment-5648748

**Comment by k1mmm** [comment]
@Saadnajmi is there anyway we can confirm this will fix the issue before we wait around for the patch?

**Comment by Saadnajmi** [comment]
@k1mmm if you fork React Native macOS internally, you could try cherry picking the one commit. 

Since RN 0.71.7 was just released, and 0.71.8 right now _only_ has that one commit in it's pick requests, I'll consider just cherry-picking it along with all the 0.71.7 commits for React Native macOS. I'll update in this thread if we end up doing that.

**Comment by Saadnajmi** [comment]
I just tested cherry-picking that commit, and it doesn't seem to fix the issue :/ 
We'll have to keep debugging

**Comment by k1mmm** [comment]
@Saadnajmi Oh, that's unfortunate. Alright, thanks for the effort and the update!

**Comment by k1mmm** [comment]
@Saadnajmi Just wanna let you know onSubmitEditing do not work either on textInputs regarding being multiline or not

**Comment by Saadnajmi** [comment]
@k1mmm What key are you using got submit? And have you set the `submitKeyEvents` prop? For context, here's the logic: https://github.com/microsoft/react-native-macos/blob/375c57902cf4605301f459c2d243f93808507fb8/Libraries/Text/TextInput/RCTBaseTextInputView.m#L458

**Comment by shwanton** [comment]
https://github.com/facebook/react-native/pull/33653 Changed this api and we need to update the `RCTBackedTextFieldDelegateAdapter` on macOS to use `textInputShouldSubmitOnReturn` instead. 

Fix incoming.

**Comment by Saadnajmi** [comment]
Reopening till we backport to 0.71-stable

**Comment by shwanton** [comment]
Fix was picked to 0.71-stable: #1812

**Comment by k1mmm** [comment]
Its working flawless now! Thanks allot!
