### ISSUE TITLE
External module (react-native-localize) cannot be found when new architecture is enabled

### ISSUE THREAD

**Issue by zoontek** [microsoft/react-native-macos#1821]
### Environment

```markdown
react-native -v: 0.71.7
npm ls react-native-macos: 0.71.6
node -v: 18.6.0
npm -v: 8.19.2
yarn --version: 1.22.19
xcodebuild -version: 14.3/14E222b
```

### Steps to reproduce the bug

Run an app with new architecture enabled + `react-native-localize`

### Expected Behavior

`RNLocalize` should be found.

I currently works correctly with:

- `react-native` (iOS) new arch enabled or not
- `react-native-macos` new arch **not** enabled

### Actual Behavior

<img width="1176" alt="Screenshot_2023-05-08_at_14 00 30" src="https://user-images.githubusercontent.com/1902323/236866948-2c432cb0-517b-4823-a7c3-4b38c20bb26f.png">

```sh
LOG  Running "RNLocalizeExample" with {"rootTag":1,"initialProps":{}}
ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNLocalize' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
ERROR  TypeError: Cannot read property 'App' of undefined, js engine: hermes
```

### Reproducible Demo

- `git clone git@github.com:zoontek/react-native-localize.git`
- `cd react-native-localize`
- `yarn install`
- `cd example`
- `yarn install`
- `cd macos`
- `edit ./Podfile` (to enable hermes)
- `RCT_NEW_ARCH_ENABLED=1 pod install`

Then try to run the app.

**Comment by alejandromolero** [comment]
same issue. any update?

**Comment by Saadnajmi** [comment]
I wonder if it's because the example app in the repo / our template app need to updated to be new arch compatible. That's my current guess

**Comment by zoontek** [comment]
@Saadnajmi Its compatible with new arch for iOS and Android. As it also works for macOS (new arch not enabled), what would be missing here?

**Comment by shwanton** [comment]
#1853 adds New Arch support to the macOS template app.
Once this PR is merged, you'll need to blow away the `macos` example & re-run `npx react-native-macos-init`
If you add the TM & run `RCT_NEW_ARCH_ENABLED=1 pod install --verbose`, codegen + TM should work.

**Comment by zoontek** [comment]
@shwanton I updated to latest version, it works 🥳

<img width="1092" alt="Screenshot 2023-06-17 at 11 36 05" src="https://github.com/microsoft/react-native-macos/assets/1902323/0bae39ee-e866-445b-853d-4d16c0f9c7b8">

**Comment by jamonholmgren** [comment]
If someone stumbles across this in the future -- please note that even if you change your podfile to look something like this, turning on the new architecture:

![Image](https://github.com/user-attachments/assets/2c7229dd-fb3f-42d1-9082-3b2b57e84fbb)

... you STILL have to run with `RCT_NEW_ARCH_ENABLED=1 pod install --project-directory=macos`

or else it will not work and you'll get this:

![Image](https://github.com/user-attachments/assets/d35de513-09bd-429d-906d-cc28f3f736e6)

I thought that just flipping the booleans in the podfile would do the job, but it does not.

Spent over an hour on this, lol
