### ISSUE TITLE
How to get native window handle of app in native modules?

### ISSUE THREAD

**Issue by jihoobyeon** [microsoft/react-native-macos#1833]
### Summary

I am trying to make [Babylon.js](https://www.babylonjs.com/) game engine to run on RN-macOS (Babylon team already [had done](https://github.com/BabylonJS/BabylonReactNative/tree/master) it for RN and RN-Windows)
It seems to almost done, but I'm [stuck](https://forum.babylonjs.com/t/im-trying-to-make-babylonreactnative-to-work-on-macos/39178/79) in native window handle part.
Babylon requires `MTKView *` type for native window handle, but initialization part is lacked now.
I tried several workaround but cannot get native window handle of app.

Is there a way that native module can access window handle of app?

### Motivation

It is essential for Babylon game engine to work on React Native for macOS
and it may will help for other native modules with graphic library.

**Comment by Saadnajmi** [comment]
I'm not familiar with Babylon.JS so you may need to reach out to the team to add macOS support. It should be fairly straightforward if there's already iOS support. One difference you might run into between iOS and macOS is that on iOS, `UIWindow` is a subclass of `UIView` while on macOS, `NSWindow` and `NSView` are entirely separate classes.

To get a View's Window, there's two options fro the top of my head:

1. Get the window directly from the view (if it's mounted): https://developer.apple.com/documentation/appkit/nsview/1483301-window
  - This is the easiest if your view is already in the window. It sounds like in your case, it's not.
2. Get the window from the `NSApplication` object:
  - Every application has an `NSApplication` singleton that you can access all the windows of your app from: https://developer.apple.com/documentation/appkit/nsapplication/app_windows

**Comment by jihoobyeon** [comment]
> I'm not familiar with Babylon.JS so you may need to reach out to the team to add macOS support. It should be fairly straightforward if there's already iOS support. One difference you might run into between iOS and macOS is that on iOS, `UIWindow` is a subclass of `UIView` while on macOS, `NSWindow` and `NSView` are entirely separate classes.
> 
> To get a View's Window, there's two options fro the top of my head:
> 
> 1. Get the window directly from the view (if it's mounted): https://developer.apple.com/documentation/appkit/nsview/1483301-window. This is the easiest if your view is already in the window. It sounds like in your case, it's not.
> 2. Get the window from the `NSApplication` object. Every application has an `NSApplication` singleton that you can access all the windows of your app from: https://developer.apple.com/documentation/appkit/nsapplication/app_windows

Okay, I got it from second way! Thank you!
