### ISSUE TITLE
How do I enable new architecture for react-native-macos?

### ISSUE THREAD

**Issue by hsjoberg** [microsoft/react-native-macos#1841]
### Description

Hi guys. By reading the commit log and your [blog post for react-native-macos 0.71](https://devblogs.microsoft.com/react-native/2023-04-27-announcing-macos-71/), new architecture appears to be in experimental support.
However, I can't find any way to confirm that it's actually enabled.

I've set up latest canary (`npx react-native-macos-init --version 0.0.0-20230601-1643-b45a40a67`) and built the pods using `bundle install && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`. It looks Fabric-relevant pods are installed.

However upon starting a debug build up, I don't see any indication of new arch support, like you would do on Android and iOS:
`{"fabric":true,"initialProps":{"concurrentRoot":true},"rootTag":1}`

I get conventional non-new arch JSON:
`{"rootTag":1,"initialProps":{}}`

Furthermore, in AppDelegate.mm I don't see the `concurrentRootEnabled()` function like you would for iOS:
```
- (BOOL)concurrentRootEnabled
{
  return true;
}
```

Also in the macos Podfile there is no mention of new architectcure or Fabric.

Any suggestions on how I would enable new architecture?

---

I've also tried running new arch in rn-tester, but I'm instantly getting a crash. I'm not sure if this is expected, I can submit a separate bug report for this if you want me to.

### Version

b45a40a

### Output of `npx react-native info`

```
❯ npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 64.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 19.5.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.3.1 - /usr/local/bin/npm
    Watchman: 20201220.042258.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK:
      Android NDK: 20.0.5594570
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8815526
    Xcode: 14.3/14E222b - /usr/bin/xcodebuild
  Languages:
    Java: 15.0.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.8 => 0.71.8
    react-native-macos: 0.0.0-20230601-1643-b45a40a67 => 0.0.0-20230601-1643-b45a40a67
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to reproduce

`npx react-native-macos-init --version 0.0.0-20230601-1643-b45a40a67`
and
`RCT_NEW_ARCH_ENABLED=1 bundle exec pod install`

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by Saadnajmi** [comment]
I think our template app via 'react--native-macos-init' isn't updated to support the new arch is the short of it. We do support the new app creation stuff (like RCTAppDelegate to get stuff like the concurrentRootEnabled method) not at this moment, you'll have to create the app yourself.

**Comment by shwanton** [comment]
#1853 adds New Arch support to the macOS template app.
Once this PR is merged, you'll need to blow away the `macos` example & re-run `npx react-native-macos-init`
