### ISSUE TITLE
Font Family is not working if the font is not installed on the macBook.

### ISSUE THREAD

**Issue by aniketgupta8960** [microsoft/react-native-macos#1855]
### Environment

```markdown
react-native -v:0.64.0
npm ls react-native-macos:0.64.0-0
node -v:v20.3.0
npm -v:9.6.7
yarn --version:1.22.19
xcodebuild -version:14.1
```

### Steps to reproduce the bug

Add a custom font into mac app without installing that font in macbook then you will get the error of font family not recognised.

### Expected Behavior

It should not depend on macBook to install the custom font .It should work with installing the font in the mac

### Actual Behavior

![MRD8Y](https://github.com/microsoft/react-native-macos/assets/74759255/47410e96-d428-4bfa-8f12-bd2aed5dcdfc)

**Comment by aniketgupta8960** [comment]
Hi @Saadnajmi Can you please help me with the above issue. My fonts are showing in info.plist but they are not working on the debug or release build

**Comment by aniketgupta8960** [comment]
I have added the fonts in the assets folder and used the npx react-native link command to link the fonts. Also added the asset folder location in react-native-config file and cross checked that info.plist under the macos folder contains the fonts under UIAppFonts tag. The font files are also showing in copy bundle resource also

**Comment by aniketgupta8960** [comment]
<img width="1440" alt="Screenshot 2023-07-26 at 5 33 16 PM" src="https://github.com/microsoft/react-native-macos/assets/74759255/75a414ae-14b1-4849-a228-85c9c5a1fb47">
This is the react-native-config file with the project structure

**Comment by aniketgupta8960** [comment]
<img width="1440" alt="Screenshot 2023-07-26 at 5 33 40 PM" src="https://github.com/microsoft/react-native-macos/assets/74759255/53d310c6-29a1-4c09-aee5-e64bc2b98436">
this is info.plist containing the font

**Comment by aniketgupta8960** [comment]
[Archive.zip](https://github.com/microsoft/react-native-macos/files/12172164/Archive.zip)
These are the two font family that we have used

**Comment by aniketgupta8960** [comment]
@Saadnajmi Any update

**Comment by Saadnajmi** [comment]
I see you've used the key "UIFont" in your plist. I think that's actually iOS specific and you want "ATSApplicationFontsPath" for macOS?

https://stackoverflow.com/a/51665559
