### ISSUE TITLE
Spin animation are not centralized

### ISSUE THREAD

**Issue by aniketgupta8960** [microsoft/react-native-macos#1891]
### Description
When I use the spin animation on a view the animation is not centralized. They are rotated about top left point. I want the roation from center.

### Version

0.64.0-0

### Output of `npx react-native info`

System:
    OS: macOS 13.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 79.93 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
    Watchman: 2023.06.26.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.0 => 0.64.0 
    react-native-macos: ^0.64.0-0 => 0.64.30 
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

1-Create a Animated imagebackground and give this style -style={[
          {
            transform: [{ rotate: spin }]
          },
        ]
        }
2- start the animation then the  image will be rotated about top left not center.
### Snack, code example, screenshot, or link to a r

https://github.com/microsoft/react-native-macos/assets/74759255/b7ea30e5-fcd0-4295-801c-333430bd2f2a

Repository

**Comment by aniketgupta8960** [comment]
how can we disable RTL in macos ? Any information will be great help

**Comment by Saadnajmi** [comment]
Can you try with 0.71?

**Comment by aniketgupta8960** [comment]
Yes it is solved in 0.71
