### ISSUE TITLE
<TextInput /> with multiline on, caret always jumps to end of text

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#1921]
### Environment

```markdown
react-native -v: ^0.71.0
npm ls react-native-macos: 0.71.34
node -v: 18.15.0
npm -v: 
yarn --version: 1.22.19
xcodebuild -version:14E300c
```

### Steps to reproduce the bug

Create a `<TextInput/>` with multiline property, with value and onChangeText callbacks also set
Write some text
Try to add some text at the beginning of line, caret will jump to end of line

### Expected Behavior

Caret should always retain correct position

### Reproducible Demo

```ts
<TextInput
  autoFocus
  value={store.ui.note}
  onChangeText={store.ui.setNote}
  // @ts-expect-error
  enableFocusRing={false}
  placeholderTextColor={colors.neutral[400]}
  placeholder="Write something..."
  className="flex-1"
  multiline
  spellCheck
/>
```

**Comment by Saadnajmi** [comment]
I thought it was expected that setValue would move the cursor to the end of the text. Do you know if this is a regression from an earlier version?

**Comment by Saadnajmi** [comment]
Also an aside, you shouldn't need "@ts-expect-error" anymore if you import the type from react-native-macOS instead of react-native

**Comment by Saadnajmi** [comment]
Also an aside, you shouldn't need "@ts-expect-error" anymore if you import the type from react-native-macos instead of react-native

**Comment by ospfranco** [comment]
yeah, it broke on the big migration to 0.71

**Comment by Saadnajmi** [comment]
> yeah, it broke on the big migration to 0.71

From 0.68?

**Comment by ospfranco** [comment]
yeah, I think so. I was a long time ago, but it was immediately broken when the big merge happened.

**Comment by Saadnajmi** [comment]
Curious if it was broken and fixed upstream for iOS..
Thanks for the report, good to know it used to work 😅

**Comment by Saadnajmi** [comment]
Yeah this is a bug I run into frequently.. I took a crack at it earlier and didn't find a solution. Just wanted to give a small update

**Comment by ospfranco** [comment]
Just tested this again with `0.72.1` and it is working there.
