### ISSUE TITLE
How to control the title bar. Currently, there is no documentation mentioning it.

### ISSUE THREAD

**Issue by bear-ei** [microsoft/react-native-macos#1994]
### Summary

How to control the title bar.
For example, Electron and EW.js have corresponding modules or libraries that support manipulating the titleBar through JavaScript.  Such as making the titleBar transparent or modifying the style of the titleBar.

### Motivation

I'm currently trying to migrate my Electron-built macOS application to React Native for macOS, and I'm facing significant challenges regarding customizing the titleBar

**Comment by Victor0814gui** [comment]
I think there's an example of that here https://github.com/Simek/react-native-macos-reminders, I haven't tested it since I don't have a Mac, but from the thumbnail in the readme, you can see that there's some custom styling.

**Comment by bear-ei** [comment]
> I think there's an example of that here https://github.com/Simek/react-native-macos-reminders, I haven't tested it since I don't have a Mac, but from the thumbnail in the readme, you can see that there's some custom styling.

Thanks for the example, I've done the customization of the titleBar by bridging it with iOS Native Modules.
