### ISSUE TITLE
useWindowDimensions causes infinite re-rendering

### ISSUE THREAD

**Issue by bear-ei** [microsoft/react-native-macos#2083]
### Environment

```markdown
react-native -v: 0.72.9
npm ls react-native-macos: 0.72.13
node -v: 21.4.0
npm -v: 10.2.4
yarn --version: 4.0.2
xcodebuild -version: Xcode 15.2 Build version 15C500b
```

### Steps to reproduce the bug

Try to drag and drop to change the application window size after using useWindowDimensions.

```
export const Tooltip: FC<TooltipBaseProps> = () => {
    const windowDimensions = useWindowDimensions();

    return (
        <View>
            <Text>{windowDimensions.width}</Text>
        </View>
    );
};
```

### Additional context

 ▶︎ 'Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn\'t have a dependency array, or one of the dependencies changes on every render.',

**Comment by Saadnajmi** [comment]
I don't repro this with RNTester on either 0.72 or 0.73. Are you sure there isn't an extra `setState` somewhere in your app?


https://github.com/microsoft/react-native-macos/assets/6722175/6f2e1a22-3c5d-485f-854c-36745992cfcb

**Comment by Saadnajmi** [comment]
FWIW, React Native macOS also just supports setting the `tooltip` prop on any View/Text/Image.
