### ISSUE TITLE
No version of react-native-macos@^0.70.0-0 found!

### ISSUE THREAD

**Issue by nolife08021** [microsoft/react-native-macos#2089]
### Environment

```markdown
react-native -v: 0.70.3
npm ls react-native-macos:(empty)
node -v: v14.17.3
npm -v: v6.14.13
yarn --version:-
xcodebuild -version:Xcode 15.0.1
```

### Steps to reproduce the bug

1.cd to existing project (RN v0.70.3)
2.run "npx react-native-macos-init"

### Expected Behavior

successfully install and setup macos for RN project and able to run app in mac.

### Actual Behavior

I try install and setup in new create project RN v0.71.0 & v0.73.5, both working as expected. But just wondering is it working in v0.70.3? Test with newly create v0.70.3 also not working.
<img width="406" alt="Screenshot 2024-03-06 at 3 45 32 PM" src="https://github.com/microsoft/react-native-macos/assets/49778835/74ba37ce-721c-4dee-9764-603fcd72d014">

**Comment by Saadnajmi** [comment]
I believe we skipped straight from 0.68 to 0.71, so we never had a 0.70 version.
