### ISSUE TITLE
v0.74 Release

### ISSUE THREAD

**Issue by hassankhan** [microsoft/react-native-macos#2133]
### Summary

Would be great to see a v0.74 release soon.

### Motivation

Several changes upstream prevent `react-native-macos` from being added to a vanilla Expo project, or to the `bare-expo` test app in the Expo repository.

- https://github.com/facebook/react-native/pull/42263
- https://github.com/facebook/react-native/pull/41437
- https://github.com/facebook/react-native/pull/42591
- https://github.com/facebook/react-native/pull/42153

As @Saadnajmi mentioned on another issue, it would also be nice to see [`@react-native-community/cli`](https://github.com/react-native-community/cli/tree/main/packages/cli-platform-apple) integration too.

The docs also seem to perpetually recommend v0.71, it would be awesome if those got an update as well.

**Comment by jbcullis** [comment]
Any update on this? Having rn-macos lag behind is preventing us from moving to .74 on rn-windows.

**Comment by Saadnajmi** [comment]
React Native macOS 0.74 is still in progress, you can track the branch we're currently working on here: https://github.com/microsoft/react-native-macos/pull/2145

I don't think I can give a better timeline besides "I would like to release it before 0.75 releases"

**Comment by hassankhan** [comment]
Closing as release is available here: https://github.com/microsoft/react-native-macos/releases/tag/v0.74.1
