### ISSUE TITLE
react-native-asset

### ISSUE THREAD

**Issue by jhay06** [microsoft/react-native-macos#2144]
### Summary

Per checking using react-native-asset is not working in react-native-macos , 
it only links assets file for android and ios only .

### Motivation

some of the module used assets like antdesign package ,

**Comment by Saadnajmi** [comment]
Hi, someone would need to add macOS support to the repo. Given it's all JS, I feel it might be doable by the community. Till then, you could manually link fonts/other assets to your xcodeproj: https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app?language=objc
