### ISSUE TITLE
React-Codegen.modulemap not found after upgrading to v0.75.2

### ISSUE THREAD

**Issue by AdrianFahrbach** [microsoft/react-native-macos#2192]
### Environment

```markdown
react-native -v: v0.75.2
node -v: v20.12.1
npm -v: 10.5.0
yarn --version: Not in use
xcodebuild -version: Xcode 15.4 Build version 15F31d
```

### Steps to reproduce the bug

1. Clone the affected repo from [here](https://github.com/nice-af/chronos-app)
2. Install the dependencies and start the project with `nom start`
3. Open the MacOS Xcode project in the `macos` folder
4. Try building the project in Xcode. You should get an error.

### Actual Behavior

In Xcode I get this error:

```
module map file '/path/to/chronos-app/macos/Pods/Headers/Public/React_Codegen/React-Codegen.modulemap' not found
```

I guess there is some kind of package from RN missing?

### Additional context

To get the app working again after upgrading, I had to do some adjustments to the `Podfile`s. I also updated the `Gemfile`. I did that by creating a new RN macOS project and copying the respective files from the newly generated project to mine. I did have to remove a line from the macOS Podfile that disabled flipper (`:flipper_configuration => flipper_config`), so this may have something to do with it.

The changes that I did to upgrade can be seen in [this](https://github.com/nice-af/chronos-app/commit/0d8a907e6799e4e1376d2e9ea332631cb7d4093e) commit.

**Comment by AdrianFahrbach** [comment]
I found the issue!
The React Codegen modulemap folder used to be under this path:

```
"${PODS_ROOT}/Headers/Public/React_Codegen/React-Codegen.modulemap\"
```

But has been renamed from `React_Codegen/React-Codegen.modulemap` to `ReactCodegen/ReactCodegen.modulemap`, so this path is now correct:

```
"${PODS_ROOT}/Headers/Public/ReactCodegen/ReactCodegen.modulemap\"
```

So  I had to adjust my Swift flags.
The changes that I did can be found [here](https://github.com/nice-af/chronos-app/commit/8ebec06f2084e9dfcdd2ccedc37944c4f7a14c41#diff-883ee23ed3ad6f80c2b06acba98bcb33ea7b19c1c167905377f19a01511f0228), although only `macos/Chronos.xcodeproj/project.pbxproj` is where the party is at.

**Comment by Saadnajmi** [comment]
Sorry, I totally missed this. Glad you found a fix!

**Comment by AdrianFahrbach** [comment]
> Sorry, I totally missed this. Glad you found a fix!

No worries! I should have just checked the path before creating this issue 😅

**Comment by MatWaligora** [comment]
My case: upgrade from RN 0.76 to 0.81.5, multiple dependencies from react-native-firebase and react-native-reanimated

For me the fix to the local production build in xcode was to :
1. Open Xcode with project_name.workspace
2. Click on your project, then 
for each target go to Build Settings
￼
Search for React-Codegen
Click on each entry like this

<img width="999" height="67" alt="Image" src="https://github.com/user-attachments/assets/973bde32-2fd9-4dfb-97fe-d5d5ee917c50" />

check for any path that contains React-Codegen and remove this entry.
