### ISSUE TITLE
0.76.2 yarn install gives @react-native-mac/virtualized-lists@npm:0.76.2: No candidates found

### ISSUE THREAD

**Issue by dngrhm** [microsoft/react-native-macos#2282]
### Environment

```markdown
react-native -v:
npm ls react-native-macos:
node -v: v22.6.0
npm -v: 10.8.2
yarn --version: 4.4.0
xcodebuild -version:Xcode 16.1 - Build version 16B40
```

### Steps to reproduce the bug

1. Update package.json `"react-native-macos": "0.76.2"`
2. run `yarn install` or `npm install`
3. Observe error about @react-native-mac/virtualized-lists@0.76.2
4. Check [npmjs](https://www.npmjs.com/package/@react-native-mac/virtualized-lists) to observe the latest version is 0.76.0

react-native-macos package version depends on unreleased version 0.76.2 of @react-native-mac/virtualized-lists.  There is a 0.76.2 version of @react-native/virtualized-lists but not @react-native-mac/virtualized-lists

### Expected Behavior

yarn or npm install succeeds

### Actual Behavior

yarn and npm install fail

### Reproducible Demo

any react-native-macos project

**Comment by dngrhm** [comment]
This also causes a failure in the [getting started docs](https://microsoft.github.io/react-native-windows/docs/rnm-getting-started) If you don't force 0.71 at the beginning. 

> npx react-native-macos-init
Reading application name from package.json…
Reading react-native version from node_modules…
Reading react-native-macos version from node_modules…
Latest matching version of react-native-macos for react-native@0.76.2 is react-native-macos@0.76.2.
Installing react-native-macos@^0.76.0-0…
Command failed: npm install --save --silent "react-native-macos@^0.76.0-0" Error: Command failed: npm install --save --silent "react-native-macos@^0.76.0-0"
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at <redacted>/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:228:42
    at Generator.next (<anonymous>)
    at fulfilled (<redacted>/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:11:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 23646,
  stdout: <Buffer >,
  stderr: <Buffer >
}

**Comment by Saadnajmi** [comment]
Oof, thanks for the report. I'll try to get this fixed early next week. Meanwhile I think just use 0.76.0

**Comment by oktaysenkan** [comment]
```sh
npx react-native-macos-init --version 0.76.0
```

**Comment by Meryldominguez** [comment]
also having this issue, even when forcing certain packages to be older versions and with a fresh node_modules install


package.json:

```
 "dependencies": {
   ...
    "react-native": "0.76.0",
   ...
  },
  "devDependencies": {
   ...
    "@react-native-mac/virtualized-lists":"0.76.0",
    "react-native-macos": "0.76.0",
    ...
  },

```

terminal readout:
````
meryldominguez@Ourania appName % npx react-native-macos-init --verbose=true
Reading application name from package.json…
Reading react-native version from node_modules…
Reading react-native-macos version from node_modules…
Latest matching version of react-native-macos for react-native@0.76.0 is react-native-macos@0.76.2.
Upgrading to react-native-macos@^0.76.0-0…
npm error code ETARGET
npm error notarget No matching version found for @react-native-mac/virtualized-lists@0.76.2.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
npm error A complete log of this run can be found in: /Users/meryldominguez/.npm/_logs/2024-11-20T13_31_11_208Z-debug-0.log
Command failed: npm install --save "react-native-macos@^0.76.0-0" Error: Command failed: npm install --save "react-native-macos@^0.76.0-0"
    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:882:11)
    at execSync (node:child_process:954:15)
    at /Users/meryldominguez/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:228:42
    at Generator.next (<anonymous>)
    at fulfilled (/Users/meryldominguez/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:11:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 51625,
  stdout: null,
  stderr: null
}
```

**Comment by DanielSRS** [comment]
@Saadnajmi Tried 0.76.0 as you suggested with: `npx react-native-macos-init --version 0.76.0` 

but while it inits the project succesfully:

- it aways fails to build with `react-native run-macos` as someone else reported in #2287 
- If I open the project in Xcode and run, it builds, but crashes even before showing a window

**Comment by Saadnajmi** [comment]
Thanks for the other bug, I'll look at both today.

**Comment by nnphong1904** [comment]
@Saadnajmi is there any update on this?

**Comment by Saadnajmi** [comment]
This should be fixed with `0.76.3`

**Comment by Saadnajmi** [comment]
... but it came back with RNM `0.76.4`. Ugh, sorry, I'll fix that. But just use `0.76.3` for now...

**Comment by Saadnajmi** [comment]
fixed

**Comment by dngrhm** [comment]
Thank you!
