### ISSUE TITLE
[0.76] npx react-native-macos-init fails

### ISSUE THREAD

**Issue by DanielSRS** [microsoft/react-native-macos#2304]
### Environment

```markdown
react-native -v: 0.76.3
npm ls react-native-macos: react-native-macos@0.76.4
node -v: v21.7.1
npm -v: 10.5.0
yarn --version: 4.5.3
xcodebuild -version: Xcode 16.1
```

### Steps to reproduce the bug

1. Create a new RN project with `npx @react-native-community/cli@latest init AwesomeProject --install-pods false`
2. Go to project folder `cd AwesomeProject`
3. Init react native macos `npx react-native-macos-init`

### Expected Behavior

The react native macos project to be initialized

### Actual Behavior

It fails with this error:

> Command failed: npm install --save --silent "react-native-macos@^0.76.0-0" Error: Command failed: npm install --save --silent "react-native-macos@^0.76.0-0"

### Additional context

The command error is not descriptive, and gives no info abou what went wrong, but I noticed that it fails if any dependencies versions are not met.

- With the latest 0.76.4 RNM release, It tries to install its dependencies with the same version (0.76.4) and fails if not found any.
- I needed to pin some dependencies with resolutions for it to work, 

```json
"resolutions": {
  "@react-native/assets-registry": "0.76.3",
  "@react-native/codegen": "0.76.3",
  "@react-native/community-cli-plugin": "0.76.3",
  "@react-native/gradle-plugin": "0.76.3",
  "@react-native/js-polyfills": "0.76.3",
  "@react-native/normalize-colors": "0.76.3"
},
```
Then, it works again: npx react-native-macos-init
#### This issue do not happen with 0.76.3, so `npx react-native-macos-init --version 0.76.3` works as expected

**Comment by Saadnajmi** [comment]
oof, thanks for the report. I'll work on fixing that!

**Comment by Saadnajmi** [comment]
Can you try `0.76.5`?

**Comment by DanielSRS** [comment]
Yes, I tested it and it worked great! 🥳
I created a new project with 0.76.5 and there was no issues running `npx react-native-macos-init`

I think this is fixed an can be closed,
thank you!
