### ISSUE TITLE
Contribute isDevModeEnabled in Release upstream

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#241]
This fork of react-native has refactored such that the compile time `#if RCT_DEV` constructs are now a runtime settings via `[[bridge devSettings] isDevModeEnabled]`.

This allows a product to allow debugging of react-native in Release builds of the native app.

(internal https://office.visualstudio.com/APEX/_workitems/edit/3237395)

**Comment by Saadnajmi** [comment]
This feature is removed, so I'm closing this.
