### ISSUE TITLE
Nesting ScrollView scrolling behavior

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#270]
Issue on macOS with ScrollView nested in ScrollView.
Inner scroll view preventing outer Scrollview from scrolling if scrollwheel event happens in inner ScrollView.
Manfiests in RNTester FlatList and SectionList.
Regression.

**Comment by ShivamJoker** [comment]
Only the outer scroll view works I am trying to use both horizontal and vertical scroll but it's not working.
Please fix this issue as well.

**Comment by zetachang** [comment]
Is this ever get fixed?
