### ISSUE TITLE
Transforms

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#280]
Rotations are broken – NOP.

**Comment by sahrens** [comment]
It seems like more than just rotations are broken. I'm going to take a look at this.

**Comment by sahrens** [comment]
Can you add the Facebook partner tag and assign to me?

**Comment by sahrens** [comment]
Current state:

iOS (correct)|MacOS
-------------|-------
<img width="415" alt="Screen Shot 2020-06-04 at 4 32 09 PM" src="https://user-images.githubusercontent.com/1509831/83820366-5bd68980-a681-11ea-94be-5eac07ddb767.png">|<img width="464" alt="Screen Shot 2020-06-04 at 4 18 29 PM" src="https://user-images.githubusercontent.com/1509831/83820381-642ec480-a681-11ea-9a2f-d8780dfdd2cb.png">

**Comment by sahrens** [comment]
Ok I have it all fixed up. Putting up some PR's now.

**Comment by Saadnajmi** [comment]
This is indeed fixed for 0.66+
