### ISSUE TITLE
ImageBackground Rendering issue

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#301]
The ImageBackground component used in the Header of NewAppScreen leaves after images as a window is resized.

**Comment by mgcrea** [comment]
Looks like the `<Image />` component has this issue as well:

```
<Image
        style={{width: 280}}
        source={require('./../fixtures/lens-exif.png')}
      />
```

Where 280 = actualWidth / 2 does produce similar artifacts.
