### ISSUE TITLE
[Hermes] Hermes from source podspec

### ISSUE THREAD

**Issue by alloy** [microsoft/react-native-macos#319]
In reference to https://github.com/react-native-community/discussions-and-proposals/projects/1#card-34851105

For now, this issue will serve as a place for me to keep track of questions I come up with as I navigate the source code and build system.

I had started on a **“build from source”** podspec, but because it has some hurdles (e.g. requires running `cmake` to generate some arch specific headers) and Hermes thus far has 
provided binary distributions (which makes sense, it seems unlikely a RN dev will debug the engine), I’ll switch to making a **“binary podspec”**. Once everything is done, I’ll circle back to the **“build from source”** one.

**Comment by alloy** [comment]
Looks like the `--static-link` flag is more about building static versions of the CLI tools.

**Comment by alloy** [comment]
# Build from source

- [x] Q: Does Hermes support [building statically on macOS](https://github.com/facebook/hermes/issues/156#issuecomment-560542113) nowadays? RN through CocoaPods is able to build both static and dynamic, so this should ideally be possible.
    A: Looks like the `--static-link` flag is more about building static versions of the CLI tools.
- [ ] Q: Figure out what targets we need to build.
    A: Looks like we want to build the bits that make up `libhermes.dylib`:
    - [ ] `libLLVHSupport.a`
    - [ ] `libLLVHDemangle.a`
    - [ ] `libhermesFrontend.a`
    - [ ] `libhermesOptimizer.a`
    - [ ] `libhermesVMRuntime.a`
    - [ ] `libhermesInst.a`
    - [ ] `libhermesFrontEndDefs.a`
    - [ ] `libhermesADT.a`
    - [ ] `libhermesAST.a`
    - [ ] `libhermesParser.a`
    - [ ] `libhermesSourceMap.a`
    - [ ] `libhermesSupport.a`
    - [ ] `libhermesBackend.a`
    - [ ] `libhermesHBCBackend.a`
    - [ ] `libhermesRegex.a`
    - [ ] `libhermesPlatform.a`
    - [ ] `libhermesPlatformUnicode.a`
    - [x] `libdtoa.a`
    - [x] `libjsi.a`
- [x] Q: Figure out what other dynamic dependencies it needs.
    A: Seems like it needs only system libraries:
    ```
    $ otool -L API/hermes/Debug/libhermes.dylib
    API/hermes/Debug/libhermes.dylib:
            @rpath/libhermes.dylib (compatibility version 0.0.0, current version 0.0.0)
            /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1675.129.0)
            /usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 64.2.0)
            /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 902.1.0)
            /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
    ```
- [ ] Q: Can Hermes’ copy of `jsi` be shared with [RN’s copy](https://github.com/facebook/react-native/blob/master/ReactCommon/jsi/React-jsi.podspec) [and trim some fat from the bundle]?
- [ ] Q: There are 4 configurations, namely: `Debug`, `Release`, `MinSizeRel`, and `RelWithDebInfo`. Which 2 do we use in the podspec?

    `Release` should use `MinSizeRel`, that much is clear. (I assume this equates to the `--distribute` option in Hermes’ configuration script.)

    As for `Debug` I assume that Hermes’ `Debug` configuration is more useful when developing Hermes, rather than using it, in which case it may make sense to use the `RelWithDebInfo` configuration in `Debug`?
- [ ] Q: What are the following `GCC_PREPROCESSOR_DEFINITIONS` for?
    * `HERMES_SLOW_DEBUG`
    * `HERMES_ENABLE_DEBUGGER`
- [ ] Q: Why is the `HERMES_ENABLE_DEBUGGER` entry of `GCC_PREPROCESSOR_DEFINITIONS` seemingly enabled in all [release] targets in upstream?

**Comment by alloy** [comment]
# Binary

**Comment by mhorowitz** [comment]
@alloy I'm really looking forward to this project!  I can answer some of your questions off the top of my head.  I may need to get others to help with the rest.  In particular, I don't know cmake very well, so I can't help much there.
>  Q: Can Hermes’ copy of jsi be shared with RN’s copy [and trim some fat from the bundle]?
Yes, that should be fine, and may avoid issues.
>  Q: What are the following GCC_PREPROCESSOR_DEFINITIONS for?
>     HERMES_SLOW_DEBUG
We build hermes in three different modes at FB.  We call them opt, dev, and dbg.  (I am not sure how these map onto cmake configurations.)  opt is for product releases and perf measurement.  dev is used by RN and other app developers who use Hermes.  It enables a bunch of assertions and other tests which validate correct behavior internally, and that it is being used correctly by callers.  These tests incur a runtime penalty, which is why we don't enable them in production builds.  dbg is for people working on the Hermes engine itself.  It is like dev, except a handful more tests are enabled which are so slow that they significantly impact the developer experience.  HERMES_SLOW_DEBUG is the preprocessor macro which, when defined, enables the tests which are enabled for dbg but not dev builds.
>  Q: Can we make a single static lib that contains the objects of all the above static libs?
As a general rule, .a files can be combined. It might be possible to do in cmake as well, but I wouldn't be able to say how.
>  Q: How do we create the include dir structure that’s distributed?
Because JSI uses virtual dispatch, hermes/hermes.h doesn't depend on any of the internal headers of the VM.  So you should only need to export hermes/Public/ and jsi/.  (Right this moment, there is a hermes/VM file included in hermes.h, but this is an error and it should be fixed shortly.)

**Comment by neildhar** [comment]
> Q: Can we make a single static lib that contains the objects of all the above static libs?

Just to add to this, I believe we currently do build a static version of libhermes.dylib called libhermesapi.a

**Comment by tmikov** [comment]
> There are 4 configurations, namely: Debug, Release, MinSizeRel, and RelWithDebInfo. Which 2 do we use in the podspec? Release should use MinSizeRel, that much is clear. (I assume this equates to the --distribute option in Hermes’ configuration script.)

On desktop it might be preferable to use "Release", because presumably binary size is not that critical.

>  HERMES_ENABLE_DEBUGGER

This setting enables the JavaScript debugging functionality in Hermes. Previously that came with non-trivial performance overhead, so we only enabled it in debug builds of Hermes itself. But these days the overhead is minimal, so we decided to enable it by default for non-mobile builds, just to decrease the number of possible configurations.

If you don't need the debugger functionality, you should probably set it to OFF.

> Can we make a single static lib that contains the objects of all the above static libs?

Yes, this has been brought up many times internally too. The current library structure wasn't really meant for distribution. We will look into this and post back here.

**Comment by alloy** [comment]
Heyy, thanks for chiming on this, folks.

> > Q: Can Hermes’ copy of jsi be shared with RN’s copy [and trim some fat from the bundle]?
> 
> Yes, that should be fine, and may avoid issues.

👍 This would pertain to the “build from source” option, which I’ve punted on for now in favour of getting a binary distribution working first.

> > Q: What are the following GCC_PREPROCESSOR_DEFINITIONS for?
> > HERMES_SLOW_DEBUG
> 
> […] `HERMES_SLOW_DEBUG` is the preprocessor macro which, when defined, enables the tests which are enabled for dbg but not dev builds.

👍 

> > Q: How do we create the include dir structure that’s distributed?
> 
> Because JSI uses virtual dispatch, hermes/hermes.h doesn't depend on any of the internal headers of the VM. So you should only need to export hermes/Public/ and jsi/. (Right this moment, there is a hermes/VM file included in hermes.h, but this is an error and it should be fixed shortly.)

Ah, great; yeah it was the VM header include in `hermes.h` that made this necessary, but this makes sense 👍

**Comment by alloy** [comment]
Regarding the static libs, I was thinking to change the pipeline to first create a single archive that contains all the various components and then use that as a single input for the dylib, which would leave us with complete static and dynamic versions. Let me know if you have other ideas or are already making such changes. (I’m not familiar with cmake, but was looking forward to dipping my toes.)

**Comment by alloy** [comment]
> > There are 4 configurations, namely: Debug, Release, MinSizeRel, and RelWithDebInfo. Which 2 do we use in the podspec? Release should use MinSizeRel, that much is clear. (I assume this equates to the --distribute option in Hermes’ configuration script.)
> 
> On desktop it might be preferable to use "Release", because presumably binary size is not that critical.

Makes sense 👍 

> > HERMES_ENABLE_DEBUGGER
> 
> This setting enables the JavaScript debugging functionality in Hermes. Previously that came with non-trivial performance overhead, so we only enabled it in debug builds of Hermes itself. But these days the overhead is minimal, so we decided to enable it by default for non-mobile builds, just to decrease the number of possible configurations.
> 
> If you don't need the debugger functionality, you should probably set it to OFF.

In binary distributions, it would probably be preferable to ship a single binary, so I’ll leave this on, for now at least.

**Comment by alloy** [comment]
> So you should only need to export `hermes/Public/` and `jsi/`. (Right this moment, there is a hermes/VM file included in hermes.h, but this is an error and it should be fixed shortly.)

@mhorowitz Btw, I noticed the current npm release does not include the `jsi` headers; I suppose it builds because it’s using the jsi headers provided by RN at build time (?). Is that intended?

**Comment by tmikov** [comment]
@alloy Can you give me some more context? Are you planning to ship a static library "libhermes.a"? If not, why is it a problem that the CMake build generates multiple separate .a libraries, as long as in the end it produces a single dylib?

**Comment by alloy** [comment]
@tmikov RN for Apple platforms in OSS builds using the CocoaPods dependency manager. It favours source builds over binary distribution and allows the dev to choose wether to build as static or dynamic libs. Because Hermes currently ships binaries for Android and the build takes a bit of time to perform, I decided to settle on binary distribution for the time being. Ideally that would eventually mean the dev can choose either a static or a dynamic binary, as some other platforms can benefit from static linkage. However, I may also end up deciding to finish the source build instead.

Anyways, for now I’ll continue other related work based on the existing dylib and circle back to this later on.

**Comment by tmikov** [comment]
@alloy Got it. So you want to be able to ship a static and a dynamic lib Hermes binary. So, we just need to add another target or tweak an existing one. We can definitely do that.

**Comment by mhorowitz** [comment]
>  I noticed the current npm release does not include the jsi headers;

@alloy I think this is just an oversight.  We should be shipping jsi headers.

**Comment by alloy** [comment]
@mhorowitz I also noticed that the bundled `jsi` does not have its symbols exported, which to an app that does not include its own copy of `jsi` means it can’t build e.g. a `StringBuffer`. I don’t know to what extend you want to support non-RN apps, but it may be better to build `libjsi.dylib` separately and share it between `libhermes.dylib` and the app? Anyways, not something that is blocking my work.

**Comment by willholen** [comment]
> > I noticed the current npm release does not include the jsi headers;
> 
> I think this is just an oversight. We should be shipping jsi headers.

These headers will be added to NPM releases from now on: https://github.com/facebook/hermes/commit/f20f5b37a3d84213495b535cc23c2596373f70ab

**Comment by ivanmoskalev** [comment]
Has there been any sort of progress on this?

**Comment by Saadnajmi** [comment]
This will probably be addressed when we merge 0.70, where Hermes is built from source.

**Comment by prabhuvi** [comment]
I want to build hermes as a static library. Can someone please suggest the changes to be done?

**Comment by Saadnajmi** [comment]
If you just run `USE_HERMES=1  pod install` (as you would on iOS) it should build Hermes with your react native app. We don't support using prebuilts yet.

**Comment by prabhuvi** [comment]
I am able to build hermes framework with this flag turned on but the file generated is a dynamic/shared library. I want to generate a static library. What are the necessary changes in the cmake or other files?
