### ISSUE TITLE
Issues creating a native module for NSSplitView

### ISSUE THREAD

**Issue by mgcrea** [microsoft/react-native-macos#324]
Hope it's ok to share that here but I'm trying to create a native module for a macOS`NSSplitView`, I'm hitting some touch related issues that seems to indicate that a non trivial native implementation might be needed: the left pane never register touches:

![Screen Recording 2020-04-27 at 23 54 51](https://user-images.githubusercontent.com/108273/80424815-bf330600-88e2-11ea-99ef-aafbd5a48e4b.gif)

*edit*: also if you click on the left pane at the height of the `Click me #2!` button (which is located on the right pane but you click where it would be if the left pane did not exist), it still triggers the `onPress` on button as well. So it looks like both view touches are sent to the right-most view? 

I can also see the following error in XCode, obviously related:

```
~/Developer/react-native-macos/react-native-macos-sandbox/node_modules/react-native-macos/React/Base/RCTTouchHandler.m:111
2020-04-27 23:45:00.681409+0200 MacOSSandbox[10571:4313998] [General] Touch is already recorded. This is a critical bug.
2020-04-27 23:45:00.692835+0200 MacOSSandbox[10571:4313998] [General] (
	0   CoreFoundation                      0x00007fff39141d07 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff71e655bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3916aec8 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff3b894456 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   MacOSSandbox                        0x000000010014e702 -[RCTTouchHandler _recordNewTouches:] + 578
	5   MacOSSandbox                        0x0000000100150923 -[RCTTouchHandler interactionsBegan:] + 83
	6   MacOSSandbox                        0x0000000100150c97 -[RCTTouchHandler mouseDown:] + 151
	7   AppKit                              0x00007fff36576574 -[NSWindow(NSGestureRecognizer_Routing) _sendEventToGestureRecognizers:requireAcceptsFirstMouse:] + 2696
	8   AppKit                              0x00007fff3657e235 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4839
	9   AppKit                              0x00007fff364e8a81 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
	10  AppKit                              0x00007fff364e7e29 -[NSWindow(NSEventRouting) sendEvent:] + 349
	11  AppKit                              0x00007fff364e61b4 -[NSApplication(NSEvent) sendEvent:] + 352
	12  AppKit                              0x00007fff3633321f -[NSApplication run] + 707
	13  AppKit                              0x00007fff36304ff6 NSApplicationMain + 777
	14  MacOSSandbox                        0x0000000100001c12 main + 34
	15  libdyld.dylib                       0x00007fff7300ccc9 start + 1
)
``` 

I've published a very basic/naive implementation here:  https://github.com/mgcrea/react-native-macos-splitview (example in the README).

I've looked into the `<ScrollView />` that seem to wrap the native module with `RCTView` and manage subviews with `insertReactSubview`, I've tried to make something alike work but so far no luck.

So I'm wondering if there could be a simple fix to the first/published straightforward implementation. Any ideas on the way forward?

Thanks!

**Comment by tom-un** [comment]
Hi @mgcrea .   I think the reason for the lack of touch events and the RCTAssert above is because in `RCTTouchHandler.m` in the `_recordNewTouches` method there is logic to set `_shouldSendMouseUpOnSystemBehalf` for special cases such as `NSControls` and `NSText`.   It may be that another case is needed for `NSSplitView`.   You could try locally modifying the code to add a case for `NSSplitView`.   Longer term we may need to provide a method that `RCTView` sublcasses can override, like a `shouldSendMouseUp` method or something.

Besides the touch issue, I do think you are going to need a less trivial implemented for other reasons.    In a purely native app, an `NSSplitView` may have two or more `NSView` subviews that it lays out.   React-native wants to use Yoga/FlexBox layout on its subviews.   You're going to have a clash between RN and NSSplitView both wanting to layout these child views.

You may want to look at `<Modal>` component and the `RCTModal*` classes for inspiration.   In `Modal` the subcomponents get projected to a completely separate subview hierarchy: `<Modal>` itself is part of the main react-native `UIView` hierarchy, but the children become part of a separate `UIView` hierarchy hosted in a proxy `RCTView` in a separate `UIWindow`.    I think for a `<SplitView>` you're going to want to do something similar: the `<SplitView>` itself will be part of the main hierarchy, and it will be projected as an `NSSplitView`, but then perhaps you could have two proxy `NSView` for the two panes and then project the children of the two `<View>`'s inside the two proxy views.   It may require another component definition: something like `<SplitView><SplitPane>... contents of left pane...</SplitPan><SplitPane>... contents of right pane ...</SplitPane></SplitView>`.

**Comment by mgcrea** [comment]
Thanks a lot for the help/guidelines!

**Comment by mgcrea** [comment]
@tom-un I've tried a few things but alas I quickly hit a roadblock:

In `_recordNewTouches`, the resolved `NSView *targetView = [self.view hitTest:touchLocation];` is always pointing on the right `RCTView` pane of the split view (even when clicking on the left pane, will give negative X coords in that case). It sometimes point to the actual `NSSplitView` parent when clicking on the divider or close to the outer edges or sometimes maybe when the window isn't focused).

So the underlying touch issue seems to be that the `[RCTRootContentView.view hitTest]` call seems to return a bad view, and to my current understanding it's a pure NSView hierarchy call so might not be a react-native issue?

What is strange is that when you debug the view hierarchy everything looks OK so not sure why the root NSView is getting confused. Wrapping the NSSplitView inside a RCTView and manually adding the subViews to the child splitView does not change anything.

Will keep trying a few things but I'm starting to wonder if it might not be easier to rebuild a splitview component from the js side (but not sure if currently doable).

**Comment by tom-un** [comment]
Take a look at `RCTModalHostView.m`.   It has its own `RCTTouchHandler`.   I think you're going to have to do something similar.

**Comment by mgcrea** [comment]
Did try to setup my own touch handler looking at `RCTInputAccessoryView.m` that does the same trick, but attaching it to any of the subviews did not change the broken behavior.

However, implementing a basic `hitTest` did seem to fix most issues.

```objective-c
- (NSView *)hitTest:(NSPoint)aPoint {
  for (NSView *subview in self.subviews) {
    if (!subview.isHidden && [subview hitTest:aPoint])
      return subview;
  }
  return nil;
}
```

Both touches are now properly working! But as you predicted, now I can see both the SplitView and Yoga fighting for layout.

> but the children become part of a separate UIView hierarchy hosted in a proxy RCTView in a separate UIWindow

Is a separate UIWindow required to have separate hierarchy? In my case it would mean that I should have two separate NSWindow for each pane.

I did implement my desired behavior in pure javascript: see [SplitView.tsx](https://github.com/mgcrea/react-native-macos-splitview/blob/master/src/SplitView.tsx). Having some minor issues with the cursor and performance.

Thanks again for the guidance!

**Comment by mgcrea** [comment]
Quick update, still not working after a few other tries. Unfortunately inserting an `NSView` between the `NSSplitView` does not fixes the layout issues, (but it does change the layout).

<img width="378" alt="Screenshot 2020-05-03 at 00 25 00" src="https://user-images.githubusercontent.com/108273/80893641-8aed8a00-8cd4-11ea-8e09-4774a4dcd128.png">
<img width="748" alt="Screenshot 2020-05-03 at 00 25 23" src="https://user-images.githubusercontent.com/108273/80893646-95a81f00-8cd4-11ea-96b5-c100a264ff79.png">

Somehow the constraints are not synced, which is the same issue without intermediate NSView, basically the grandchild RCTView does not reflect the change of its parent (be it a RCTView or a NSView) when those changes are initiated by the `NSSplitView`, here an example without intermediate NSView with the view that won't properly adjust highlighted:

<img width="400" alt="Screenshot 2020-05-03 at 00 37 24" src="https://user-images.githubusercontent.com/108273/80893848-4367fd80-8cd6-11ea-95f0-657fd0654480.png">
<img width="616" alt="Screenshot 2020-05-03 at 00 37 29" src="https://user-images.githubusercontent.com/108273/80893854-4662ee00-8cd6-11ea-860d-9e477706f0b4.png">

**Comment by tom-un** [comment]
After adding the subviews to the NSSplitView, did you call NSSplitView's adjustSubviews method? 
 I still think you're going to need a <SplitPane> component and in its ShadowView you can have control over how its laid out by react -- or in this case make it *not* be laid out by react :).    You're going to want these SplitPanes to just let the parent NSplitView control layout completely.    If you want to push the latest to your branch I can take a look.

**Comment by mgcrea** [comment]
@tom-un, yep indeed would be great if there was some kind of public boolean on an RCTView to toggle the yoga layout. Digging into the multiple layers of react-native view rendering is a bit arcane to me!

I've also found out that I can manually update the grandchildren frames (with `setFrame` in `splitViewDidResizeSubviews`) with something like:

```objective-c
    for (RCTView *grandSubview in subview.subviews) {
      [grandSubview setFrame:NSMakeRect(0, 0, size.width, size.height)];
      [grandSubview setNeedsDisplay];
    }
```

And that works to fix the grandchild layout, but alas, the grandchildren children won't get their layout updated...! So it looks like it's not propagating changes (and I guess recursing through all subviews isn't the way forward).

<img width="805" alt="Screenshot 2020-05-03 at 11 54 35" src="https://user-images.githubusercontent.com/108273/80911148-de8fc000-8d34-11ea-9059-83ae93074ba5.png">

I've published my wip sandbox project (should be ready to run) in a [sandbox branch](https://github.com/mgcrea/react-native-macos-splitview/tree/sandbox), native module is in the [modules/](https://github.com/mgcrea/react-native-macos-splitview/tree/sandbox/modules/RNSplitView/macos) subfolder.

Thanks!

**Comment by Simek** [comment]
@tom-un The same error appears for me when [Contextual Menu](https://developer.apple.com/design/human-interface-guidelines/macos/menus/contextual-menus/) for `TextInput` is open and a Touchable with `onPress` defined have been pressed for the second time (first click just closes the Contextual Menu, and event is not passed to the Touchable).

```
020-08-03 21:24:21.389932+0200 Reminders[10623:1878807] *** Assertion failure in -[RCTTouchHandler _recordNewTouches:](), /Users/simek/projects/macOSWorkbench/node_modules/react-native-macos/React/Base/RCTTouchHandler.m:111
2020-08-03 21:24:21.390136+0200 Reminders[10623:1878807] [General] Touch is already recorded. This is a critical bug.
2020-08-03 21:24:21.393359+0200 Reminders[10623:1878807] [General] (
	0   CoreFoundation                      0x00007fff39031be7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff71e095bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3905ad98 +[NSException raise:format:arguments:] + 88
	3   Foundation                          0x00007fff3b7883b6 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 166
	4   Reminders                           0x00000001001b8422 -[RCTTouchHandler _recordNewTouches:] + 578
	5   Reminders                           0x00000001001ba643 -[RCTTouchHandler interactionsBegan:] + 83
	6   Reminders                           0x00000001001ba9b7 -[RCTTouchHandler mouseDown:] + 151
	7   AppKit                              0x00007fff3645e104 -[NSWindow(NSGestureRecognizer_Routing) _sendEventToGestureRecognizers:requireAcceptsFirstMouse:] + 2696
	8   AppKit                              0x00007fff36465dc5 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4839
	9   AppKit                              0x00007fff363d0611 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
	10  AppKit                              0x00007fff363cf9b9 -[NSWindow(NSEventRouting) sendEvent:] + 349
	11  AppKit                              0x00007fff363cdd44 -[NSApplication(NSEvent) sendEvent:] + 352
	12  AppKit                              0x00007fff3621adaf -[NSApplication run] + 707
	13  AppKit                              0x00007fff361ecb86 NSApplicationMain + 777
	14  Reminders                           0x00000001000016f2 main + 34
	15  libdyld.dylib                       0x00007fff72fb0cc9 start + 1
```

The source code of my test/sample app is here: https://github.com/Simek/react-native-macos-reminders
