### ISSUE TITLE
Skip bundling for macOS platform when in Debug mode

### ISSUE THREAD

**Issue by mgcrea** [microsoft/react-native-macos#334]
Probably sure it changed with the 0.61.x releases, I noticed unusual long build times while playing with native modules.

I think we should change [this line in react-native-xcode.sh#L35](https://github.com/microsoft/react-native/blob/v0.61.0-microsoft.5/scripts/react-native-xcode.sh#L35) to `if [[ "$PLATFORM_NAME" == *simulator || "$PLATFORM_NAME" == macosx ]]; then` so that bundling is not done when running in debug mode.

Build times (hot cache) went from 5+seconds back to nearly instant.

**Comment by tom-un** [comment]
Thanks.  We used to have a || macosx before, I must have stomped on it during the .61 merge.
