### ISSUE TITLE
AlertMacOS should be deprecated in favor of Alert

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#354]
Upstream react-native has `Alert` which works on iOS and Android.
`Alert` has an `options` argument that can contains a couple Android specific options.
`AlertIOS` also exists with some iOS specific options, but has been deprecated upstream.
`AlertMacOS` was created in the fork to be similar to `AlertIOS` and address macOS specific concerns.
`AlertMacOS` should now be deprecated and replaced by additional macOS specific options in the `Alert` `options` argument.

The macOS specific keys which are currently implemented under the covers in the `RCTAlertManager.alertWithArgs` method are:
```
    defaultInputs?: DefaultInputsArray,
    modal?: ?boolean,
    critical?: ?boolean,
```
The `DefaultInputsArray` is an array of objects each with:
```
  /**
   * Default input
   */
  default?: string,
  /**
   * Placeholder input
   */
  placeholder?: string,
```
to set the default text and placeholder string of the text inputs.   It can contain 1 or 2 objects: 2 objects if the alert type is `login-password`

`modal` makes the Alert appear as a modal dialog instead of a sheet.

`critical` makes the Alert icon an exclamation mark instead of the app icon.

**Comment by anhdevit** [comment]
How can I fix that issue? @tom-un
