### ISSUE TITLE
[Hermes] Add ‘trace’ support

### ISSUE THREAD

**Issue by alloy** [microsoft/react-native-macos#365]
If I understand things correctly, the ‘systrace’ code in RN (specifically for Android) relies on a non-oss FB tool called `fbsystrace`. It appears that RN for Windows has implemented [their own version](https://github.com/microsoft/react-native-windows/tree/master/vnext/ReactWindowsCore/tracing), so we should look into creating one too. Probably in a manner that interfaces well with Instruments.app.

**Comment by alloy** [comment]
@mhorowitz @NickGerleman Is my understanding here correct?

**Comment by NickGerleman** [comment]
That sounds correct. @mganandraj will have more context than I do.

**Comment by mganandraj** [comment]
@alloy that's correct. We planned to create a fbsystrace open source library but it never materialized .. We had an fbsystrace implementation for ANdroid platform too in the past which we used extensively for perf analysis couple of years back .. 

https://office.visualstudio.com/ISS/_git/sdx-platform?path=%2Fsrc%2Freact-native%2FReactCommon%2Fcxxreact%2Ffbsystrace.cpp&version=GBJSI&_a=contents

https://office.visualstudio.com/ISS/_git/sdx-platform?path=%2Fsrc%2Freact-native%2FReactCommon%2Fcxxreact%2FJSCTracing.cpp&version=GBJSI&_a=contents

Please note that for Android platform, this is needed only for Systrace events from C++ code.
