### ISSUE TITLE
Right clicking on Button and other Touchable based components is triggering the action as if it were a left click

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#379]
### Issue

Touchable based components such as Button and List items can be triggered with a right click and behave as if they were left clicked.   In Debug builds, a right click will show the Dev menu *and* trigger the press.

### Steps to Reproduce

Open RNTester
Right click on an item in the example list
Right click on the Back button

### Expected Behavior

In Debug builds only the Dev menu should appear
In Release builds nothing should happen

### Actual Behavior

The Button and List items behave as if they were left clicked *and* the Dev menu appears.

**Comment by chrisglein** [comment]
FWIW, we had this issue in Windows as well: https://github.com/microsoft/react-native-windows/issues/4566
