### ISSUE TITLE
'Question: [How do I build standalone MacOS App]'

### ISSUE THREAD

**Issue by ShivamJoker** [microsoft/react-native-macos#400]
Hey please add the commands for bundling the macos app I am getting this error after I build the app and try to run it

```
No bundle URL present.

Make sure you're running a packager server or have included a .jsbundle file in your application bundle.

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
RunCurrentEventLoopInMode
ReceiveNextEventCommon
_BlockUntilNextEventMatchingListInModeWithFilter
_DPSNextEvent
-[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
-[NSApplication run]
NSApplicationMain
main
start
```

**Comment by tom-un** [comment]
Hi.   The react-native-macos fork is currently synced to react-native 0.61-stable.   Most things are parallel to how iOS bundling behaved in 0.61 **except** that the cli.js commands must be passed a `--use-react-native-macos` argument which enables a workaround in `react-native.config.js`.   This workaround is needed for "out-of-tree" platforms like macOS and Windows which are not part of core.   This workaround and the need for `--use-react-native-macos` will go away after this fork is merged with RN .62 (Issue #367).

The  `--use-react-native-macos` is used in the two Bash scripts that Xcode projects use: `scripts/react-native-xcode.sh` and `scripts/launchPackager.command`.   But if you have your own custom build steps or scripts that directly invoke the CLI, you have to pass  `--use-react-native-macos` yourself.

When building your App target the 'Bundle React Native code and images' custom build step invokes `../node_modules/react-native-macos/scripts/react-native-xcode.sh`.  The `react-native-xcode.sh` will create the static jsbundle and copy it into the App bundle, but *not* in Debug configs, only in Release configs.

When running your App target the 'Start Packager' custom build step invokes `scripts/launchPackager.command` if a packager is not already running.  Sometimes there is lag between the time it takes for the packager to start and the app booting.   I think this is what you are seeing.   When this happens, simply clicking Reload on the RedBox dialog or just restarting the app fixes it.   We don't behave any differently than iOS in .61 so my guess is that this was an issue upstream as well.  

Thanks!

**Comment by ShivamJoker** [comment]
Thanks for the help but still I am still not clear what will be the steps for building the .app file from xcode or command line

should I just archive the project in xcode and get the app ? for now it seems to be working

**Comment by tom-un** [comment]
From Xcode, to force the jsbundle to be put inside the .app during a Debug build, it would be the same as it is upstream for iOS: you can set the `FORCE_BUNDLING` var to make it always bundle regardless of config.

From the command line, the raw invocation of the CLI to create a jsbundle is:
`node node_modules/react-native-macos/local-cli/cli.js bundle --entry-file index.js --platform macos --bundle-output MyApp.jsbundle --use-react-native-macos`

When the fork has merged with .62 and we remove the workarounds, you'll be able to do the more natural:
`npx react-native bundle --entry-file index.js --platform macos --bundle-output MyApp.jsbundle`

**Comment by iamjaredwalters** [comment]
Im trying to understand this as well. Is there a step by step I can reference in order to build the standalone app I can distrubute?

**Comment by iamjaredwalters** [comment]
Fresh install seemed to solve my issues 🤷🏻
