### ISSUE TITLE
Question: How do I access the MacOS file system with react-native-macos/windows?

### ISSUE THREAD

**Issue by mruzekw** [microsoft/react-native-macos#406]

**Comment by Simek** [comment]
Hi @mruzekw, you should check out [Node File System API](https://nodejs.org/api/fs.html).

**Comment by tom-un** [comment]
react-native-macos is no different than iOS upstream in react-native regarding local file system access: in other words, there is no built-in JavaScript API for arbitrary file system access.   The nearest thing is the AsyncStorage API which is still in core but deprecated, or the react-native-community [AsyncStorage](https://github.com/react-native-community/async-storage/tree/master/src) which *does* have support for macOS as well Windows, iOS and Android.   For you're own app's specific needs, you could create your own Native Module that uses ObjC/C/C++ calls to access the file system.

**Comment by mruzekw** [comment]
@tom-un Thanks, Tom. I might actually undertake that. That’s really the only feature that’s missing for an app I’d like to build (at least that I can think of right now haha).

Is there a place I can submit community modules for react-native-macos/windows?

**Comment by tom-un** [comment]
Try the https://reactnative.directory/.   A search there shows some existing components for file file system access.   Mac and windows implementations could be contributed to an existing one.

**Comment by mruzekw** [comment]
Okay, thanks.

Looks like react-native-fs and expo-file-system are both worth contributing too.

I just didn't know if there was a specific place for react-native-macos/windows modules.

**Comment by tom-un** [comment]
In my opinion, the best react-native modules will have support for all platforms: ios, android, macos and windows 😀.   There are three RNC modules that already have support for all four platforms ([WebView](https://github.com/react-native-community/react-native-webview), [AsyncStorage](https://github.com/react-native-community/async-storage), [NetInfo](https://github.com/react-native-community/react-native-netinfo)) and more on the way.      Of course there are cases for platform specific modules, like a wrapper for a widget that is unique to a single platform.   But a file system module should be universal 👍.

**Comment by mruzekw** [comment]
Of course! Makes perfect sense. Thanks again!

**Comment by penx** [comment]
related: https://github.com/microsoft/react-native-windows/issues/2829
