### ISSUE TITLE
<ScrollView> needs implementations for onScrollBeginDrag/onScrollEndDrag, onMomentumScrollBegin/onMomentumScrollEnd

### ISSUE THREAD

**Issue by t4t5** [microsoft/react-native-macos#410]
Is it possible to detect when a user lets go of the trackpad in a `ScrollView`? (I believe this is what Cocoa calls `touchesEndedWithEvent`)

Seems like an important event to detect for more gesture-based apps, but I haven't found a way to make it work (`onScrollEnd` and `onMomentumScrollEnd` don't seem to fire)?

Thanks!

**Comment by tom-un** [comment]
Hi.   No, we never implemented those events in react-native-macos.   I think it would be relatively easy to implement by listening for `NSScrollViewDidLiveScrollNotification` in `RCTScrollView.m`.   We're accepting contributions if you would like to implement it.   Thanks!
