### ISSUE TITLE
ActivityIndicator causes brief flicker

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#412]
Reported by @Simek: 

> There is an issue with ActivityIndicator view Example, I assume it's related to the componentDidMount or timer there, for a brief moment just after click (after navigate), the app background became transparent and flickers (maybe it's resized to 0,0 for a ms?), most of other Examples seems to load fine.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30053638/82708589-79dccc80-9c33-11ea-8849-e97efd9e54f3.gif)

**Comment by tido64** [comment]
This is caused by the use of `CIFilter`s: https://github.com/microsoft/react-native-macos/blob/45d1df90e4e43f2b47259327cfb8192fb945644d/React/Views/RCTActivityIndicatorView.m#L92

Removing that one line resolves the issue. I'm currently trying to find an alternative implementation for `setColor:`.
