### ISSUE TITLE
<TouchableOpacity/> is calling onPress twice when invoked via keyboard

### ISSUE THREAD

**Issue by konvolution** [microsoft/react-native-macos#420]
### Steps to Reproduce

```
<TouchableOpacity onPress={ onPress }>
   <Text title="Press here!"/>
</TouchableOpacity>

onPress = () => {
  console.log('onPress called.');
}
```

1. TAB to `<TouchableOpacity/>`.
2. Press `[ENTER]` key.

### Expected Behavior

`onPress` gets called once.

### Actual Behavior

`onPress` gets called twice.

**Comment by tido64** [comment]
What version are you on? I couldn't repro this on 0.61.39:

![touchable-bug](https://user-images.githubusercontent.com/4123478/84371478-01d24880-abda-11ea-84c0-a07570c7da04.gif)

**Comment by iscontre** [comment]
@tido64 - I'm still seeing this in RN62 in one of our components. 

```
<TouchableOpacity onPress={ this._onPress }>
     { this.props.children }
</TouchableOpacity>

  private _onPress = (e: GestureResponderEvent) => {
    e.stopPropagation();
    this.props.onPress();
    console.log('Pressed');
  };
```

I get a single "Pressed" message in the console when doing it by mouse, and 2x when doing it via Keyboard/Enter keys.

**Comment by tom-un** [comment]
@HeyImChris : maybe there is an issue with our Office internal wrapper.  Can you verify that it does't repro in RNTester, then verify if it happens in PLYTestApp

**Comment by HeyImChris** [comment]
@tom-un yea we weren't able to repro this earlier this month, but have gotten more repro steps from another client. Either Amanda or I will take a look at this

**Comment by chiuam** [comment]
@tom-un @HeyImChris @tido64 

https://user-images.githubusercontent.com/67026167/107290781-20bcff00-6a35-11eb-9374-eeed946b5de6.mov

 I got a repro in RN63.

**Comment by chiuam** [comment]
This issue is fixed with https://github.com/microsoft/react-native-macos/pull/691.
