### ISSUE TITLE
<Image/> on Mac is not accessible unless accessible is false

### ISSUE THREAD

**Issue by konvolution** [microsoft/react-native-macos#428]
# Issue

If you have a react-native Image component and set accessible to true, it is not recognized a s a graphic to VoiceOver. However, if you set accessible to false, it becomes visible. This is the opposite of expected behavior.

<Image style={{width: 250, height: 250}} accessible={true} accessibilityLabel="This is an image" source={....}/>

### Expected Behavior

Navigate to image using VO+ArrowRight (next item), or VO+Command+G (next graphic).

### Actual Behavior

Image is skipped. On the other hand, if you change accessible to false, the image is visible to VoiceOver.

**Comment by tom-un** [comment]
Thanks.   I can repro the behavior.
