### ISSUE TITLE
OnSubmitEditing fires at wrong time on TextInput

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#429]
### Environment
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.21 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.volta/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

### Issue

When using TextInput field onSubmitEditing is being fired when pressing the backspace key

### Steps to Reproduce

1. Create the following component:

```javascript
<TextInput
        placeholder="+ Add Entry..."
        onSubmitEditing={() => console.warn('onSubmitEditing fired')}
        multiline
        numberOfLines={10}
/>
```

2. Start typing, when you press Cmd+Enter the onSubmitEditing function is called correctly
3. Now press Delete key
4. onSubmitEditing will also fire

### Expected Behavior

expected `onSubmitEditing` to only fire when pressing the Enter key

**Comment by okwast** [comment]
Hey, I also experience some issues with the TextInput.
When multiline is `false` it seems like `onSubmitEditing` is not called at all. At least I did not make it happen.
Neither with Enter nor CMD+Enter nor anything else.

With multiline enabled the TextInput seems to be completely broken.
It stops showing the input, but only shows the background and when typing there is some block spawning at the bottom of the window.
A bit hard to explain.

With empty input:
![Screen Shot 2020-06-02 at 15 57 40](https://user-images.githubusercontent.com/13070135/83528788-d10f5680-a4e9-11ea-8322-d14f85937ac6.png)

After typing `asdf`:
![Screen Shot 2020-06-02 at 15 57 44](https://user-images.githubusercontent.com/13070135/83528812-da002800-a4e9-11ea-87c8-fd8f200bb96d.png)

### System info:
System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 186.52 MB / 16.00 GB
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 14.1.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-28 | Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6392135
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_232 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by tom-un** [comment]
Probably related to Issue #432 
@tido64 FYI

**Comment by tido64** [comment]
@okwast Can you create a new issue for us? Thanks!
