### ISSUE TITLE
Question: Will Realm database work with RN for macOS

### ISSUE THREAD

**Issue by de1mat** [microsoft/react-native-macos#431]
In am investigating database options that will work with RN across different platforms. Will Realm with Cloud Sync work with RN on macOS and Windows?

**Comment by ospfranco** [comment]
https://github.com/realm/realm-js/issues/2907 I think is is an issue for the Realm repo and not the rn-macos repo, since each individual project needs to add support for different platforms

**Comment by tom-un** [comment]
Hi @de1mat.  This would be a feature request/contribution for the realm-js project.   Thanks @spfranco for opening the issue there.
