### ISSUE TITLE
Multiline textInput throws exception when loosing focus

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#432]
### Environment

npx react-native info
info Fetching system and libraries information...
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 1.89 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.volta/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found

### Issue
When using a multiline textInput, when it looses focus it causes a firstResponder resigned exception:

### Steps to Reproduce

1. Create a <TextInput multiline/>
2. Click on it, write something
3. Click outside (or loose focus somehow)
4. Exception will be thrown

### Expected Behavior

No exception thrown when using multiline

![Screenshot 2020-06-01 at 10 32 55](https://user-images.githubusercontent.com/1634213/83391126-464c3000-a3f3-11ea-973d-e798980560ae.JPG)

**Comment by tom-un** [comment]
Thanks for reporting.
@tido64 FYI.
