### ISSUE TITLE
Can existing React Native Android / iOS apps be built using react-native-macos? 

### ISSUE THREAD

**Issue by whenmoon** [microsoft/react-native-macos#436]
This project looks really exciting - the first thing that came in to my mind when I discovered it is "can I bring my existing React Native Android app over to OS X?".

I can't really seem to find any information on if that can be done or how that would work. Does every package that is written to support Android and iOS have to be updated to support react-native-macos?

Thanks.

**Comment by tom-un** [comment]
Hi @whenmoon.  The short answer is "yes".   Upstream react-native is a mobile cross platform framework: it is possible to write a single app that runs on iOS and Android.   Most props and components upstream are cross platform, but there are exceptions: some props and components are iOS specific and some are Android specific.   react-native-macos and react-native-windows align to the same philosophy: wherever possible props and components are cross platform but there are some props that are Desktop specific (like mouse and keyboard focus events) and some that are macOS or Windows specific.

So, a react-native app that was written specifically for Android may just work on react-native-macos or react-native-windows, but if the app uses any Android specific props or components, then you would have to manually add affordances for macOS or Windows just as you would have to manually add affordances if you were trying to run on iOS.
