### ISSUE TITLE
New app build fails

### ISSUE THREAD

**Issue by fitzmode** [microsoft/react-native-macos#440]
### Environment

1. `react-native -v`: 4.10.0
3. `npm ls react-native-macos`: react-native-macos@0.61.39
4. `node -v`: v12.16.2
5. `npm -v`: 6.14.4
6. `yarn --version`:
7. `xcodebuild -version`: Xcode 11.3.1 Build version 11C505

### Steps to Reproduce

Create a new project via `npx`.

1. `$ npx react-native init foo --version 0.61.5`

2. `$  cd foo`

3. `$ cd macos && pod install && cd ..`

4. `$ npx react-native run-macos`

### Expected Behavior

Expected application to run .

### Actual Behavior
T

Build fails  with below output. One thing of note is the path in the error points to an incorrect path with `...Pods/Pods/...

`

```
info Found Xcode workspace "spawn.xcworkspace"
info Building (using "xcodebuild -workspace spawn.xcworkspace -configuration Debug -scheme spawn-macOS")
.......
error Failed to build macOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening spawn.xcworkspace. Run CLI with --verbose flag for more details.
note: Using new build system
note: Planning build
note: Using build description from disk
error: /Users/fitzmode/spawn/macos/Pods/Pods/Target Support Files/Pods-Shared-spawn-macOS/Pods-Shared-spawn-macOS.debug.xcconfig: unable to open file (in target "spawn-macOS" in project "spawn") (in target 'spawn-macOS' from project 'spawn')
error: /Users/fitzmode/spawn/macos/Pods/Pods/Target Support Files/Pods-Shared-spawn-macOS/Pods-Shared-spawn-macOS.debug.xcconfig: unable to open file (in target "spawn-macOS" in project "spawn") (in target 'spawn-macOS' from project 'spawn')
error: /Users/fitzmode/spawn/macos/Pods/Pods/Target Support Files/Pods-Shared-spawn-macOS/Pods-Shared-spawn-macOS.debug.xcconfig: unable to open file (in target "spawn-macOS" in project "spawn") (in target 'spawn-macOS' from project 'spawn')


** BUILD FAILED **
```
Running through `XCode` returns the same error.

<img width="1279" alt="Screenshot at Jun 08 23-54-55" src="https://user-images.githubusercontent.com/17691094/84084323-84dd7e00-a9e3-11ea-9b84-c178005afd34.png">

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

### Additional context

(Write any other additional context that may help in root causing the issue.)

**Comment by tom-un** [comment]
Hi @fitzmode ,
I was not able to reproduce the issue.   In your repro steps there is no `npx react-native-macos-init` call, but I assume you just accidentally omitted that step in your report.   If I do:
1. `$ npx react-native init foo --version 0.61.5`
2. `$ cd foo`
3. `$ npx react-native-macos-init`
4. `$ cd macos && pod install && cd ..`
5. `$ npx react-native run-macos`
It succeeds and the 'foo' app launches.   Also, note step 4 is not actually necessary anymore as react-native-macos-init now does the pod install automatically.

**Comment by leotm** [comment]
Similar here (https://microsoft.github.io/react-native-windows/docs/rnm-getting-started)

`node -v`: v16.2.0
`npm -v`: 7.13.0
`yarn -v`: 1.22.4
`xcodebuild -version`: Xcode 12.4 Build version 12D4e
`macOS`: Big Sure v11.4, MacBook Pro (15-inch, 2018)

`npx react-native init foo --template react-native@^0.63.0`

<img width="1600" alt="Screenshot 2021-05-31 at 13 25 31" src="https://user-images.githubusercontent.com/1881059/120192981-c4643200-c213-11eb-9039-f58d86d0281b.png">

`npx react-native-macos-init`

<img width="1638" alt="Screenshot 2021-05-31 at 13 18 12" src="https://user-images.githubusercontent.com/1881059/120193262-1a38da00-c214-11eb-8f23-97676deb804d.png">

`pod install`

<img width="1561" alt="Screenshot 2021-05-31 at 13 21 24" src="https://user-images.githubusercontent.com/1881059/120192495-22dce080-c213-11eb-8bc8-0e77c0f238c8.png">

`npx react-native run-macos`

<img width="1651" alt="Screenshot 2021-05-31 at 13 22 32" src="https://user-images.githubusercontent.com/1881059/120192595-4869ea00-c213-11eb-845c-57883df9a159.png">
