### ISSUE TITLE
enableClearButton prop is not applied to TextInput

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#448]
### Issue
On iOS the `enableClearButton` prop on TextInput shows an ⓧ.   On macOS it is not implemented.

This will not be entirely trivial to implement on macOS.   The NSTextField has no built-in support for icons on the left or right.   There is the NSSearchField
<img width="462" alt="Screen Shot 2020-06-11 at 3 22 22 PM" src="https://user-images.githubusercontent.com/30053638/84444814-72d42900-abf7-11ea-91ca-46475b0e9734.png">
but it has no affordance to modify the left icon.

To get a cancel button in the RCTUITextField (the NSTextField subclass for single line TextInput) we would have to make an implementation similar to NSSearchField and add sub NSCell's to be the clear button.   At the same time, we could add a new macOS specific prop to add a left-hand image also using an NSCell.

### Steps to Reproduce

In RNTester go to the TextInput Example "Clear button mode" example.

iOS:
<img width="559" alt="Screen Shot 2020-06-11 at 3 19 22 PM" src="https://user-images.githubusercontent.com/30053638/84444577-f7727780-abf6-11ea-8dbb-b41e0dbb8464.png">

macOS:
<img width="774" alt="Screen Shot 2020-06-11 at 3 20 45 PM" src="https://user-images.githubusercontent.com/30053638/84444668-24bf2580-abf7-11ea-9897-3b1307bf45ab.png">

**Comment by Simek** [comment]
Hmm, it looks like this "somewhat" works for me in `0.64` release using iOS [`clearButtonMode `](https://reactnative.dev/docs/textinput#clearbuttonmode-ios). 

The "X" appears but not on every interaction it clears the input. It also appear to be quite slow process:

![Kapture 2021-12-13 at 23 08 18](https://user-images.githubusercontent.com/719641/145896910-88a55986-ee30-4c1e-bb96-7a5eac1037a9.gif)
