### ISSUE TITLE
Single line TextInput onSubmitEditing doesn't work

### ISSUE THREAD

**Issue by byw** [microsoft/react-native-macos#451]
### Environment

1. `react-native -v`: 0.62.13
3. `npm ls react-native-macos`: 0.61.0-0
4. `node -v`: 12.18.0
5. `npm -v`: 6.14.4
6. `yarn --version`: 1.22.4
7. `xcodebuild -version`: 11E608c

### Issue

`TextInput` in single-line mode doesn't trigger `onSubmitEditing` event when I press enter.

### Steps to Reproduce

1. Hookup `onSubmitEnter` to a callback. 
2. `console.log` a debug line in callback.
3. Type something, press enter

### Expected Behavior

The callback should be called, producing console output.

### Actual Behavior

The callback is not called - no message printed to console. 
It does work, however, in multiline when I hit Cmd-Enter.

**Comment by tom-un** [comment]
Thanks.   I think this was resolved in a PR for another issue. @tido64 : can you confirm?

**Comment by tido64** [comment]
Only `onSubmitEditing` in multi-line `TextInput` was fixed (#442). I can take a look at this one next.
