### ISSUE TITLE
Revisit workaround for window resizing events overloading the shadow queue

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-macos#459]
In order to fix #322 and #422, we've added throttling of layout events (#439) to reduce load on the shadow queue. Post-Fabric, we should revisit this workaround and see if we can implement a proper fix.

**Comment by tido64** [comment]
cc @tom-un

**Comment by Saadnajmi** [comment]
I would like to keep this open.

**Comment by christophpurrer** [comment]
Can this one be closed now since #1318 landed?
