### ISSUE TITLE
Question: How to add macOS support to existing React Native plugins?

### ISSUE THREAD

**Issue by hassankhan** [microsoft/react-native-macos#467]
Hi there,

I was wondering if there was a guide for adding support to existing React Native projects that already have iOS support?

**Comment by tom-un** [comment]
Hi @hassankhan : no, there isn't one that I know of, but that's a great idea for us to add one.   In the meantime you could look at three react-native-community repo's that have macOS implementations:

- [WebView](https://github.com/react-native-community/react-native-webview)
- [AsyncStorage](https://github.com/react-native-community/async-storage)
- [NetInfo](https://github.com/react-native-community/react-native-netinfo)

**Comment by hassankhan** [comment]
Thanks for the reply, and for sharing those repositories, @tom-un!

I was wondering if there were any explicit guidelines specifically around generating a macOS Xcode project for an existing RN plugin? Should I just create a new project via Xcode with the same name as the iOS project (for example), or is there some other programmatic way of doing this?

**Comment by hassankhan** [comment]
I've created an issue on [`bob`](https://github.com/react-native-community/bob) https://github.com/react-native-community/bob/issues/70.
