### ISSUE TITLE
Flaky CI tests should pass consistently

### ISSUE THREAD

**Issue by graytmatterMS** [microsoft/react-native-macos#471]
Several CI tests are regularly failing on PRs. They should be fixed so good PR's aren't left hanging.

[ ] RNTesterLoadAllPages:JSResponderHandlerExample
ex: https://dev.azure.com/ms/react-native/_build/results?buildId=89666&view=logs&j=628dfcdf-afa5-5702-e4da-dfa310a93062&t=65c699ef-104f-5f6e-4efa-350cb1662389
[ ] RNTesterLoadAllPages: ScrollViewExample

**Comment by chrisglein** [comment]
Totally believe you on that. The run results you linked have timed out (sorry it took awhile to get to this issue). We need to figure out which tests are being flakey (is it always these 2 or is it all tests?) and take the right action, so new reports are valuable. If you hit this again please open an issue. Currently unactionable without the logs :(
