### ISSUE TITLE
onSubmitEditing on multiline textinput broken on 0.61.51

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#472]
### Environment

System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 8.09 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.0 - ~/.volta/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom, android-R | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_212 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
### Issue

I just updated my react-native-macos installation to 0.61.51 and it seems there is a regression, `onSubmitEditing` on a multiline textinput (via Cmd+Enter) is not working any more.

### steps
1. Create a multiline input and add a onSubmitEditing callback
2. Type a few characters and then press Cmd + Enter
3. onSubmitEditing callback should fire, but it is not

**Comment by tom-un** [comment]
@tido64 fyi

**Comment by tido64** [comment]
This worked briefly by mistake between 0.61.45 and 0.61.49. As of 0.61.49, multiline `TextInput` behaviour matches that of upstream, as documented under [`TextInput.blurOnSubmit`](https://reactnative.dev/docs/textinput#bluronsubmit):

_Note that for multiline fields, setting `blurOnSubmit` to `true` means that pressing return will blur the field and trigger the `onSubmitEditing` event instead of inserting a newline into the field._

Nowhere does it mention that Cmd+Enter will trigger `onSubmitEditing`. As far as I am aware, @tom-un correct me if I'm mistaken, our policy is to match upstream behaviour, and not deviate from it. My recommendation is to file this bug upstream, i.e. `react-native`. A change there will trickle down to `react-native-macos`.

**Comment by ospfranco** [comment]
ok, so it might have been unintended behavior, but let me describe my use case and you might provide some indications on how should one proceed when using react-native on macos.

I'm building a note taking app, and I have a multiline text input, now if I set `blurOnSubmit` and `onSubmitEditing` when I press the `return` key then onSubmitEditing is triggered, which is fine, but how can I then insert new line breaks? there is no way to detect when the `Shift + return` combination has been pressed right?

**Comment by tom-un** [comment]
Hi @ospfranco:  Could you use `ctrl + return` in your app to insert lines?   That key combination succeeds in inserting a new line into a multiline TextInput.

Our implementation uses the `NSTextViewDelegate` protocols `textView:doCommandBySelector:` method to detect these return key events.   At this level `return` and `shift + return` actually send the same selector: `insertNewLine:`.   The `ctrl + return` combo sends `insertLineBreak:` and we don't fire the `onSubmitEditing` for that event, but do fire the `onChange` event.

For the record, these are the selectors sent for all the combinations:
| key combo | `textView:doCommandBySelect:` |
|:------------|:-----------------------------------|
| `return` | `insertNewline:` |
| `shift + return` | `insertNewline:` |
| `alt + return` | `insertNewlineIgnoringFieldEditor:` |
| `ctrl + return` | `insertLineBreak:` |
| `cmd + return` | `noop:` |

**Comment by ospfranco** [comment]
thanks @tom-un, I could... but I don't think that is the correct solution, a lot of apps use the shift + return to insert line breaks, even though ctrl + return does achieve what I need the UX is subverted...

anyways, I have implemented my own key press listener using https://github.com/soffes/HotKey but as we had this discussion before, I still think react-native needs to be adapted to desktop environments in order for it be really used in production apps

Feel free to close this issue if you see fit though

**Comment by tom-un** [comment]
Ok.  Well, glad you have a workaround.   As @tido64 said above, we don't want to deviate from the behavior upstream.   In this case, the upstream `onSubmitEditing` does not set the `key` field in its dictionary.   It *could* though.  If you made such a PR upstream we'd do the reciprocal in macos.

In iOS, the event is fired via:
```
#0 -[RCTBaseTextInputView textInputShouldReturn] 
#1 -[RCTBackedTextViewDelegateAdapter textView:shouldChangeTextInRange:replacementText:] 
...
```
The `textInputShouldReturn` could be modified to take a string argument that is passed the `replacementText:` string, and that could be passed to the `key:` argument in the call to `[_eventDispatcher sendTextEventWithType:RCTTextEventTypeSubmit ... key:]`. 

On macOS, the event is fired via:
```
#0 -[RCTBaseTextInputView textInputShouldReturn]
#1 -[RCTBackedTextViewDelegateAdapter textView:doCommandBySelector:] 
...
```
In the macOS implementation, we could get the key via `[NSApp currentEvent]` and pass it to the `textInputShouldReturn` if it were refactored upstream to take a string argument.

**Comment by ospfranco** [comment]
I'm sorry but my objc-fu is simply not good enough, I don't think I will be the one that creates such a PR, I will close this issue for now since the behavior is working as intended
