### ISSUE TITLE
BorderRadius and overflow: hidden not working

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#478]
### Environment
"react-native-macos": "0.61.46",

### Issue

Trying to set `borderRadius` on an `Image` does not work, neither does setting the `borderRadius` on a parent container and setting `overflow` to `hidden`

**Comment by TheSavior** [comment]
This may have gotten fixed in one of the recent PRs: https://github.com/microsoft/react-native-macos/pull/457

**Comment by ospfranco** [comment]
Yep, seems to be fixed on the latest version
