### ISSUE TITLE
Question: How to link fonts?

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#482]
It's seems like modifying the `react-native.config.js` and doing `react-native link` does not link fonts to the project, how would one go about doing this?

**Comment by tom-un** [comment]
Hi @aspfranco.  the `react-native link` command does not yet support macos.    It is tracked by https://github.com/microsoft/react-native-macos/issues/465.   However, for font linking, the same manual font linking steps documented elsewhere for iOS apps should apply to macOS targets.

**Comment by ospfranco** [comment]
ah, well, I'm in a bit a problem then... I followed the instructions on [react native vector icons](https://github.com/oblador/react-native-vector-icons#osx-via-react-native-desktop), which means I can only have a single (referenced) font folder... not a rn problem though, thanks though

**Comment by OKNoah** [comment]
@ospfranco Share code?

**Comment by ospfranco** [comment]
no code to share, just follow the instructions on the react native vector icons repo, they work just fine

**Comment by OKNoah** [comment]
> no code to share, just follow the instructions on the react native vector icons repo, they work just fine

All I'm asking is that you share your code so that I can compare it with my own and diagnose the problem on my own. I had a fear the React community would become unfriendly at the most important time. Tell me I'm wrong.

**Comment by ospfranco** [comment]
Jesus... the entitlement of the open source community, news flash mate, I'm no obligation to help you, yet I'm gonna point it to you one last time, THERE IS NO CODE JUST LINK THE FONTS

<img width="870" alt="Screenshot 2020-12-14 at 07 55 11" src="https://user-images.githubusercontent.com/1634213/102049724-b8112780-3de1-11eb-982a-a58bc77e2e17.png">

**Comment by shayneoneill** [comment]
Hmm. That doesn't seem to work properly. It now finds the material fonts but complains about san serif and the like. Theres gotta be a more deterministic way to get this working :/

**Comment by tejasjoshiagile** [comment]
create Resources folder in your macOS xcode project drop all fonts file in it 
add key in info.pllist 

```
<key>ATSApplicationFontsPath</key>
	<dict>
		<key>item 0</key>
		<string>Ubuntu-Bold.ttf</string>
	</dict>
```

and all set work..

**Comment by devAdrish** [comment]
> create Resources folder in your macOS xcode project drop all fonts file in it add key in info.pllist
> 
> ```
> <key>ATSApplicationFontsPath</key>
> 	<dict>
> 		<key>item 0</key>
> 		<string>Ubuntu-Bold.ttf</string>
> 	</dict>
> ```
> 
> and all set work..

The standard and recommended method is to use UIAppFonts, which is specifically designed to handle custom fonts in iOS and macOS applications.

<key>UIAppFonts</key>
<array>
    <string>YourFontName.ttf</string>
    <string>AnotherFontName.otf</string>
</array>

XCODE way:

1. from the left panel (navigator) select yourapp-macos, 
2. create a new folder by right click > new group
3. add files to your project (appname)
4. select all font files (make sure they are located somewhere inside the react native project e.g. src/assets/fonts/...)
5. then add to info.plist as above

**Comment by Saadnajmi** [comment]
@devAdrish Thanks! I didn't know about UIAppFonts. @tido64 potentially an update to react-native-test-app ?

**Comment by tido64** [comment]
> @devAdrish Thanks! I didn't know about UIAppFonts. @tido64 potentially an update to react-native-test-app ?

https://github.com/microsoft/react-native-test-app/wiki/Assets#fonts
