### ISSUE TITLE
Disable focus ring

### ISSUE THREAD

**Issue by salbatore** [microsoft/react-native-macos#483]
A great job with this repository!

How to remove focus ring from a TextInput ?.

<img width="450" alt="Captura de pantalla 2020-07-04 a las 20 53 01" src="https://user-images.githubusercontent.com/46431183/86519153-5e6eff00-be38-11ea-86a2-2079ed671cc0.png">

**Comment by tom-un** [comment]
Hi.  You can use `enableFocusRing={false}` to hide the focus ring.

**Comment by salbatore** [comment]
Thanks @tom-un
