### ISSUE TITLE
'Question: How to make Audio playback work?'

### ISSUE THREAD

**Issue by federicocandiago** [microsoft/react-native-macos#484]
Good afternoon,

I'm currently using RN 0.61 and Xcode 11.5, and I've been trying to port an existing RN app to mac OS, but I struggle to make sound playback work.
I've tried using YBRAIN/react-native-audio-toolkit, react-native-play-audio-ios, zmxv/react-native-sound (both manual and automatic linking land me to the famous 'RNSound.IsAndroid' error) and dooboolab/react-native-audio-recorder-player (null is not an object (evaluating 'RNAudioRecorderPlayer.startPlayer')), but couldn't get anyone to work.

Has anybody been more successful in implementing audio playback on a microsoft/react-native-macos application?

Thanks

**Comment by tom-un** [comment]
Hi @federicocandiago : all the repo's you listed above have only ios and android implementations.   Someone would have to contribute a macOS implementation to one of those existing projects, or make a new macOS specific project.   Generally, its fairly easy to port an existing iOS react-native implementing to macOS, but I don't know if that would be the cause for audio playback -- not an expert in that area.

**Comment by federicocandiago** [comment]
Thank you Tom! Unfortunately I don't have the technical competences to contribute in a working audio native library, so I'll just wait for any developments from the community authors.

**Comment by HaddyYang** [comment]
My current implementation method is through webview (react-native-webview)

**Comment by aniketgupta8960** [comment]
Any update on this ?

**Comment by WINTERANDREA** [comment]
Any update on this??? Thank you

**Comment by aniketgupta8960** [comment]
replace this -  s.platform   = :ios, "7.0" with s.platforms           = { :ios => "10.0", :tvos => "12.0", :osx => "10.10" } in RNSound.podspec and also replace  [[NSBundle mainBundle] bundlePath] with [[NSBundle mainBundle] resourcePath] in RNSound.m and then create a patch and it will work

**Comment by Saadnajmi** [comment]
> replace this -  s.platform   = :ios, "7.0" with s.platforms           = { :ios => "10.0", :tvos => "12.0", :osx => "10.10" } in RNSound.podspec and also replace  [[NSBundle mainBundle] bundlePath] with [[NSBundle mainBundle] resourcePath] in RNSound.m and then create a patch and it will work

Any chance you can make a PR for this to the community module? :) 

You can use a preprocessor macro for the line you have to replace to have it compile for both platforms iOS and macOS:
```
#if !TARGET_OS_OSX 
[[NSBundle mainBundle] bundlePath]
#else
[[NSBundle mainBundle] resourcePath]
#endif

Unless of course, the former works on both...

**Comment by aniketgupta8960** [comment]
> > replace this -  s.platform   = :ios, "7.0" with s.platforms           = { :ios => "10.0", :tvos => "12.0", :osx => "10.10" } in RNSound.podspec and also replace  [[NSBundle mainBundle] bundlePath] with [[NSBundle mainBundle] resourcePath] in RNSound.m and then create a patch and it will work
> 
> Any chance you can make a PR for this to the community module? :)
> 
> You can use a preprocessor macro for the line you have to replace to have it compile for both platforms iOS and macOS:
> 
> ```
> #if !TARGET_OS_OSX 
> [[NSBundle mainBundle] bundlePath]
> #else
> [[NSBundle mainBundle] resourcePath]
> #endif
> ```
> 
> Unless of course, the former works on both...

Yes This will be better if you like to support both environments (ios and macOS)
