### ISSUE TITLE
Multiline TextInput crashes after buffer has a certain number of characters and they are deleted

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#486]
### Environment

"react-native-macos": "^0.61.54"

### Steps to Reproduce
 on a `<TextInput multiline />` try to write several characters (number seems to ~100 - ~300) after you have enough characters in the buffer, try to delete a few of them, react-native will crash:

![Screenshot 2020-06-30 at 19 16 36](https://user-images.githubusercontent.com/1634213/86156607-83950200-bb06-11ea-87b8-4c933e45a1a7.JPG)

![Screenshot 2020-07-06 at 16 19 58](https://user-images.githubusercontent.com/1634213/86603720-aa3eb700-bfa4-11ea-9690-349a59836115.JPG)

The problem was happening a lot more often with an older version, now it doesn't happen as often, but still occurs every once in a while, it might take a lot of typing/deleting to reproduce the problem

**Comment by tido64** [comment]
@ospfranco: Do you have the opportunity to try out my branch? I think I've addressed it but it's hard to repro this bug to begin with so I'm not 100%.

**Comment by ospfranco** [comment]
awesome! I'm at work right now, I'll try to make some room tonight, thanks for the fix!
