### ISSUE TITLE
'Question: Is react-native-macos compatible with react-native-navigation or is there smth else to use instead for navigation?'

### ISSUE THREAD

**Issue by 0xmtn** [microsoft/react-native-macos#488]
I'm using react-native-macos for a while now and the core of the application is finished. I'd like to add login/register screens with externally managed payment options. For this I'm thinking of using react-native-navigation, yet I couldn't get it working with react-native-macos. 

Is it compatible or is there something else to use instead? How to create a 3 page app with simple transitions with react-native-macos?

**Comment by tido64** [comment]
Can you please provide more information? What do you mean by "I couldn't get it working"? Were there errors? Did the animations just not work? It would also be nice if you could provide information on your environment, e.g. which version of react-native-macos you were using and so on.

**Comment by 0xmtn** [comment]
You're absolutely right @tido64 , my bad. I thought maybe react-native-navigation is not suitable for this task at all and there is smth else to use instead, that's why I didn't show what I've tried. Not right, thanks for pointing it out.

So, here is what I did based on the [rnn documentation](https://wix.github.io/react-native-navigation/docs/installing/). 

First, `npx rnn-link` returns these:

```
Running Android postlink script.

Linking MainApplication...
   MainApplication already extends NavigationApplication, skipping.
   NavigationReactNativeHost is already used, skipping.
   SOLoader.init() is not called, skipping.
MainApplication.java linked successfully!

Linking MainActivity...
   MainActivity already extends NavigationActivity
   getMainComponentName function was not found.
MainActivity linked successfully!

Linking root build.gradle...
   Kotlin version already specified
   Kotlin plugin already declared
   Already specified minSdkVersion 19
Root build.gradle linked successfully!

Running iOS postlink script.

Linking AppDelegate...
   Removing Unneeded imports
   No imports could be removed. Check the manual installation docs to verify that everything is properly setup:
   https://wix.github.io/react-native-navigation/docs/installing#native-installation
   AppDelegate already imports ReactNativeNavigation.h
   Navigation Bootstrap already present.
   Removing Application launch content
   No elements could be removed. Check the manual installation docs to verify that everything is properly setup:
   https://wix.github.io/react-native-navigation/docs/installing#native-installation
AppDelegate linked successfully!

Updating Podfile...
   RNN Pod has not been added to Podfile

React Native Navigation link is completed. Check the logs above for more information.

   If any of the steps failed, check the installation docs and go through the necessary steps manually:
   https://wix.github.io/react-native-navigation/docs/installing#manual-installation

When you're done, don't forget to update the index.js file as mentioned in docs!

Thank you for using React Native Navigation!
```

Then, I changed my `index.js`  into:

```
import { Navigation } from "react-native-navigation"; 
//import {AppRegistry} from 'react-native';
import App from './src/App';   
//import {name as appName} from './app.json';


Navigation.registerComponent('com.myApp.HomeScreen', () => App);
Navigation.events().registerAppLaunchedListener(() => {
   Navigation.setRoot({
     root: {
       stack: {
         children: [           
           {
             component: {      
               name: 'com.myApp.HomeScreen'    
             }
           }
         ]
       }
     }
  });
});

//AppRegistry.registerComponent(appName, () => App);    
```
Then I ran the application as per the documentation, at this point the app should run gracefully. 

The error I'm getting when running the app:

![image](https://user-images.githubusercontent.com/732147/87002183-bbb0da80-c1c1-11ea-8070-c42fcece0b1d.png)

**Comment by tido64** [comment]
@0xmtn: How did you get past the `pod install` step? I got this error:

```
% pod install --project-directory=macos
Detected React Native module pods for ReactNativeNavigation and ReactTestApp-DevSupport
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native-macos/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native-macos/third-party-podspecs/Folly.podspec`
Fetching podspec for `boost-for-react-native` from `../node_modules/react-native-macos/third-party-podspecs/boost-for-react-native.podspec`
Fetching podspec for `glog` from `../node_modules/react-native-macos/third-party-podspecs/glog.podspec`
[!] The platform of the target `ReactTestApp` (macOS 10.14) is not compatible with `ReactNativeNavigation (6.9.0)`, which does not support `macOS`.
```

The error message indicates that `react-native-navigation` doesn't support macOS. You could [open an issue](https://github.com/wix/react-native-navigation/issues/new) in their repo to see if they have any plans for macOS.

Otherwise, have you looked into [React Navigation](https://reactnavigation.org/)? I don't know if it works with `react-native-macos` but it could be worth trying it out.

**Comment by 0xmtn** [comment]
It is the same for `@react-navigation/native`. Apparently, none of its dependencies support macOS.

Also, some dependencies, such as stackview, is interdependent on masked-view and safe-area-context, which don't support macOS.

I wonder what is the officially supported navigator for react-native-macos. How to proceed from here?

**Comment by tido64** [comment]
Sorry, this is the sort of question that you'll get better answers from on StackOverflow or some other forum. I'm not aware of any officially supported navigator for react-native-macos. You _could_ try asking the folks on `react-native-navigation` or `react-navigation` to see if they have any plans for macOS.

**Comment by ospfranco** [comment]
You won't be able to run the latest versions of react-navigation because as you figured it out, natively it is not supported on macOS, you can use however an older version that depends on javascript only, I have the latest version of the 2.X.X branch working... it is no longer updated, but it works until navigation adds support for macOS

**Comment by armandodlvr** [comment]
what should I use if I need to create a Left Navigation?

**Comment by ospfranco** [comment]
what is a left navigation? you mean a drawer navigator? if it's not on the 2.X.X branch of react-navigation you will have to do your own custom implementation, shouldn't be too hard, just put it on the root of your app and bind it to some sort of state handler.

**Comment by armandodlvr** [comment]
Left Navigation example

<img width="1680" alt="Screen Shot 2020-08-01 at 14 02 22" src="https://user-images.githubusercontent.com/8527538/89110479-c85ed200-d3ff-11ea-82d8-f4d1bacbb48d.png">

**Comment by tido64** [comment]
FYI, `@react-navigation/stack` just got macOS support: [@react-navigation/stack@5.9.0](https://github.com/react-navigation/react-navigation/releases/tag/%40react-navigation%2Fstack%405.9.0)

**Comment by tangten** [comment]
hi @tido64, have you tested that? because I'm using @react-navigation/stack@5.14.5, it can work with macOS but there is no animation when changing screen :(

**Comment by ospfranco** [comment]
**react-navigation/stack** works, the fact there is no animation is a different issue (it is because react-native-screens does not support macOS)

**Comment by tangten** [comment]
thanks @ospfranco, that's a sad news :(
