### ISSUE TITLE
Question: Control Window Aspect Ratio?

### ISSUE THREAD

**Issue by kevinvangelder** [microsoft/react-native-macos#490]
Is there a supported way to control/lock the window aspect ratio? It's probably not a high-priority feature, but it will be important for some apps to have this ability. Maybe allowing the developer to set the initial window size would be an easier first step?

**Comment by tom-un** [comment]
Hi.  react-native-macos, like react-native for iOS, starts at the RCTRootView (a UIView subclass), and has no real knowledge or opinions about the native app or window that is hosting it.    If you started your app via `react-native-macos-init`, then you will have a native ViewController, AppDelegate and Storyboard that sets up and hosts the RCTRootView.   You can modify the initial window size at that level.   The easiest way to achieve that would be to change the width and height in the Storyboard.    If you want more customization, you can modify the ViewManager in any way you want.

**Comment by kevinvangelder** [comment]
D'oh! I should have realized that!
