### ISSUE TITLE
Question: Create a spotlight-like window

### ISSUE THREAD

**Issue by jet8a** [microsoft/react-native-macos#491]
<img width="769" alt="image" src="https://user-images.githubusercontent.com/14956407/85175802-92fb8c00-b278-11ea-91ed-2e0c23297d35.png">

How can I create a window which is displaying a spotlight-like popup after global keyboard shortcut.

**Comment by tom-un** [comment]
react-native-macos has no built-in facility to do this.   It manages the rendering and interactions within its RCTRootView.   To make an experience like this, you would need a new top level NSWindow to host the RCTRootView.   It's certainly possible, but it would require writing a Native Module to support it.

**Comment by hassankhan** [comment]
Hi @tom-un, does this also mean that `react-native-macos` will not have any built-in support for opening multiple windows, for example?

**Comment by alexindigo** [comment]
Thanks for the details @tom-un, how about rendering in the background? There are apps like [Plash](https://github.com/sindresorhus/Plash) that render into the desktop background, is it possible to do something like this with RN MacOS? Thank you.

**Comment by tom-un** [comment]
@hassankhan : there are no plans to add build-in NSWindow support to react-native-macos.   Its scope is similar to react-native for iOS: the react-native JavaScript experience begins at the RCTRootView level (a UIView or NSView subclass).   React-native for ios and macos are not opinionated about the native app, window and view hierarchy the RCTRootView is hosted in.

@alexindigo : I don't know anything about Plash, but as I described above, the RCTRootView is just an NSView and as such can be hosted in just about any NSWindow/NSView hierarchy.   You can control the RCTRootView's background to make it use use any effect supported by the system.   Further, you can assign system colors to any color prop in the react-native View hierarchy using the `{ semanticColor: 'systemColorName' }` syntax (when we sync up to RN .63 we will align with the `PlatformColor()` syntax https://reactnative.dev/docs/platformcolor).

**Comment by ospfranco** [comment]
https://github.com/ospfranco/sol
