### ISSUE TITLE
Question: No bundle URL present

### ISSUE THREAD

**Issue by callaars** [microsoft/react-native-macos#493]
I've followed the documentation to set up a new RN MacOs project but when it comes to the first time running `npx react-native run-macos` it just throws a "No bundle URL present". 

I'm not sure if I should've done something else but currently, I'm stumped.

Is there any advice on this? This is a snippet of my `package.json`:

```
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-macos": "^0.61.0-0"
  },
```

**Comment by callaars** [comment]
For some reason restarting my computer worked. Sorry for the question.

**Comment by Zorgatone** [comment]
I rebooted and still have the same issue...

info Fetching system and libraries information...
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 4.78 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    Yarn: Not Found
    npm: 6.14.9 - ~/.nvm/versions/node/v15.3.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.0 - /Users/tommaso/.rvm/gems/ruby-2.7.2/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.2, DriverKit 20.0, macOS 11.0, tvOS 14.2, watchOS 7.1
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 30.0.0, 30.0.2
      System Images: android-29 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64, android-30 | Google Play Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1.1 4.1.1
    Xcode: 12.2/12B45b - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_231 - /usr/bin/javac
    Python: 2.7.18 - /Users/tommaso/.pyenv/shims/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.3 => 0.63.3
    react-native-macos: ^0.63.1 => 0.63.1
