### ISSUE TITLE
'Question: [Whats the recommended way to play videos?]'

### ISSUE THREAD

**Issue by justmelnyc** [microsoft/react-native-macos#494]
can I use iOS/Android RN components like [](https://github.com/react-native-community/react-native-video )

**Comment by kevinvangelder** [comment]
You would need to implement React Native Video (or some comparable library) for macOS. I did this for Windows back in the day. It isn't too difficult as long as you can find comparable native APIs to use.

**Comment by justmelnyc** [comment]
> You would need to implement React Native Video (or some comparable library) for macOS. I did this for Windows back in the day. It isn't too difficult as long as you can find comparable native APIs to use. 

I tried using react Native video, and got undefined constant. So I would have to write the native code as well? 

Also I would want this to be cross platform, so I would do this in windows as well?

**Comment by kevinvangelder** [comment]
The vast majority of React Native projects that use native code will not support macOS, so yes, you would need to write the native code yourself or wait until someone else does it. You can usually tell which platforms are supported by the native folders in the root of the project. [React Native Video](https://github.com/react-native-community/react-native-video), for example, has iOS, android, and windows folders, so those are the supported platforms (although, if a package has no native platform folders it probably is a javascript-only package and may work on any platform).

**Comment by hassankhan** [comment]
I feel like if the process for adding macOS support is a bit more clearly documented (as per #467), it would give developers a good starting point. 

In React Native Video's case specifically, I believe the underlying [`AVFoundation`](https://developer.apple.com/av-foundation/) classes are the same for both iOS and macOS, so it may be possible to simply enable macOS as a valid build target.
