### ISSUE TITLE
Question: is pinch gesture on scrollview going to be supported?

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#495]
I have a canvas like container that I would like make zoomable via trackpad gestures:

![Screenshot 2020-07-10 at 20 40 23](https://user-images.githubusercontent.com/1634213/87187539-9a4d0d00-c2ed-11ea-956b-54922bfcfb92.JPG)

So far I've managed to get some basic funcionality using a panGestureHandler, however, enabling pinch zooming is not possible with it, in fact zooming in general within a scrollview doesn't seem to be possible, is there anyway to achieve this?

**Comment by tom-un** [comment]
There are no plans to add this support.   Maybe you could use a NSMagnificationGestureRecognizer in your native code.
