### ISSUE TITLE
loading custom fonts does not seem to work

### ISSUE THREAD

**Issue by elcssmouhsine** [microsoft/react-native-macos#496]
### Environment

1. `react-native -v`: 
3. `npm ls react-native-macos`: react-native-macos@0.61.55
4. `node -v`: v10.16.0
5. `npm -v`: 6.14.5
6. `yarn --version`: 1.16.0
7. `xcodebuild -version`: Xcode 11.5 Build version 11E608c

i have followed every step in this tutorial  [link here](https://troz.net/post/2020/custom-fonts/) among many on the internet but it seems react-native-macos does not load fonts

also followed tutorial here : https://github.com/oblador/react-native-vector-icons#osx-via-react-native-desktop

**Comment by OKNoah** [comment]
I haven't been able to load fonts either. That includes with expo and rnvi.

**Comment by OKNoah** [comment]
@shayneoneill I "solved" it by simply making my app with vanilla RN and setting the macOS as a target platform. As for fonts, I use `expo-fonts`, which you can see a quick example of in my starter-kit/template here: https://gitlab.com/NoahGray/react-once-template/-/blob/main/template/src/App.js#L120. You can give the template a shot with with `npx create-react-once-app myapp` as described here: https://www.npmjs.com/package/create-react-once-app
