### ISSUE TITLE
On app start wrong IP is selected for packager

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#497]
### Environment

"react-native-macos": "^0.61.55"

### Steps to Reproduce

I changed networks from my home network to my office network, when I tried to start my app to fix a small issue the app won't start saying the packager is not running, however it seems the wrong IP address is picked up.

Things I already tried:
- Restarting my computer
- I already tried clearing the caches (including XCode's derived data)
- Changing access points
- Recheck my network settings to make sure no static IP is assigned
- Opened a different rn app (non-macos) and that is working fine

```swift
class ReactNativeBridgeDelegate: NSObject, RCTBridgeDelegate {

    func sourceURL(for bridge: RCTBridge!) -> URL! {
        let jsCodeLocation: URL
        #if DEBUG
          jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource:nil)
        #else
          jsCodeLocation = Bundle.main.url(forResource: "main", withExtension: "jsbundle")!
        #endif
        print("jsCodeLocation", jsCodeLocation)
        return jsCodeLocation
    }
}
```

My network IP is: `192.168.178.67`
The output of the code above is: `jsCodeLocation http://192.168.178.21:8081/index.bundle?platform=macos&dev=true&minify=false`

Cannot really tell you how to reproduce the issue, because it was working 1 hr ago when I was at my home network

**Comment by callaars** [comment]
I had the same thing earlier. I need to shut down my VPN connection before starting React Native. I am a RN developer by trade and I've never seen this with the other versions (haven't tried Windows to be honest).

**Comment by tom-un** [comment]
react-native-macos shares virtually all the same bridging layer code as react-native for iOS.   In `RCTBundleURLProvider.m` there is code that can get/set the jsLocation to NSUserDefaults.    I suspect that your app's defaults has a `RCT_jsLocation` key persisted.

Try running `$ defaults read your.app.bundle.id` and see what's there?   (RNTester, for example, would be `defaults read Microsoft.RNTester-macOS`).

If it has a `RCT_jsLocation`, you could surgically remove it using `defaults`, or just blow away all the app's defaults via:
`defaults delete Microsoft.RNTester-macOS`

**Comment by ospfranco** [comment]
ah yes, reading the defaults does show the IP is hardcodeddefaults read com.ospfranco.kipu

```
{
    "NSWindow Frame Main Window" = "1280 0 1280 777 0 0 2560 1417 ";
    RCTDevMenu =     {
        devModeEnabled = 1;
        hotLoadingEnabled = 1;
        isDebuggingRemotely = 0;
        shakeToShow = 1;
        showInspector = 0;
    };
    "RCTI18nUtil_makeRTLFlipLeftAndRightStyles" = 1;
    "RCT_jsLocation" = "192.168.178.21";
}
```

did I do something to persist this? how can I avoid it in the future?

**Comment by tom-un** [comment]
I'm not actually sure how it could be set.   You could put a breakpoint on line 245 of RCTBundleURLProvider.m and run your app.

**Comment by Zorgatone** [comment]
Where is this file located?
