### ISSUE TITLE
Add focusable to Pressable

### ISSUE THREAD

**Issue by chrisglein** [microsoft/react-native-macos#500]
From [Keyboarding in React Native Desktop](https://microsoft-my.sharepoint-df.com/:w:/r/personal/harinik_microsoft_com/_layouts/15/guestaccess.aspx?e=vboyhr&wdLOR=c797FF090-3702-4FEE-AD68-1E204281FFD9&share=EY4TcWAvR4tKu7EjxUG7OcwBkIHpcehA26atyX4BTwCYLw) document:

> Property that determines whether this View, Touchable should be focusable with a non-touch input device, eg. receive focus with a hardware keyboard. Setting the property to true will make that View compoonent become a part of tabbing loop. 
> - Add focusable to Pressable

**Comment by NickGerleman** [comment]
Left comments in https://github.com/microsoft/react-native-windows/issues/5512, but we should already have this for free.

**Comment by NickGerleman** [comment]
Going to close this one since I think there's nothing left to do. @chrisglein please reopen if I missed something here.
