### ISSUE TITLE
GIFs are not played

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#507]
### Environment
"react-native-macos": "^0.61.55"
### Steps to Reproduce

Seems like using a GIF with an Image component does not play the content, all I get is a static image

![Screenshot 2020-07-18 at 09 15 04](https://user-images.githubusercontent.com/1634213/87847291-4fc42580-c8d7-11ea-9dc8-912e21dfcf80.JPG)

**Comment by tom-un** [comment]
I'm afraid animated GIFs are not implemented in react-native-macos.

It is not a priority for us to implemented, but we would welcome a contribution from the community to implement it.   I actually stared implementing it in this branch: https://github.com/microsoft/react-native-macos/compare/master...tom-un:tomun/animated-gif.   It could be a starting point for someone else to finish.
