### ISSUE TITLE
Add `.focus()`, `.blur()`, `onFocus()`, `onBlur()` and `isFocused()` to Pressable

### ISSUE THREAD

**Issue by harinikmsft** [microsoft/react-native-macos#518]
From Keyboarding in React Native Desktop document:

> Add .focus(), .blur(), onFocus(), onBlur() and isFocused() to Pressable. These are currently supported in View, TextInput.

**Comment by HeyImChris** [comment]
I'm not sure I know what you mean by `Pressable` as that's not an actual component. That said, support for onFocus and onBlur was recently added to Button, Text Input, TouchableBounce, TouchableHighlight, TouchableOpacity, and TouchableWithoutFeedback. Does that resolve this for you or is there something else that you need those events on?

**Comment by acoates-ms** [comment]
Pressable was added in 0.63.

**Comment by HeyImChris** [comment]
Gotcha thanks for the heads up. Will be a while until we can get to this then as we haven't started the 0.63 merge yet.

**Comment by chrisglein** [comment]
Peer issue in the RNW repo: https://github.com/microsoft/react-native-windows/issues/5589
