### ISSUE TITLE
Is there currently any way to draw SVG graphics?

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#522]
Hey! I've reached the point were I need to create some custom graphics for my app, I tried to dumb port react-native-svg to macos but it's obviously not easy and it is not working

I also tried the ART module from react-native itself, but it looks like it is not implemented on macOS yet.

I was thinking about using a webview, but the problem is that it will be statically loaded, there is no communication between the app and the webview, is there any other possible way to generate graphics?

**Comment by tom-un** [comment]
Hi @ospfranco: regarding the ART module: we never had a use for it internally at Microsoft, so I've never deeply tested it.   We *did* port it, and it *does* build and the simple test in RNTester renders the same way that iOS renders.   But that RNTester page is the deepest I've ever tested it.

I've only made a cursory glance at the react-native-svg code on github just now.   I looks like the iOS code would port to mac cleanly: it's just using CoreGraphics as far as I can tell.

**Comment by ospfranco** [comment]
Ah, I see, then maybe I'm doing something wrong with the ART module, I will take another look, thanks a lot!

Regarding react-native-svg I did try to see if it would be an issue of adding macos to the podspec but quickly hit some UIKit errors, I did fumble my way around trying to get it to compile but failed miserably: https://github.com/ospfranco/react-native-svg/commit/89c268716e0a8fa943d4abe67078da80c097576b

**Comment by ospfranco** [comment]
I just tried to copy the ART example from the RNTester into my app, but it seems like something might not be correctly exported

<img width="2382" alt="Screenshot 2020-07-29 at 18 57 09" src="https://user-images.githubusercontent.com/1634213/88829914-8b12fe00-d1cd-11ea-8402-0bc9ea61228d.png">

**Comment by ospfranco** [comment]
Ah, I needed to add React-ART to the podspec

pod 'React-ART', :path => '../node_modules/react-native-macos/Libraries/ART'

seems like the type is missing however

**Comment by tom-un** [comment]
@ospfranco: I have some bad news about the ART module.   It was ejected from react-native in 0.62 which means that when we merge .62 into this fork, the macOS ART module will go away.   The RN .62 merge is imminent: #526.   Someone needs to port the macOS ART module to the new react-native-community repo: #387.   Internally, we do not have the funding to do the port because we don't use it ourselves.   Just wanted to give you a heads up since I am working on the merge and noticed that its now gone.

**Comment by ospfranco** [comment]
I see, thanks a lot, tbh I think I have pushed the ART module as far as I could... I need some interactivity and that is not possible, I guess waiting for rn svg is the best option for now
