### ISSUE TITLE
'Question: [RCTView support cursor property]'

### ISSUE THREAD

**Issue by RockyF** [microsoft/react-native-macos#525]
Now i need to modify cursor when mouseEntered and restore it after mouseExited.
if can export a prop likes `cursor`, eg: `<View cursor="pointingHand"/>`

Thanks.

**Comment by RockyF** [comment]
I resolved it by `onMouseEnter` and `onMouseLeave` event hooks,
And set cursor by a nativemodule `react-native-app-interface`!

**Comment by arturmusin** [comment]
> nativemodule `react-native-app-interface`

could you please shed some light how did you do that ? I have installed "react-native-app-interface" via npm. What should be done next? Could you paste some code sample please?
