### ISSUE TITLE
Proposal: Add acceptsFirstMouse prop to View and Touchables

### ISSUE THREAD

**Issue by appden** [microsoft/react-native-macos#531]
# Proposal: Add acceptsFirstMouse prop to View and Touchables (future: Pressable)

Presently in RN macOS, clickable views (buttons, etc.) require *two* clicks when that window is not in the foreground. This counter to the typical behavior on macOS where controls will default to accepting the mouse event even when in the background (and simultaneously bring to the foreground unless the command key is held).

## Summary

This prop would default to `false` for `View`, but default to `true` on `Touchable*` and the future `Pressable` components. The `NSView` class has an [`acceptsFirstMouse:`](https://developer.apple.com/documentation/appkit/nsview/1483410-acceptsfirstmouse?language=objc) to control this behavior.

**Note:** In Electron, the [`BrowserWindow`](https://www.electronjs.org/docs/api/browser-window) API include an `acceptFirstMouse` option to control this behavior for the entire window, which is better than nothing but not granular enough for a native-feeling experience on the Mac.

## Motivation

This is long-standing Mac behavior, formerly described in the Apple Human Interface Guidelines (HIG) as "click-through". It should be controllable via this `acceptsFirstMouse` prop because there are legitimate reasons to disable it. From the old HIG:

> Avoid providing click-through for an item or action whose result might be dangerous or undesirable. Specifically, avoid enabling click-through for an item that:
> - Performs a potentially harmful action that users can’t cancel (for example, the Delete button in Mail)
> - Performs an action that is difficult or impossible to cancel (such as the Send button in Mail)
> - Dismisses a dialog without telling the user what action was taken (for example, the Save button in a Save dialog that overwrites an existing file and automatically dismisses the dialog)
> - Removes the user from the current context (for example, selecting a new item in a Finder column that changes the target of the Finder window)

## Open Questions

I'm not married the `acceptsFirstMouse` name. Electron dropped the "s", which is fine, and really anything else descriptive is fine. I don't think it should use the "click-through" terminology however, because that would be fairly confusing.

In **React Native Windows**, this "click-through" behavior is already present by default, thus matching the behavior of most controls on Windows. The only exception I've found on Windows are menus/toolbars, such as those in File Explorer, Office, and MS Paint. Those don't accept clicks while the window is in the background, and therefore it would reasonable to explore adding this API to React Native Windows for parity and to give developers a similar level of control.

**Comment by alloy** [comment]
Makes a lot of sense to me 👍

I have no strong opinion on the name itself, other than there being merit in leaving the name as-is so it’s easier to find conceptual information about 🤷‍♂️ 

cc @tom-un

**Comment by chrisglein** [comment]
Seems like this is the right thing to do. CC @kikisaints in case there is some parallel for Windows, but I believe the default behavior there is to allow window click through and some apps do additional work to not do that. As in there isn't a clean Windows API to map to here, so I think no work required.

Assuming that's true, no cross-platform coordination, so this proposal is good to go as soon as someone makes the change.
