### ISSUE TITLE
Add TypeScript support for semantic colors

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-macos#540]
# Proposal: Add TypeScript support for semantic colors

## Summary
Recently I learned that in styles I can use OS colors using code like `{semantic: 'selectedContentBackgroundColor'}`. But when I do so TypeScript gives an error:

```
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<ViewProps>): View', gave the following error.
    Type '{ backgroundColor: { semantic: string; }; }' is not assignable to type 'false | ViewStyle | RegisteredStyle<ViewStyle> | RecursiveArray<false | ViewStyle | RegisteredStyle<ViewStyle> | null | undefined> | readonly (false | ... 3 more ... | undefined)[] | null | undefined'.
      Types of property 'backgroundColor' are incompatible.
        Type '{ semantic: string; }' is not assignable to type 'string'.
  Overload 2 of 2, '(props: ViewProps, context?: any): View', gave the following error.
    Type '{ backgroundColor: { semantic: string; }; }' is not assignable to type 'false | ViewStyle | RegisteredStyle<ViewStyle> | RecursiveArray<false | ViewStyle | RegisteredStyle<ViewStyle> | null | undefined> | readonly (false | ... 3 more ... | undefined)[] | null | undefined'.
      Types of property 'backgroundColor' are incompatible.
        Type '{ semantic: string; }' is not assignable to type 'string'.ts(2769)

```
## Motivation

Proper TypeScript support

**Comment by acoates-ms** [comment]
I believe this is fixed by using PlatformColor and the 0.63 typings for react-native.  The details of the object layout of the colors are intentionally hidden.

https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d2a9bce984b33920378ff6661fdf9c683274a0b4#diff-7c5007b14419e07403a6a320e5b22742

**Comment by alloy** [comment]
Correct. If needed we can backport this to the RN 0.62 typings; let me know.

**Comment by lyahdav** [comment]
I don't think it's urgent. We can wait until we're on 0.63. Thanks.

**Comment by lyahdav** [comment]
@acoates-ms Any idea of the support of PlatformColor on RN Windows?

**Comment by acoates-ms** [comment]
PlatformColor should work in 0.63. -- It takes an array of values of a XAML resource keys that should be used. -- It unfortunately currently does not support fallback values, so only the first value is used.

In 0.62 you can use colors with the format of {windowsBrush: <string>}. -- But there is no typings for that, and going forward PlatformColor is the thing we will be supporting.
