### ISSUE TITLE
Xcode thinks app is for iOS and the app only runs in iOS Simulator Xcode 11.3.1

### ISSUE THREAD

**Issue by johncaling40** [microsoft/react-native-macos#541]
### Environment

1. `react-native -v`: 3.2.1
3. `npm ls react-native-macos`: macosRNTest@0.0.1 /Users/arcarc/macosRNTest
└── react-native-macos@0.61.65 
4. `node -v`: v14.7.0
5. `npm -v`:   6.14.7
6. `yarn --version`: n/a
7. `xcodebuild -version`:  11C505

### Issue
Xcode thinks app is for iOS and the app only runs in iOS Simulator Xcode 11.3.1. 
### Steps to Reproduce

(Write your steps here:)

1. Follow instructions here https://microsoft.github.io/react-native-windows/docs/rnm-getting-started
2. Open Project with Xcode instead of npm command at bottom
3. See error

### Expected Behavior

I thought the app would run like other macOS apps which would be opening a normal macOS window
### Actual Behavior

Xcode thinks app is for iOS and the app only runs in iOS Simulator Xcode 11.3.1. 

### Reproducible Demo

https://microsoft.github.io/react-native-windows/docs/rnm-getting-started

### Additional context

(Write any other additional context that may help in root causing the issue.)

**Comment by HeyImChris** [comment]
What schemes do you have available? I just ran it and it defaulted to iOS, but I was able to switch it to `<project_name>-macOS` and build/run for macOS.

Fwiw it's expected that you have iOS support in that xcworkspace as well since react-native-macos takes react-native with iOS and extends it to work for macOS, so it should be able to build for both platforms.

**Comment by johncaling40** [comment]
How do you _switch it to <project_name>-macOS_?

**Comment by HeyImChris** [comment]
It's just a scheme change. Does this help?

<img width="493" alt="Screen Shot 2020-08-14 at 10 21 44 AM" src="https://user-images.githubusercontent.com/48299693/90276065-23d58a80-de18-11ea-8284-9fa32aba02b0.png">
<img width="630" alt="Screen Shot 2020-08-14 at 10 21 51 AM" src="https://user-images.githubusercontent.com/48299693/90276070-2637e480-de18-11ea-850e-b94800c4ccd8.png">

**Comment by johncaling40** [comment]
I get `RNTestMac/node_modules/react-native-macos/Libraries/Vibration/RCTVibration.m:18:32: Use of undeclared identifier 'kSystemSoundID_Vibrate'`

**Comment by johncaling40** [comment]
I was able to fix this by comminting(`/**/`) out line 18(`AudioServicesPlayAlertSound(kSystemSoundID_Vibrate);`) of `node_modules⁩/react-native-macos⁩/Libraries⁩/Vibration⁩/RCTVibration.m`. My guess is that it gave that error because `AudioServicesPlayAlertSound(kSystemSoundID_Vibrate);` is an iOS inly function as Macs do not have vibration support.
