### ISSUE TITLE
Question: How can I build a dmg file or zip in release?

### ISSUE THREAD

**Issue by xyz0405** [microsoft/react-native-macos#544]

**Comment by HeyImChris** [comment]
Assuming you're talking about how to automate it producing as a zip, AFAIK we're only producing it publicly as an [npm package](https://www.npmjs.com/package/react-native-macos). If you want to modify the [publish pipeline](https://github.com/microsoft/react-native-macos/blob/master/.ado/publish.yml) you're welcome to fork the repo and edit the pipeline's yml to publish it however you'd like from there.

**Comment by tom-un** [comment]
Are you asking how to package your own app as a Zip or DMG?   The details of how you distribute your own app is something outside of the scope of this project.   However, it's relatively easy to manually make a DMG using Disk Utility or a Zip via the Finder.   If you want to automate the creation of a DMG, you could look at other open source projects such as https://github.com/LinusU/node-appdmg.
