### ISSUE TITLE
Question: Is it possible to disable  Developer Menu in Release

### ISSUE THREAD

**Issue by bralax** [microsoft/react-native-macos#545]
I am getting ready to release a project using this library. I just built a release version as a test and noticed that the devmenu still appears when you right click. I tested to see what would happen when you click the different options and a lot of them cause the system to crash now as they should not be available anymore (like open debug). Is there anyway to turn off the developer menu?

**Comment by acoates-ms** [comment]
See https://github.com/microsoft/react-native-macos/pull/528.

**Comment by bralax** [comment]
Hi @acoates-ms. Now that the pull request you mention has been merged, I have realized that it does not actually answer the question I have. 

The [DevSetting object](https://github.com/microsoft/react-native-macos/blob/master/Libraries/Utilities/DevSettings.js), which contains the isSecondaryClickToShowDevMenuEnabled is only available when in debug mode. This means that you do not have access to this option when in Release mode basically blocking the ability to disable the debug menu in release mode.

**Comment by ospfranco** [comment]
Hi! I'm just facing this issue, any news here?

Also, I enabled hermes on my project and even though it is compiled on release mode, the window still shows development? is this correct?

<img width="700" alt="Screenshot 2020-10-28 at 09 02 58" src="https://user-images.githubusercontent.com/1634213/97408455-64638100-18fc-11eb-8101-1ee38c70f0f8.png">

**Comment by ospfranco** [comment]
Circling back here, is this in any way shape or form fixed?

**Comment by dimaportenko** [comment]
I dive deeper in the source code and found 
```
// React/Base/RCTDefines.h

/**
 * The RCT_DEV macro can be used to enable or disable development tools
 * such as the debug executors, dev menu, red box, etc.
 */
#ifndef RCT_DEV
#if DEBUG
#define RCT_DEV 1
#else
// Dev Mode is now enabled or disabled at runtime via the -[RCTDevSettings isDevModeEnabled] property
#define RCT_DEV 1
#endif
#endif
```
And following comment explain what is going on
> // Dev Mode is now enabled or disabled at runtime via the -[RCTDevSettings isDevModeEnabled] property

so I end up with following code for my project
```
import {AppRegistry, NativeModules} from 'react-native';
import App from './src/App';
import {name as appName} from './app.json';

if (__DEV__) {
  NativeModules.DevSettings.setDevModeEnabled(true);
} else {
  NativeModules.DevSettings.setDevModeEnabled(false);
}

AppRegistry.registerComponent(appName, () => App);
```
