### ISSUE TITLE
[!] Invalid `Podfile` file: 767: unexpected token at 'info Run "react-native --help" to see a list of all available commands.

### ISSUE THREAD

**Issue by sangeethkumarv** [microsoft/react-native-macos#563]
When I did mac os init in my project it fails with the following message

Environment:
Mac OS Version: 10.15.4 (19E287)
React Version:   "react": "16.9.0",
                           "react-native": "0.61.5"

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error: error Unrecognized command "config".

 #  from /Users/dev/Desktop/Sangeeth/****/Myt-Mac/MacOS/macos/Podfile:44
 #  -------------------------------------------
 #      platform :ios, '9'
 >      use_native_modules!
 #      # Pods specifically for iOS target
 #  -------------------------------------------

    at CocoaPodsPackageManager._installAsync (/Users/dev/.npm/_npx/19556/lib/node_modules/pod-install/build/index.js:2:85721)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Command failed: npx --quiet pod-install --non-interactive --quiet { Error: Command failed: npx --quiet pod-install --non-interactive --quiet
    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at installPods (/Users/dev/Desktop/Sangeeth/mytakeaway2.0/Myt-Mac/MYT_MacOS/node_modules/react-native-macos/local-cli/generator-macos/index.js:153:16)
    at generateMacOS (/Users/dev/Desktop/Sangeeth/mytakeaway2.0/Myt-Mac/MYT_MacOS/node_modules/react-native-macos/local-cli/generate-macos.js:33:3)
    at Object.<anonymous> (/Users/dev/.npm/_npx/19090/lib/node_modules/react-native-macos-init/lib-commonjs/cli.js:254:9)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dev/.npm/_npx/19090/lib/node_modules/react-native-macos-init/lib-commonjs/cli.js:10:58)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19556,
  stdout: null,
  stderr: null }

This is how podfile looks like

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

abstract_target 'Shared' do
  # Pods for ****
  pod 'FBLazyVector', :path => '../node_modules/react-native-macos/Libraries/FBLazyVector'
  pod 'FBReactNativeSpec', :path => '../node_modules/react-native-macos/Libraries/FBReactNativeSpec'
  pod 'RCTRequired', :path => '../node_modules/react-native-macos/Libraries/RCTRequired'
  pod 'RCTTypeSafety', :path => '../node_modules/react-native-macos/Libraries/TypeSafety'
  pod 'React', :path => '../node_modules/react-native-macos/'
  pod 'React-Core', :path => '../node_modules/react-native-macos/'
  pod 'React-CoreModules', :path => '../node_modules/react-native-macos/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native-macos/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native-macos/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native-macos/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native-macos/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native-macos/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native-macos/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native-macos/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native-macos/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native-macos/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native-macos/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native-macos/'

  pod 'React-cxxreact', :path => '../node_modules/react-native-macos/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native-macos/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native-macos/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native-macos/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => '../node_modules/react-native-macos/ReactCommon'
  pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native-macos/ReactCommon'
  pod 'Yoga', :path => '../node_modules/react-native-macos/ReactCommon/yoga'

  pod 'boost-for-react-native', :podspec => '../node_modules/react-native-macos/third-party-podspecs/boost-for-react-native.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native-macos/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native-macos/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native-macos/third-party-podspecs/Folly.podspec'

  target '****-macOS' do
    platform :macos, '10.14'
    # Pods specifically for macOS target
  end

  target '****-iOS' do
    platform :ios, '9'
    # Pods specifically for iOS target
  end
end

**Comment by sangeethkumarv** [comment]
Solved this by removing  use_native_modules! in all places in pod file inside mac os directory

**Comment by timbicker** [comment]
@HeyImChris I re-comment because this issue still exists. It feels weird to manually edit the Podfile. If this is the issue, why don't just remove it from `react-native-macos-init`? This shouldn't take more than a few minutes. So I wonder what's the purpose of `use_native_modules!` if I can simply delete it.
