### ISSUE TITLE
Building/Managing NSMenu with JS

### ISSUE THREAD

**Issue by safaiyeh** [microsoft/react-native-macos#576]
# Proposal: Building/Managing NSMenu with JS

## Summary

AppKit allows managing menubar menus with NSMenu https://developer.apple.com/documentation/appkit/nsmenu

![Screen Shot 2020-09-03 at 7 06 46 AM](https://user-images.githubusercontent.com/8675043/92125580-09a62100-edb4-11ea-9b83-3102c563243b.png)

There is the ability to create tray apps as mentioned here: https://ospfranco.github.io/post/2020/05/23/how-to-make-a-react-native-menu-bar-app-for-mac-os/ however, this does not give the ability to build native menu items

## Motivation

I currently have a macOS application that uses NSMenu to create a menubar app. This requires data & actions to be passed between the application and the NSMenu listeners.

The application would need to be able to pass JS functions and data to the NSMenu.

## Basic example

A possible example from ptmt/react-native-macos, `View` components managed the NSMenu

From https://github.com/ptmt/react-native-macos/issues/237#issuecomment-477554281:
```jsx
const contextMenu = [
  { key: 'foo', title: 'Foo' },
  { isSeparator: true },
  { key: 'bar', title: 'Bar' },
]

<View
  contextMenu={contextMenu}
  onContextMenuItemClick={event => {
    console.log(event.nativeEvent)
 }} />
```

## Open Questions

How would this API/view declaration look like if the menu manager is separate from the application view? 

NSMenu relies on manual calls of [update](https://developer.apple.com/documentation/appkit/nsmenu/1518249-update) to update the view, this may make it easier to support the separate lifecycle

How would persisting data when the desktop app is not running work?

Would this be more appropriate as a separate module?

**Comment by kevinvangelder** [comment]
https://github.com/microsoft/react-native-macos/issues/492#issuecomment-657820916

**Comment by safaiyeh** [comment]
Thanks @kevinvangelder! I'll close this. I'll hack away on a module this weekend

**Comment by lyahdav** [comment]
In case it's helpful here's my implementation of a native module for this:
- ContextMenuNativeModule-macOS.h: https://gist.github.com/lyahdav/1afb5e98562954f971793c12b9ba5e1f
- ContextMenuNativeModule-macOS.mm: https://gist.github.com/lyahdav/0ee567426d9001cd812b6b1dda05a700
- ContextMenuNativeModule.tsx: https://gist.github.com/lyahdav/8c9064aadc2a5d868097ca27a1c6207b

For API look at the TS types in `showNativeContextMenu` in `ContextMenuNativeModule.tsx`.

**Comment by safaiyeh** [comment]
Hey @lyahdav this is amazing. I also saw ur windows one. Would you want to collaborate on making this an OSS package?

**Comment by lyahdav** [comment]
I don't have the bandwidth for that anytime soon, but feel free to go for it based off the code above if it helps. One thing to be careful about is that with the new RN Fabric architecture `findNodeHandle` is going away, so it might make more sense to build this as an actual ViewManager/Component like the Windows PR here: https://github.com/microsoft/react-native-windows/pull/2738

**Comment by safaiyeh** [comment]
Awesome! I'll put something up and make sure to give you credit
