### ISSUE TITLE
Touchable* onMouseEnter/Leave callbacks no longer called on 0.62

### ISSUE THREAD

**Issue by appden** [microsoft/react-native-macos#588]
# Issue

`onMouseEnter` and `onMouseLeave` are no longer being called on `Touchable*` components.

### Steps to Reproduce

See `TouchableHover` example in RNTester.

### Expected Behavior

The callbacks are passed along to the underlying `View`

### Actual Behavior

![gif](https://user-images.githubusercontent.com/70904/92520756-f8547e80-f1d0-11ea-9feb-ddf2175f9c3a.gif)

**Comment by alloy** [comment]
The fix has been merged and has been cherry-picked and released as v0.62.8.

**Comment by NickGerleman** [comment]
Oh wow we had the exact same issue in RNW https://github.com/microsoft/react-native-windows/issues/5715 (think the macOS solution is cleaner than what we did)

Wondering how many upgrade issues end up being common between react-native-macos and react-native-windows.
