### ISSUE TITLE
Can window controller manage from JS ?

### ISSUE THREAD

**Issue by melihberberolu** [microsoft/react-native-macos#593]
When open xcode see the window controller area with window controller native buttons. (close, fullscreen)
Can we change that area from JS ? 

For example: set height 120, put select box the center, use right side of support links.
<img width="526" alt="Screen Shot 2020-09-10 at 9 04 44 PM" src="https://user-images.githubusercontent.com/3721734/92778024-710e3300-f3a9-11ea-8ceb-6c2d4549c08c.png">

**Comment by chrisglein** [comment]
Answer is no. There's not control over the top level window from JS. There is a setting you can do on the root view for sizing, but that won't affect the Window. If you want to change the default size of the window you can do that in the storyboard.

Somewhat related issue for Windows [here](https://github.com/microsoft/react-native-windows/issues/3580). But this sort of thing is likely to remain native-specific per platform, not unified across JS.
