### ISSUE TITLE
'Question: Multiple windows'

### ISSUE THREAD

**Issue by ziulev** [microsoft/react-native-macos#604]
I want to implement something like widgets so I need to have an ability to say where to renderer my component.
I mean I want to render few windows.

Does it possible to have multiple windows with multiple react components?

**Comment by chrisglein** [comment]
@tom-un This question has come up before, you may be able to refer to answers from old issues. But this seems like a common enough question that we may want to cover it in the docs.

**Comment by vascofg** [comment]
Can someone link an example on how to achieve this? I can't find any references

**Comment by jet8a** [comment]
AppDelegate.swift
swift```
    var bridge: RCTBridge!
    
    #if DEBUG
        jsCodeLocation = RCTBundleURLProvider.sharedSettings().jsBundleURL(forBundleRoot: "index", fallbackResource:nil)
    #else
        jsCodeLocation = Bundle.main.url(forResource: "main", withExtension: "jsbundle")!
    #endif
  
    self.bridge = RCTBridge(bundleURL: jsCodeLocation, moduleProvider: nil, launchOptions: nil)
    #if RCT_DEV
    self.bridge?.module(for: RCTDevLoadingView.self)
    #endif

    let firstRootView = RCTRootView(bridge: self.bridge, moduleName: "yourFirstModuleNameHere", initialProperties: nil)
    let firstRootViewController = NSViewController()
    firstRootViewController.view = firstRootView
    
    
    let secondRootView = RCTRootView(bridge: self.bridge, moduleName: "yourSecondModuleNameHere", initialProperties: nil)
    let secondRootViewController = NSViewController()
    secondViewController.view = secondRootView
```

index.js
javasscript```
AppRegistry.registerComponent('yourFirstModuleNameHere', () => YourFirstContainer);
AppRegistry.registerComponent('yourSecondModuleNameHere', () => YourSecondContainer);

```
