### ISSUE TITLE
List items are not showing selection highlight color

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#605]
### Issue

When using keyboard navigation, Lists can be tabbed to and then the arrow keys can be used to move up and down through the items in the list.   The return key will press the item.

In previous versions of react-native-macos, the currently selected row in a list would render with the system's accent color.   In the current version, no background color changes at all.   So although the keyboard gestures work, the user is "flying blind"

### Steps to Reproduce

1. Ensure that keyboard navigation is enabled in System Preferences > Keyboard > Shortcuts > "Use keyboard navigation to move focus between controls"
2. Run RNTester
3. Press tab until the List is selected (no visual indicator that it is selected will appear)
4. Press down arrow a few times
5. Press Return

### Expected Behavior

When the List becomes first responder, the first row in the list should highlight with the system accent color.   When pressing the down arrow key, the highlighted row should change.

### Actual Behavior

Although rows in the List are invisibly changing selection, there is no visual feedback that this happening.

### Reproducible Demo

![ezgif com-gif-maker](https://user-images.githubusercontent.com/30053638/93606435-58fd6b80-f9c8-11ea-96d1-23c6d5ecca68.gif)

I found this issue while testing PR https://github.com/microsoft/react-native-macos/pull/603.  FYI: @alloy , @HeyImChris , and @tido64

**Comment by alloy** [comment]
How can we ensure these types of regressions get caught next time? Is this case something that can be tested for by asking the views for their state or would it require a visual snapshot test?

**Comment by tom-un** [comment]
> How can we ensure these types of regressions get caught next time? Is this case something that can be tested for by asking the views for their state or would it require a visual snapshot test?

In this case, perhaps an XCUITest case that performs the scenario, then examining the state and/or screenshot.  Examining the state would probably be more reliable as the screenshot state is so variable based on the version of the OS, the retina/non-retina-ness of the test machine's display, etc.

**Comment by chrisglein** [comment]
Regression as of 0.62 (or 0.63, but timeline probably indicates 0.62). Needs investigation to see how far back it goes, but expected this was known good in 0.61.
May have regressed from a merge in List/VirtualList.
Not an issue with accessibility APIs, but has effective accessibility impact.
