### ISSUE TITLE
Multiline TextInput with attributed text is rendered vertically offset

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#611]
### Issue

If a TextInput component is multiline and has text attributes (font styles) the text can be rendered vertically offset from the components bounds.

### Steps to Reproduce

1. Run RNTester and navigate to the TextInput test page
2. Scroll down to the Multiline section
3. Notice that the red "multiline textinput with font styles and placeholder" is rendered *below* the second TextInput rectangle
4. Click in the second TextInput and type.
5. Notice that whatever you type is rendering below and outside of the second TextInput rectangle.

### Expected Behavior

The TextInput's text should render within the bounds of the TextInput component.

### Actual Behavior

The TextInput's text is offset vertically and is rendering outside of the TextInput bounds.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/30053638/93871943-b7c82b00-fccf-11ea-9a9e-d1f62e03454a.gif)

### Additional context

This is not a new issue.   TextInput that is multiline and has font styling has always had this issue in react-native-macos.   Its unclear what the root cause issue may be -- maybe something to do with macOS NSView's default coordinate system being flipped vertically unlike iOS UIViews.

**Comment by chrisglein** [comment]
NSTextStorage is heavily customized so there's potential that the root cause is there. Also default coordinate system is flipped with macOS relative to iOS, so there's opportunity for failure there. But cause isn't yet known. Needs someone to spelunk in and find out.
