### ISSUE TITLE
How to setup macos playground?

### ISSUE THREAD

**Issue by Patys** [microsoft/react-native-macos#616]
Hello 👋 

Basically I just read through contributing guideline and setup repo. I'm using macos and I found that playground is missing code for macos 🤔 (Maybe I'm wrong but I cannot find entry point - I can make pr to clarify it contribution guideline).

So I started to setup macos build and I manage to have running playground on macos. Unless it's breaking during metro loading as it's cannot find proper libraries (as on screenshot):
<img height="400" src="https://user-images.githubusercontent.com/8997573/94153123-ac663280-fe7c-11ea-88ee-113f98a9750e.png" />

How I make it working to this point?
1. I generated new RN project with macos init.
2. I copy-paste Playground folder for macos
3. I adjusted paths in native project files (packages/playground/macos/Playground.xcodeproj/project.pbxproj) so they use proper node_modules
4. I fixed podfile in same way like in 3.
5. I added: vnext/RNTester/js/RNTesterApp.macos.js. It's the same as: vnext/RNTester/js/RNTesterApp.windows.js
6. I modified metro command to: (removed option --use-macos or sth like that beacuse of it metro didn't wanted to start)
```    
"start:macos": "node ../../node_modules/react-native-macos/local-cli/cli.js start"
```
7. Run `yarn start:macos`
8. Run `yarn mac`

App is building, you get native window, metro starts loading and stops after few files.

Here is overview on changes: https://github.com/Patys/react-native-windows/pull/1/files

How can I improve setup or make macos playground working? How can we lower entry point to contribute?

**Comment by asklar** [comment]
moved to macos

**Comment by Patys** [comment]
🤦 my mistake, I didn't check that there is a different repo for macos. I thought that they are like in RN, together 😄 Now it makes sense 😄
