### ISSUE TITLE
PR CI tests to release branches hang on the Circle CI tests

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#619]
### Issue

When a PR is made that targets a release branch like `0.62-stable`, all the Azure DevOps tests work fine, but four of the Circle CI tests seem to hang perpetually

### Steps to Reproduce

1. Make a PR that targets `0.62-stable`
2. Notice that four Circle CI tests are stuck in "waiting for status..."

![cci-stall](https://user-images.githubusercontent.com/30053638/94417109-f6525f80-017f-11eb-92e8-8aaca8c65b8e.png)

### Expected Behavior

Circle CI tests should trigger and pass as they do for tests targeting `master`.

**Comment by chrisglein** [comment]
Tests may need to be evaluated for how much value they're adding, but that's independent of whatever issue is causing them to hang. Only affects the release branch and thus a limited audience of engineers. Kind of up to core contributors whether to disable the tests or figure out what's going on. There's been some short investigation (~hour) and it wasn't anything obvious.
