### ISSUE TITLE
v0.63 merge TODOs

### ISSUE THREAD

**Issue by alloy** [microsoft/react-native-macos#621]
For once https://github.com/microsoft/react-native-macos/pull/613 is merged.

- [x] ~~Get Android patches to apply and work as expected and/or move them out of this repo. This includes the Folly, double-conversion, and possible other vendored libs in the root of the repo.~~ https://github.com/microsoft/react-native-macos/pull/641

- [x] Update `react-native-macos-init`:
     * The Podfile needs reconciliation with with upstream and RNTester
     * Ensure the user can enable hermes

- [x] Go through all `TODO(macOS v0.63)` instances and verify new behaviour
  - [x] ~~https://github.com/facebook/react-native/commit/fb8f5ea07f9fb5899e0c848792bd78792798a2dd~~ https://github.com/microsoft/react-native-macos/pull/631/commits/8a20e2cb6630a97da8b6318d621964dfbce3a0f1

- [x] Ensure the CircleCI nightly job isn't ran

- [ ] `RNTester/Podfile`:
    - [x] `require_relative '../scripts/react_native_pods'`
    - [x] `use_flipper!`
    - [ ] Change macOS targets to have deployment target of 10.13 (need newer hermes release) depends on https://github.com/facebook/hermes/pull/351. The artefacts need testing on a arm64 DTK.

- [x] `Libraries/Components/View/ReactNativeViewViewConfig.js`:
       Do `platform === ios` checks need macOS as well?

- [x] `Libraries/Pressability/__tests__/Pressability-test.js`:
     does this still fail: is called independent of preceding long touch gesture

- [x] ~~https://github.com/facebook/react-native/commit/5394c908ebe21ffb9d8b0764011b25e6a0973e6f:
     Should we remove our addition to RCTTextAttributes?~~ https://github.com/microsoft/react-native-macos/pull/631

- [x] ~~`Libraries/Text/TextInput/Singleline/RCTUITextField.m`:
     Do we still need to disable scrollEnabled on macOS? https://github.com/facebook/react-native/commit/827b1fe7a4164eeb5aa9cf57d47af1a7b949592c~~ https://github.com/microsoft/react-native-macos/pull/631

- [x] ~~`React/Base/RCTTouchHandler.m`:
     Does `- (NSInteger)_eventWithNumber:(NSInteger)touchID` still need to be an extracted method? Was it shared previously?~~ https://github.com/microsoft/react-native-macos/pull/625

- [x] ~~`React/Base/RCTUtils.m`:
     Does `RCTForceTouchAvailable` still need a iOS (10) guard?~~ https://github.com/microsoft/react-native-macos/pull/626

- [x] ~~`React/CoreModules/CoreModulesPlugins.mm`:
     Remove guard around `RCTLogBoxCls`~~ Moving this to https://github.com/microsoft/react-native-macos/issues/627

- [x] ~~`React/CxxBridge/RCTCxxBridge.mm`:
     Where did this change move? https://github.com/microsoft/react-native-macos/commit/150f935ee9f75ecb69c332be2160bec205b13385#diff-a2a67635fffd7b690d14dc17ae563a71R933~~ https://github.com/microsoft/react-native-macos/pull/628

- [x] ~~`React/Views/RCTView.m`:
     Do we still need `savedTraitCollection` in `displayLayer:`?~~
    * ~~https://github.com/microsoft/react-native-macos/commit/5bff60fe0d6d8dfc4f493cb4ecb8b9c8145b432a#diff-82cd0f8fb7478261a85ac686ac07be50R793-R801~~
    * ~~https://github.com/microsoft/react-native-macos/commit/5bff60fe0d6d8dfc4f493cb4ecb8b9c8145b432a#diff-82cd0f8fb7478261a85ac686ac07be50R814-R821~~
     No longer needed, as per @tom-un’s comment below.

- [x] ~~Revisit the code-sharing between iOS and macOS `PlatformColorValueTypes` here https://github.com/microsoft/react-native-macos/pull/613/commits/5065f58e0fe5cacbdbbd99302220468e0a616913~~ https://github.com/microsoft/react-native-macos/pull/631/commits/e030009a39d1f7bd77c72719cb97cf32cc405f63

- [x] Is the naming of these alternate color names important? https://github.com/microsoft/react-native-macos/pull/613/commits/21c189d485f02340032ca2806f8fd4c55e5d590c
     Apparently not https://github.com/microsoft/react-native-macos/pull/613#discussion_r497409911

- [x] ~~Image in RNTester doesn't load. The following message is logged:
     `Reloading image http://192.168.1.35:8081/assets/node_modules/react-native-macos/Libraries/NewAppScreen/components/logo.png?platform=macos&hash=47ce6e77f039020ee2e76a10c1e988e9 as size {918, nan}`~~ Fixed by https://github.com/microsoft/react-native-macos/pull/637.

- [x] ~~LogBox does not have a working full screen version.~~ https://github.com/microsoft/react-native-macos/pull/645

## Not now

- [ ] Should we run clang-format as per upstream? https://github.com/facebook/react-native/commit/d0871d0a9a373e1d3ac35da46c85c0d0e793116d
  * Should probably do this last so we can easily merge in master
  * Ensure it also runs on cpp files
  * Add a git/CI hook to ensure files are prettified?
  * Currently upstream `master` is not formatted either, so doesn't seem like the right time. Asking upstream maintainers what their plans are.

- [ ] `Libraries/PushNotificationIOS/RCTPushNotificationManager.mm`:
     old deprecated macOS ifdef'ed code replaced by: RCTPromiseResolveValueForUNNotificationSettings
- [ ] `Libraries/PushNotificationIOS/RCTPushNotificationManager.mm`:
     use UUUserNotificationCenter on macOS in removeAllDeliveredNotifications, removeDeliveredNotifications, getDeliveredNotifications

**Comment by alloy** [comment]
@tom-un Do you recall why you didn’t move these iOS changes upstream in your (dynamic) color changes?

* https://github.com/microsoft/react-native-macos/commit/5bff60fe0d6d8dfc4f493cb4ecb8b9c8145b432a#diff-82cd0f8fb7478261a85ac686ac07be50R793-R801
* https://github.com/microsoft/react-native-macos/commit/5bff60fe0d6d8dfc4f493cb4ecb8b9c8145b432a#diff-82cd0f8fb7478261a85ac686ac07be50R814-R821

**Comment by tom-un** [comment]
It was per this code review feedback from nscoding: https://github.com/facebook/react-native/pull/27908#discussion_r374962276

And resulted in this commit by me: https://github.com/tom-un/react-native/commit/7a4629ba468798ca4714579a01d99564af2217e2

In short: in the react-native-macos fork, and in my initial PR upstream, in `-[RCTView displayLayer:]` needed to get a "flattened" color via `_backgroundColor.CGColor` using the correct traits.   In react-native-macos it was doing a `[UITraitCollection setCurrentTraitCollection:[self traitCollection]]` , call `_backgroundColor.CGColor`, then restore UITraitCollection via `[UITraitCollection setCurrentTraitCollection:savedTraitCollection]`.   Nscodings suggestion was to use `[_backgroundColor resolvedColorWithTraitCollection:self.traitCollection].CGColor` instead so that's what's upstream.

**Comment by alloy** [comment]
@tom-un Ok, so if I understand correctly we now have a iOS specific solution upstream and still need the platform guard in our fork with your previous change? It sounds like the upstream version should just use the change you previously had and then we can get rid of the change in our fork, no?
