### ISSUE TITLE
Enable previously disabled core turbo modules

### ISSUE THREAD

**Issue by alloy** [microsoft/react-native-macos#627]
During the v0.62.x merge, a couple of core turbo modules were disabled and need re-consideration, see https://github.com/microsoft/react-native-macos/commit/8ed4bc1e33d321783a847547a4565f50a2b84298#diff-415eb3b6425c153bf2dd1fca2b7c61e1. However, currently the `RCTCoreModulesClassProvider` function is only invoked from the iOS RNTester target, so this probably needs follow-up once @ZihanChen-MSFT’s TM work is completed.

- [ ] AccessibilityManager: ?
- [ ] Appearance: https://reactnative.dev/docs/appearance#docsNav
- [ ] PerfMonitor: https://reactnative.dev/docs/performance#what-you-need-to-know-about-frames
- [ ] LogBox: The new YellowBox/RedBox replacement https://reactnative.dev/blog/2020/07/06/version-0.63#logbox

**Comment by chrisglein** [comment]
@alloy Is this something you're planning doing as part of your checklist or should it be put up for grabs?

**Comment by alloy** [comment]
I’m currently working on making LogBox at least work on macOS—aside from its turbo module interface. Otherwise this ticket is up for grabs 👍
