### ISSUE TITLE
Clicking on a scroll bar triggers a click on component within the scroll view

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-macos#629]
### Environment

1. `react-native -v`: 6.13.4
3. `npm ls react-native-macos`:
```
react-native-macos@1000.0.0 /Users/lyahdav/Documents/react-native-macos
└── (empty)
```
4. `node -v`: v12.14.1
5. `npm -v`: 6.13.4
6. `yarn --version`: 1.21.1
7. `xcodebuild -version`:
```
Xcode 11.6
Build version 11E708
```

### Issue

Clicking on a ScrollView's scroll bar triggers a click on component within the scroll view.

### Steps to Reproduce

1. Run RNTester Mac
2. Click on the scroll bar in the main list

### Expected Behavior

Allows me to scroll.

### Actual Behavior

Triggers a click on the row next to it. Note to make this easier to repro you can enable scroll bars to always show in macOS settings.

### Reproducible Demo

[Screen Recording 2020-10-02 at 2.48.52 PM.mov.zip](https://github.com/microsoft/react-native-macos/files/5320616/Screen.Recording.2020-10-02.at.2.48.52.PM.mov.zip)

**Comment by chrisglein** [comment]
The scroll indicator on iOS can't get a touch event, but on desktop it works differently. There's some assumption that's wrong in there because of that different. Scroll events yes, but not touch events (which this case are clicking the underneath list item and navigating to the next page).

**Comment by lyahdav** [comment]
I removed the stale label because I'm pretty sure this is still an issue

**Comment by Saadnajmi** [comment]
Yeah this is still an issue... and on my backlog.

**Comment by christophpurrer** [comment]
I think with https://github.com/microsoft/react-native-macos/pull/1281 we can close this issue now?
