### ISSUE TITLE
macOS Linking support

### ISSUE THREAD

**Issue by HeyImChris** [microsoft/react-native-macos#632]
Tracking support for macOS Linking ifdef'd out in code for now.

**Comment by chrisglein** [comment]
@HeyImChris Can you link the specific file? (or does that ifdef mention this issue number?)
Also, assuming we're talking about [Linking](https://reactnative.dev/docs/linking) and not autolinking. What's the timeline for re-enabling this?

**Comment by HeyImChris** [comment]
Fixed with with [PR](https://github.com/microsoft/react-native-macos/pull/633)
