### ISSUE TITLE
Flex doesn’t work

### ISSUE THREAD

**Issue by Jablett** [microsoft/react-native-macos#635]
Flex:1 doesn’t work with macOS

**Comment by chrisglein** [comment]
@Jablett Can you provide a standalone repro of what you're seeing?

**Comment by Luksys5** [comment]
It does for me.
Although sometimes you do need to make these actions to make it work
1. watchman watch-del-all
2. rm -rf node_modules && rm yarn.lock
3. yarn install 
4. yarn start --reset-cache

If that doesn't help try reloading the app few times...
If that doesn't help then good luck
