### ISSUE TITLE
Add a FocusZoneView component

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-macos#636]
# Proposal: Add a FocusZoneView component

## Summary

There are places in apps where it's useful to have keyboard arrow keys move focus instead of tab/shift, e.g. in lists. This issue proposes a FocusZoneView component for this.

## Basic example
Assume the FlatList renders buttons:
```
<FocusZoneView>
  <FlatList ... />
</FocusZoneView>
```

## Open Questions

I don't have time to make a PR for this, but here's a working implementation (be warned this is off an older RN Mac commit):
[FocusZoneView-Mac.zip](https://github.com/microsoft/react-native-macos/files/5418675/FocusZoneView-Mac.zip)

Note one thing this implementation doesn't support is the ability to remember the last focused component when focusing back on the focus zone. I hope to get to this in the next couple weeks and if so I'll update the link here.

**Comment by chrisglein** [comment]
Linking to [related issue](https://github.com/microsoft/react-native-windows/issues/6293) on React Native for Windows repo;

**Comment by Saadnajmi** [comment]
Well we have a FocusZone in FluentUI React Native that works pretty well. Is this still an ask? I was actually curious about that.

**Comment by lyahdav** [comment]
It's not an ask for us as we are using the one I linked above internally. Previously there was talk if we should have this in the React Native macOS repo, but I think having it in FluentUI is good enough.

**Comment by Saadnajmi** [comment]
OK! If you're ever curious, our Fluent FocusZone supports quite a few more props like bi-directional navigation and (somewhat) remembering what your last focused component was.
https://github.com/microsoft/fluentui-react-native/tree/master/packages/components/FocusZone
https://github.com/microsoft/fluentui-react-native/blob/master/apps/fluent-tester/src/FluentTester/TestComponents/FocusZone/FocusZoneTest.tsx (Test page of examples usage)
