### ISSUE TITLE
Reloading the app after changing Dark Mode state will revert the in-app setting to previous state.

### ISSUE THREAD

**Issue by alloy** [microsoft/react-native-macos#638]
1. Launch RNTester
1. Change Dark Mode state
1. Observe app correctly being updated
1. Open contextual dev menu and reload
1. Observe the app incorrectly reflecting Dark Mode state of when the app launched

**Comment by chrisglein** [comment]
This was supposed to be hooked up with `PlatformColor`, but there is another mechanism (RNTesterThemeContext?) that uses an event and says which style it is and choses a style sheet. So this probably _isn't_ a `PlatformColor` bug, but something that should for RNTester that should be using `PlatformColor` but isn't. If so, iOS may have this issue as well. @alloy have you been able to repro this not on mac?

**Comment by Saadnajmi** [comment]
Fixed by @chiuam recently, this can be closed
