### ISSUE TITLE
Touchables missing clicks when in titlebar

### ISSUE THREAD

**Issue by gorbypark** [microsoft/react-native-macos#643]
### Environment

1. `react-native -v`: 0.62.2
3. `npm ls react-native-macos`: react-native-macos@0.62.16
4. `node -v`: v12.19.0
5. `npm -v`: 6.14.8
6. `yarn --version`: 1.22.10
7. `xcodebuild -version`: Xcode 12.0.1 / Build version 12A7300

### Issue
In xcode, if you select "Hide Title Text" and "Transparent Titlebar", it's possible to position RN elements inside of the titlebar.  When doing so, click events on all Touchable components do not appear to propagate through to the clickable elements.  A `TextInput` components works properly capturing the focus.  I apologize in advance if this is a xcode configuration issue, as I'm quite new to anything native related.  I was inclined to believe it was my issue until I noticed that `TextInput` components worked as expected

### Steps to Reproduce
1. Open xcode project, select "Hide Title Text" and "Transparent Title Bar" from Attribution Inspector in Main.storyboard.
2.  Place elements at top of app

![Screen Shot 2020-10-30 at 8 46 42 PM](https://user-images.githubusercontent.com/19569469/97751140-1fa13b00-1af2-11eb-8dd7-6714ea681591.png)

### Expected Behavior
That the onPress would fire

### Actual Behavior
onPress callbacks are not fired, yet TextInput can capture focus
![2020-10-30 20 40 55](https://user-images.githubusercontent.com/19569469/97750873-de109000-1af1-11eb-952b-1e1d145cecbd.gif)
In the screenshot above, there's an `alert()` wired up to `onPress()`, which work as expected if a margin is placed so the buttons are pushed down below the tool bar.

### Additional context

I am not sure if this is the intended behaviour or not, or if there is something else required in xcode, but it would be nice to be able to make custom title bars with RNmacOS

**Comment by HeyImChris** [comment]
Can you confirm this is a React-Native specific issue and not a generic macOS issue?
