### ISSUE TITLE
TouchableOpacity outline.

### ISSUE THREAD

**Issue by antonioreyna** [microsoft/react-native-macos#644]
I am setting a button using TouchableOpacity and when i Press it, it keeps an outline.

How can i blur that selection?

<img width="153" alt="Captura de Pantalla 2020-11-03 a la(s) 4 45 24 a m" src="https://user-images.githubusercontent.com/147514/97975872-6495cd80-1d8f-11eb-98bf-8714ae1e943e.png">

**Comment by ospfranco** [comment]
Touchable opacity has a property (doesn't have typescript types though)
```javascript
// @ts-ignore
enableFocusRing={false}
```

**Comment by HeyImChris** [comment]
This is a view that can become first responder, therefore (depending on the system settings) it can have a focus ring. The prop Franco mentioned should allow one to toggle that prop.
