### ISSUE TITLE
How to execute subprocesses

### ISSUE THREAD

**Issue by ksurya** [microsoft/react-native-macos#646]
Does RN has API to run bash commands? 

I want to execute a command, retain its PID, kill it on button click, run on system start etc. 

What would your suggestion to do these? I guess some of this could be configured at LaunchAgents, but that would require the app write access to a plist file to ~/Library/LaunchAgents.

Related to: https://developer.apple.com/documentation/foundation/nstask

**Comment by HeyImChris** [comment]
We don't have this support. Anything file system access/shelling is outside the scope of React-Native-macOS. We welcome the community to implement third party modules to add new features. Please see our [wiki](https://github.com/microsoft/react-native-macos/wiki) for more info

**Comment by ksurya** [comment]
@chrisglein Yes, on the macOS.

**Comment by chrisglein** [comment]
> If RN cannot access file system to manage LaunchAgents, is there a way to run background subprocesses, schedule them?

This isn't something that RN core does, so that carries to macOS as well. The expectation is that you drop to native code for this. Unless there's a community module you're aware of that bundles that up? If so, exploring that for macOS would be interesting.

**Comment by chrisglein** [comment]
I _think_ the question has been answered here, so closing the issue.
