### ISSUE TITLE
0.63.2 is out, can you provide a migration guide?

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#673]
Or even better would be to add the documentation to the react-native-upgrade helper

https://react-native-community.github.io/upgrade-helper/?from=0.62.2&to=0.63.2

**Comment by ospfranco** [comment]
Until an official migration guide is provided, this are the steps I followed and I got my app running on the latest version, it is more than likely not complete... but hey, it's working

https://github.com/ospfranco/tempomat/commit/5aba474a58ad842261846c9c11dc7fbedda4f9b2

**Comment by Luksys5** [comment]
In case that dosn't work you can always:

delete macos folder together with node_modules and yarn.lock
change package.json react-native and react-native-versions 
yarn install
npx react-native-macos-init

That did work for me quite quickly
(Just be careful because it will remove macos pod data)

**Comment by chrisglein** [comment]
The out of tree platforms (e.g. macOS, Windows, and Web) are not part of the upgrade helper. Agreed it would be helpful to have solutions there (that's also been brought up on the [Windows repo](https://github.com/microsoft/react-native-windows/issues/3470)).

Outside of that it'd be good to have some sort of general guide on the [RN macOS website](https://microsoft.github.io/react-native-windows/docs/rnm-getting-started). Not that one exists ([that's been raised](https://github.com/microsoft/react-native-windows-samples/issues/258)), but I think that'd be a natural place for it.

Also it looks like the landing page for macOS on that website needs to be updated with the most recent version.

My instinct is to transfer this issue to the [website repo](https://github.com/microsoft/react-native-windows-samples) to capture that macOS is missing this. Thoughts?

**Comment by Saadnajmi** [comment]
Worth noting here that I believe macOS is now part of upgrade-helper!
