### ISSUE TITLE
Toxic community

### ISSUE THREAD

**Issue by OKNoah** [microsoft/react-native-macos#675]
https://github.com/microsoft/react-native-macos/issues/482#issuecomment-744004569

**Comment by chrisglein** [comment]
Regular issue triage was offline for the month of December, so this got missed for a bit. Apologies for letting this sit.
Note that this repo has a [code of conduct](https://github.com/microsoft/react-native-macos#code-of-conduct) which covers expectations and ways to act if there are sustained code of conduct issues (although it's expected that individuals try to work things out first). In the linked conversation thread there's a quick escalation on a closed issue. I wouldn't call it an ideal interaction, but I'm also not seeing a pattern of toxic community behavior. Closing this issue.
