### ISSUE TITLE
How to remove TextInput outline

### ISSUE THREAD

**Issue by JoshuaZacek** [microsoft/react-native-macos#680]
How does one remove the an outline from a TextInput component. I have tried `outline: 'none'` but that doesn't work.
![Screenshot 2020-12-26 at 19 58 24](https://user-images.githubusercontent.com/57673080/103158382-fd0b6580-47b4-11eb-9fa8-0bcb962b59f2.png)

My macOS version is 11.1
Big Sur

**Comment by JoshuaZacek** [comment]
Edited, sent wrong screenshot

**Comment by JoshuaZacek** [comment]
Oh figured out, you have to use `enableFocusRing={false}`

**Comment by HaddyYang** [comment]
enableFocusRing={false}  is not working

**Comment by bongani-m** [comment]
> enableFocusRing={false} is not working

same here.  I haven't been able to get it to work.

**Comment by HaddyYang** [comment]
@JoshuaZacek @bongani-m I did it! 
Change the file: **node_modules/react-native-macos/Libraries/Text/TextInput/Singleline/RCTUITextField.m**
Add one line code at last: **[self setFocusRingType:NSFocusRingTypeNone];** into **initWithFrame** function.
