### ISSUE TITLE
Getting NSBeep feedback on every keystroke when entering text into the standard TextInput component

### ISSUE THREAD

**Issue by vincentriemer** [microsoft/react-native-macos#683]
### Environment

1. `react-native -v`: N/A (master)
3. `npm ls react-native-macos`:
```
react-native-macos@1000.0.0 /Users/vincentriemer/Workspace/react-native-macos
└── (empty)
```
4. `node -v`: `v14.15.3`
5. `npm -v`: `6.14.9`
6. `yarn --version`: `1.22.5`
7. `xcodebuild -version`:
```
Xcode 12.3
Build version 12C33
```
8. MacOS version: 11.1

### Issue

Ever since I upgraded react-native-macos to 0.63.4 I noticed that I've been getting NSBeep (I think that's where it comes from) audio feedback for every keystroke — most notably when entering text into a `TextInput` component.

### Steps to Reproduce

1. Checkout the master branch of `react-native-macos` & perform the standard instructions detailed in the repo's "Contributing Guidelines" in order to build RNTester.
2. Build & launch RNTester
3. Navigate to the TextInput section
4. Enter text into any TextInput instance present.

### Expected Behavior

The text should properly be entered without any extra audio feedback.

### Actual Behavior

There's a "beep" (from my brief research it comes from the NSBeep class) on every keystroke.

### Reproducible Demo

I've been able to reproduce on the latest master branch of `react-native-macos`'s RNTester project.

**Comment by ospfranco** [comment]
This is only happening on development builds for me, once the app is packaged it works fine

**Comment by chrisglein** [comment]
There was a change to expand keyboard accessibility that may have caused a side effect here. The timeline could line up. @HeyImChris can you link the PR for that?

**Comment by HeyImChris** [comment]
Yea this seems related to this [keyboard support](https://github.com/microsoft/react-native-macos/pull/657) fix made back in mid December
