### ISSUE TITLE
React Native MacOS Snapshot/Screenshot

### ISSUE THREAD

**Issue by oguzsh** [microsoft/react-native-macos#684]
# Proposal:
 React Native MacOS Snapshot/Screenshot 

## Motivation
I think this package should be on the macOS side. In this way, it will be easy for us to develop monitoring apps.
[React Native View Shot](https://github.com/gre/react-native-view-shot)

## Open Questions
Do you have this feature on this repo? If yes, please write documentation for how to use X native component 😢

**Comment by chrisglein** [comment]
@oguzsh There's a template to request macOS support to a community module from the "new issue" menu: https://github.com/microsoft/react-native-macos/issues/new/choose
In that there are some additional details asked about what you might need from the module. At the end of the day that work will happen on that repo, not this one. Although it can be handy to track what people are looking for for macOS.
Can you provide that extra detail?

> Do you have this feature on this repo?

Nope, it'd need to be added to [the module's repo](https://github.com/gre/react-native-view-shot)

**Comment by oguzsh** [comment]
@chrisglein  - >  Can you provide that extra detail?

I mean, developers create time tracking apps and these apps have a screenshot feature. Like the Desktime. If you activate, the DeskTime will get a screenshot every 10 minutes and save it on the company dashboard.

Example :
![image](https://user-images.githubusercontent.com/15168877/105222463-925b0900-5b6b-11eb-855e-e1c0ac73f9b3.png)

**Comment by chrisglein** [comment]
@oguzsh Thanks for the context. Did you open an issue against that repo?

**Comment by oguzsh** [comment]
Hi! 
Any update on this issue?

**Comment by HeyImChris** [comment]
> Hi!
> Any update on this issue?

This is the screenshot test page in RNTester in rn-macos. Does this do what you want?

<img width="752" alt="rn-macos_screenshot" src="https://user-images.githubusercontent.com/48299693/128384357-3eb29779-e4e1-4867-89c0-99cbca02e12f.png">

**Comment by oguzsh** [comment]
That's exactly what I need but I can't integrate this module on my rn-macOS project. Is there any documentation for how can I integrate this module into a project?

**Comment by HeyImChris** [comment]
> That's exactly what I need but I can't integrate this module on my rn-macOS project. Is there any documentation for how can I integrate this module into a project?

Integration should be the same for this module as it would be for any module in React-Native iOS (or macOS) which is [documented](https://reactnative.dev/docs/native-modules-ios) pretty well. If you'd like an actual example of the Snapshot being used in JS, you can see how the RNTester test app uses it [here](https://github.com/microsoft/react-native-macos/blob/master/RNTester/js/examples/Snapshot/SnapshotExample.js).

**Comment by oguzsh** [comment]
Ahh that's right! Thanks for your help! We can close this issue anymore :D
