### ISSUE TITLE
Keyboard event inconsistencies with react-native-windows

### ISSUE THREAD

**Issue by appden** [microsoft/react-native-macos#702]
### Issue

The new keyboard events added in #657 has some inconsistencies with the corresponding `IKeyboardEvent` type in `react-native-windows` along with the [Keyboarding API Proposal](https://github.com/microsoft/react-native-windows/blob/master/vnext/proposals/active/keyboard-reconcile-desktop.md).

Some examples:
- `controlKey` instead of `ctrlKey`
- `optionKey` instead of `altKey`
- `commandKey` instead of `metaKey`
- `leftArrowKey` instead of `key == 'ArrowLeft'`

It would be great to get the modifier keys aligned across platforms, especially since the correct ones are already used for mouse events, and it would be especially nice to provide the "virtual key" strings for arrow keys, enter key, etc. ([see here](https://github.com/microsoft/react-native-windows/blob/master/vnext/Microsoft.ReactNative/Views/KeyboardEventHandler.cpp#L259-L271
) in RNW)

### Steps to Reproduce

Add `onKeyDown`/`onKeyUp` events and log their `nativeEvent` property.

### Expected Behavior

Align as much as possible with `react-native-windows` and the [Keyboarding API Proposal](https://github.com/microsoft/react-native-windows/blob/master/vnext/proposals/active/keyboard-reconcile-desktop.md)

**Comment by jacobp100** [comment]
It looks like the Windows version conforms closer to the W3C spec https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent

**Comment by HeyImChris** [comment]
Thanks for filling this. It's definitely a bug on our end and I've gotten reports from some other React-Native clients about this as well- we'll look into fixing it soon.
