### ISSUE TITLE
Which one is the latest release?

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#703]
Heyo, I was using the 0.63.X release on my branch, but new commits are being released under the 0.62.X branch

https://github.com/microsoft/react-native-macos/releases

is this intended?

**Comment by HeyImChris** [comment]
Yes it's intentional. We needed some fixes in the 0.62-stable branch for some downstream dependencies still on 62. 0.63 is still the latest release version to use.

**Comment by ospfranco** [comment]
ok, thanks for the reply!
