### ISSUE TITLE
FlatList does not animate when running `scrollToIndex({..., animate: true})`

### ISSUE THREAD

**Issue by geekster777** [microsoft/react-native-macos#706]
FlatList does not animate when scrolling to an index using `FlatList.scrollToIndex({..., animate: true})`.

Based on these lines, it looks like this may be an issue with all ScrollView scrollTo* functions on mac:
https://github.com/microsoft/react-native-macos/blob/master/React/Views/ScrollView/RCTScrollView.m#L718-L719

**Comment by chrisglein** [comment]
Looking at the code it appears this just sets the value instead of animating it. So this is not yet implemented.
