### ISSUE TITLE
Support react-native-Zerconf bonjour services

### ISSUE THREAD

**Issue by elmcapp** [microsoft/react-native-macos#726]
Like to know if you can create a module for network discovery service. This would be good as it will allow use to develop desktop app that need to find a printer, or other services that my be on the network. I am requesting to make a bonjour service or Zeroconf module. Any example can be found at this link however it works for electron apps and I can't get working with React Native macOS. 
https://www.npmjs.com/package/bonjour

I am trying to target React-native-macOS v 0.62 or and 0.63

The module is use to get services on the local network. Bonjour service or Zeroconf

**Comment by chrisglein** [comment]
There's an issue template for making a module request, and that includes some extra info. I've pasted that below. Can you fill that out?

That said, if bonjour is inactive it may be hard to get support to accept a PR there.



# Support `react-native-foo` on React Native for macOS


## Basic Info
- Module Repo URL: [link to repo]()
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())
If the community module repo already has an issue tracking adding React Native Support, please check this box and link to it.

## Which app/customer is requesting this module?
Please describe which app/customer needs this module.

## In what scenarios will this module be used?
Please detail how the app/customer will use the module. Please include screenshots/mockups/wireframes if possible. 

## Essential Features
Please enumerate which features of the module are required. For example, you may be using a map module and you only need the 'pinning' functionality and NOT the turn-by-turn direction functionality.
