### ISSUE TITLE
Trying to use npm modules are not working

### ISSUE THREAD

**Issue by elmcapp** [microsoft/react-native-macos#727]
I am trying to use a npm module called bonjour and zeroconf which provide network discovery services.  https://www.npmjs.com/package/bonjour
https://www.npmjs.com/package/react-native-zeroconf

Both of these modules worked if I am using a plain Electron app or react native app. however when I try to use with react native for macOS none of these modules work.  I can't provide an exact error message because the errors message always change. Again it works with react native mobile apps using react native versions 0.59 to 0.62 and 0.63

like to know if something can be done to use addition libraries with react native macOS

**Comment by chrisglein** [comment]
Native modules don't support macOS without explicitly adding support for them (unlike Android/iOS). The bonjour package doesn't appear to have been updated in the last 5 years, so there's no way it has react-native-macos support. And looking at zeroconf it also doesn't have macOS support. So your path forward here would be to work with those module owners to add macOS support.
