### ISSUE TITLE
Change C++ TurboModule/NativeModule namespace shared with RNW away from "winrt"

### ISSUE THREAD

**Issue by appden** [microsoft/react-native-macos#732]
This API was integrated starting in #595 with the aspiration that this can be contributed upstream, but it still used the `winrt::Microsoft::ReactNative` namespace. In preparation for contributing upstream, it would be really nice to adjust the namespace to at least not have `winrt` since it's the API is not specific to Windows anymore. 😀

**Comment by HeyImChris** [comment]
Agreed! We shouldn't have any win specific types on macOS or iOS. This should definitely get fixed before it's contributed upstream.

**Comment by chrisglein** [comment]
@ZihanChen-MSFT Tagging you so you see this but I don't think there's an immediate action needed so unassigning you.
