### ISSUE TITLE
Empty object logging/using Native Modules

### ISSUE THREAD

**Issue by matheusmarranebairesdev** [microsoft/react-native-macos#749]
### Environment

1. `react-native -v`: 4.14.0
3. `npm ls react-native-macos`:  react-native-macos@0.63.23
4. `node -v`:v14.15.4
5. `npm -v`:7.6.1
6. `yarn --version`:1.22.10
7. `xcodebuild -version`:
Xcode 12.4
Build version 12D4e

### Issue

I created one Native Module but it isn't exposed to JS (I followed the iOS docs on RN website, cause we don't have docs to do that to macOS)

### Steps to Reproduce

1. [Create Header File ](https://reactnative.dev/docs/0.63/native-modules-ios#create-custom-native-module-files)
2. [Create Module](https://reactnative.dev/docs/0.63/native-modules-ios#module-name)
3. import the Native Modules on JS and console.log it.

### Expected Behavior

The Native Module should appear

### Actual Behavior

the log shows an empty object `{}`

### Reproducible Demo

./macos/<project>-macOS/RCTAudioToolbox.h
```
#import <Foundation/Foundation.h>
#import <React/RCTBridgeModule.h>

NS_ASSUME_NONNULL_BEGIN

@interface RCTAudioToolbox : NSObject <RCTBridgeModule>

@end

NS_ASSUME_NONNULL_END
```
./macos/<project>-macOS/RCTAudioToolbox.m (added to sound-macOS target)
```
#import "RCTAudioToolbox.h"

@implementation RCTAudioToolbox
RCT_EXPORT_MODULE();
@end
```

./App.js
```
import React, {useEffect} from 'react';
import {NativeModules} from 'react-native';

const App: () => React$Node = () => {
  useEffect(() => {
    console.log(NativeModules);
  }, []);
  return <></>;
};

export default App;

```

**Comment by chrisglein** [comment]
At first glance these steps seem correct. Will need someone to run through the steps to see if something is being missed (Which is understandable because as you said the steps aren't documented for macOS - [see issues like this one](https://github.com/microsoft/react-native-windows-samples/issues/159)).
