### ISSUE TITLE
 Support react-native-video on Mac

### ISSUE THREAD

**Issue by dingbo8128** [microsoft/react-native-macos#753]
# Support `react-native-video` on React Native for macOS

## Basic Info
- Module Repo URL: [https://github.com/react-native-video/react-native-video]()
- Target version: 0.61
- [ ] Issue exists on module repo (if so, [link]())

## Which app/customer is requesting this module?
Zion锡安 for macos

## In what scenarios will this module be used?
play videos from URL

## Essential Features
1. play video from .m3u8 URL
2. full screen 
3. repeat the video when the end is reached (support repeat prop)
4. show control buttons (support controls prop)

**Comment by chrisglein** [comment]
@dingbo8128 Can you fill out this information?

```
<!-- This Issue template helps us track which modules need to work with React Native for macOS. If you have found a community module that doesn't yet work with React Native for macOS, fill out the Issue fields below! -->

# Support `react-native-foo` on React Native for macOS
<!-- Update the react-native-foo text with the module name -->

## Basic Info
- Module Repo URL: [link to repo]()
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())
<!-- If the community module repo already has an issue tracking adding React Native Support, please check this box and link to it. -->

## Which app/customer is requesting this module?
<!-- Please describe which app/customer needs this module. -->

## In what scenarios will this module be used?
<!-- Please detail how the app/customer will use the module. Please include screenshots/mockups/wireframes if possible. -->

## Essential Features
<!-- Please enumerate which features of the module are required. For example, you may be using a map module and you only need the 'pinning' functionality and NOT the turn-by-turn direction functionality.  -->
```

**Comment by enigmablue** [comment]
# Support `react-native-foo` on React Native for macOS


## Basic Info
- Module Repo URL: [react-native-video](https://github.com/react-native-video/react-native-video)
- Target version: 
- [ ] Issue exists on module repo (if so, [link]())


## Which app/customer is requesting this module?
react-native-video

## In what scenarios will this module be used?
Need to display videos on the mobile application

## Essential Features
Just need to be able to play videos! Currently getting error on the RCTVideoInstance when trying. But there is no installation instructions eg on react-native-video for macos

related

https://github.com/react-native-video/react-native-video/issues/2027

**Comment by enigmablue** [comment]
Wondering if we could get this prioritized as there are no alternatives i think for getting videos to work on macos :/
So am kind of stuck on getting a mac app setup

**Comment by chrisglein** [comment]
> Wondering if we could get this prioritized as there are no alternatives i think for getting videos to work on macos :/
> So am kind of stuck on getting a mac app setup

For transparency, the template to request community module implementations is largely intended to track relative interest (there are [almost 1000](https://reactnative.directory/) modules out there) and provide a place for potential macOS implementers to communicate intent (as each of those module repos are unique and have different rules). But there is no dedicated team to go through and implement them - it's a bit more organic than that.

Which is to say, I think this one is open to jump on if you want to try adapting the iOS implementation. Agreed that `react-native-video` is one of the more requested modules.

**Comment by MuhammadBilal164** [comment]
You need to create a native module for this, currently there is no option to play video in react native macOS
