### ISSUE TITLE
Hit test is broken on Text screen in RNTester app

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-macos#754]
### Environment

1. `react-native -v`: I'm on this commit:
```
commit 5a3ee83efeec124b3aedbcccc90f2a878b75917e (HEAD -> master, origin/master, origin/HEAD)
Author: Saad Najmi <saadnajmi2@gmail.com>
Date:   Wed Mar 31 23:18:16 2021 -0500
```
3. `npm ls react-native-macos`: `(empty)`
4. `node -v`: `v12.14.1`
5. `npm -v`: `6.13.4`
6. `yarn --version`: `1.21.1`
7. `xcodebuild -version`:
```
Xcode 12.4
Build version 12D4e
```

### Issue
When I run RNTester on Mac and go to Text examples, if I right click on the selectable text example, it will only show the correct context menu if I click within the top few pixels of the component.

### Steps to Reproduce

1. Clone repo
2. Run RNTester Mac
3. Go to Text example
4. Scroll to selectable text
5. Click and hold to select the text
6. Right click on the lower half of the text

### Expected Behavior

Context menu with copy should show.

### Actual Behavior

RN Context menu shows.

### Reproducible Demo

The first click in this video is on top half (works fine), second click is bottom half (bug).

https://user-images.githubusercontent.com/359157/113638221-36146b00-962b-11eb-8a26-48e8c10ad18e.mov

### Additional context

The bug is due to this line: https://github.com/microsoft/react-native-macos/blob/master/RNTester/js/components/RNTesterPage.js#L72
If I delete it, everything works fine. It seems that setting a `paddingTop` on `ScrollView` breaks hit tests.

**Comment by chrisglein** [comment]
Commit that added the `paddingTop` is... not recent (6 years ago). Does this repro on older versions (you listed a specific commit) too?
Any downside to removing that padding? What's the deeper issue?

**Comment by lyahdav** [comment]
I'm not sure if it repros on older versions but I'm guessing it does given that commit is so old (don't have time to verify now). I couldn't find any downsides to removing the padding. I believe the deeper issue is that setting `paddingTop` on `ScrollView` doesn't set the padding on the ScrollView's content view.

**Comment by Saadnajmi** [comment]
It sounds like this year old issue has a fix on your local fork @lyahdav ?

**Comment by lyahdav** [comment]
@saadnajmi yes, in our fork we just deleted that paddingTop. You can see that in the change to [RNTesterPage.js here](https://github.com/christophpurrer/react-native-macos/commit/bba86a3fe1ff4285873dbc95c3f12e3dc63fe99f#diff-3dba1c0dd8be70f7b4647c30df936807e274f5bccf4c124a1f882449167d5f1e). Just one of many changes we haven't had time to contribute back yet.

**Comment by christophpurrer** [comment]
I am not able to repro this problem with react-native-macOS 0.68-stable/main at this point
(3b1f575937d798d127f1b39d995a041dd14b197b)
Hence I recommend to close this issue.

Removing ```paddingTop: 10,``` in RNTesterPage.js is not necessary anymore

https://user-images.githubusercontent.com/484044/183130630-247bd6f1-0780-4528-91e9-ff931f03a0fa.mov

**Comment by christophpurrer** [comment]
Great!
