### ISSUE TITLE
Switch component has incorrect dimensions on macOS

### ISSUE THREAD

**Issue by mlalkaka** [microsoft/react-native-macos#757]
### Environment

6. `yarn --version`: 1.17.0-20190429.1820
7. `xcodebuild -version`: Xcode 12.4 (Build version 12D4e)

### Issue

The dimensions of the Switch component, which renders as a checkbox, is incorrect on macOS. It looks like the dimensions are set to something more like a toggle control would be. See the example below, as well as the likely cause of the issue.

### Steps to Reproduce

1. Use the example below to view the dimensions of the Switch component, or use the Inspector.

### Expected Behavior

![image](https://user-images.githubusercontent.com/11790481/114938637-33b4cc80-9df4-11eb-938b-f78813b28130.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/11790481/114938328-d7ea4380-9df3-11eb-9ab0-bc21ab50afe1.png)

### Reproducible Demo

```jsx
// This example renders a red border around the checkbox/switch to make it easier to view the dimensions.
export default function Example() {
  return (
    <View style={styles.borderContainer}>
      <View style={styles.border}>
        <ArchonSwitch />
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  borderContainer: {
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
  },
  border: {
    borderWidth: 1,
    borderColor: 'red',
  },
});
```

### Additional context

It looks like it is being caused by [this line](https://github.com/microsoft/react-native-macos/blob/master/Libraries/Components/Switch/Switch.js?fbclid=IwAR1qkI4sHf2YiLd7vw6Id0AQz-_xHPyChRZBwyijTWTpyAuBxKmxeWk_tV4#L147).

**Comment by HeyImChris** [comment]
Thanks for filing this! My guess is it's the correct size for the wider iOS switches but when the cross-plat code was brought over to macOS it didn't take into consideration the fact that macOS switches are narrower.

**Comment by HeyImChris** [comment]
Using keyboard navigation, the blue ring does appear to size to the correct control as it appears to go off of the NSButtonImageView (which is the actual checkbox we see), whereas the RCTSwitch itself it the bigger superview that shouldn't be hardcoded this wide.

**Comment by mlalkaka** [comment]
Thanks for following up!

> ... the RCTSwitch itself is the bigger superview that shouldn't be hardcoded this wide.

Isn't it just [this line in Switch.js](https://github.com/microsoft/react-native-macos/blob/master/Libraries/Components/Switch/Switch.js?fbclid=IwAR1qkI4sHf2YiLd7vw6Id0AQz-_xHPyChRZBwyijTWTpyAuBxKmxeWk_tV4#L147) that's causing the problem?

**Comment by Saadnajmi** [comment]
On 0.66, the switch is actually a switch, not a checkbox. So this should be fixed.

**Comment by christophpurrer** [comment]
Since we have a NSSwitch support in macOS 10.15/run-macOS 0.66 -> should we close this issue now?

**Comment by amerllica** [comment]
Sorry, but does anyone know how to toggle the `Inspector` hide/show? What's the shortcut key or keys?

**Comment by Saadnajmi** [comment]
Right click to get the dev menu?
