### ISSUE TITLE
Poistioning/Animations broken (ActivityIndicator of react-native-paper)

### ISSUE THREAD

**Issue by nikgraf** [microsoft/react-native-macos#767]
### Environment

1. `react-native -v`: says unknown option -v?
3. `npm ls react-native-macos`: react-native-macos@0.63.28 
4. `node -v`: v14.15.1
5. `npm -v`: 6.14.8
6. `yarn --version`: 1.22.10
7. `xcodebuild -version`: Xcode 12.5

### Issue

When adding the ActivityIndicator from react-native-paper it seems like the positioning/animation is broken.

### Steps to Reproduce
 
This is the commit: https://github.com/nikgraf/alpine/commit/2ecaf8fc88a3191c2ace9c66b9f927f2a2b9a4f9

### Expected Behavior

Should look like this:

![](https://callstack.github.io/react-native-paper/screenshots/activity-indicator.gif)

### Actual Behavior

This is how it looks like:

https://user-images.githubusercontent.com/223045/117546238-b31b7180-b029-11eb-8fc3-6d054996ec53.mov

### Reproducible Demo

Here is a minimal reproducible repo: https://github.com/nikgraf/alpine/tree/animation-bug with the commit I mentioned

**Comment by chrisglein** [comment]
Thanks for the clear video and the min repo!
There is the built in [ActivityIndicator](https://reactnative.dev/docs/activityindicator), which should work if you're willing to do a PlatformSelect for macOS. I don't think anyone has done work to validate [react-native-paper's ActivityIndicator](https://callstack.github.io/react-native-paper/activity-indicator.html) on macOS (or any of the rest of paper? it isn't listed in the [directory](https://reactnative.directory/?search=paper) as supporting macOS).

However if the animations are broken like this and the module is implementing this in pure JS, that indicates a problem in RN macOS... somewhere.

**Comment by chrisglein** [comment]
Confirmed that the default activity indicator works fine.
The bug here may be related to setting an anchor point for rotation animations.

**Comment by Saadnajmi** [comment]
> Confirmed that the default activity indicator works fine.
> The bug here may be related to setting an anchor point for rotation animations.

That could be possible. It could be because macOS might use a slightly different coordinate system?

**Comment by Saadnajmi** [comment]
This was fixed

**Comment by nikgraf** [comment]
awesome 👍
