### ISSUE TITLE
Hermes won't build on M1 Mac

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-macos#781]
### Environment

1. `react-native -v`
3. `npm ls react-native-macos`: 
4. `node -v`: v12.21.0
5. `npm -v`: 6.14.11
6. `yarn --version`: 1.22.10
7. `xcodebuild -version`: Xcode 12.4 Build version 12D4e

### Issue

If you try to build RNTester-macOS on an M1 Mac with hermes enabled, it fails. You have to keep hermes disabled in the pod file to build RNTester-macOS on an M1 Mac.

### Steps To Reproduce

1. Clone the react-native-macos repo (https://github.com/microsoft/react-native-macos)
2. Setup RNTester & open Xcode project (`yarn && cd RNTester && pod install && open RNTesterPods.xcworkspace`)
3. Try to build RNTester-macOS for Target "My Mac" (in my case it's am M1 Mac mini)

### The Expected Behavior

It builds successfully

### Actual Behavior

Several Errors:

![Screen Shot 2021-05-06 at 2 37 13 PM](https://user-images.githubusercontent.com/6722175/119443701-a5374300-bcef-11eb-9fd0-b1ce570ab202.png)

**Comment by Saadnajmi** [comment]
Looks like this will be fixed by https://github.com/facebook/hermes/pull/475 =)

**Comment by chrisglein** [comment]
@kelset A little bird told me you maybe knew of a workaround for this? If so, share it here.

But based on the previous comment it seems like this fixed with a newer version of Hermes, so this will be naturally resolved. @Saadnajmi does that work for you?

**Comment by Saadnajmi** [comment]
@chrisglein yeah, that's fine! It's not an actual issue for me I just wanted to make sure it was tracked. Looks like Hermes is directly tracking so we can close this.
