### ISSUE TITLE
<Pressable/> missing

### ISSUE THREAD

**Issue by scarlac** [microsoft/react-native-macos#796]
# Proposal: Add support for Pressable

## Summary
It isn't clear that `<Pressable />` is missing from react-native-macos.

From node_modules/react-native:
<img width="400" alt="Screen Shot 2021-06-26 at 17 45 41" src="https://user-images.githubusercontent.com/895369/123529557-55f58100-d6a6-11eb-8708-3f4fb239f35f.png">

From node_modules/react-native-macos:
<img width="433" alt="Screen Shot 2021-06-26 at 17 44 54" src="https://user-images.githubusercontent.com/895369/123529551-4118ed80-d6a6-11eb-9913-9d30f248b679.png">

From node_modules/react-native-windows:
<img width="425" alt="Screen Shot 2021-06-26 at 17 47 30" src="https://user-images.githubusercontent.com/895369/123529589-9ce37680-d6a6-11eb-9651-f2bd22b0fe05.png">

## Motivation
Given RN's push to use this component over Touchable* it seems relevant to include it, perhaps even supporting the hover style functionality. E.g. it would be neat if you could do: `<Pressable style={({ hovering }) => styles.hover } />`

## Basic example

```jsx
<Pressable><Text>Hello world</Text></Pressable>
```
and for hover support:
```jsx
<Pressable style={({ hovering }) => styles.hover }>
<Text>Hello world</Text>
</Pressable>
```

**Comment by HeyImChris** [comment]
The Pressable component lives [here in react-native-macos](https://github.com/microsoft/react-native-macos/blob/master/Libraries/Components/Pressable/Pressable.js), but there hasn't been specific work to cater this control to macOS (e.g. adding hover effects). It's a great point though that having desktop functionality could come in handy.

Can you post the repro steps for how you're generating the node_modules folder in the screenshots for your react-native-macOS project above? It sounds like there are two issues you mention here- one is you're not seeing any Pressable component at all for react-native-macOS when you make a new project and two is you'd like more desktop support built into the component. Does that summarize it or did I misunderstand something?

**Comment by scarlac** [comment]
I followed the exact steps from the "getting started" guide for macOS. I haven't modified my node modules manually. I did add typescript support but i don't see how it relates.

Other yes, that summarizes it. I was really most interested in the Pressable component missing.
