### ISSUE TITLE
Support expo

### ISSUE THREAD

**Issue by haveamission** [microsoft/react-native-macos#800]
# Support `expo` on React Native for macOS

## Basic Info
- Module Repo URL: https://expo.io/

**Comment by VaarunSinha** [comment]
Will expo be supported?

**Comment by algoflows** [comment]
What happened to this, can we use this expo?

**Comment by haveamission** [comment]
I think there's a way to do Electron on Expo and use that to build a desktop native app, but that's obviously inferior to native deployment.

I don't believe anyone has made any major progress on this
