### ISSUE TITLE
After resized window in other screen, when navigate to the old screen, it shows empty view. (Using React-Navigation/bottom-tabs).

### ISSUE THREAD

**Issue by wzbwan** [microsoft/react-native-macos#817]
### Environment

1. `react-native -v`: 0.63.0
3. `npm ls react-native-macos`: 0.63.37
4. `node -v`: v14.16.1
5. `npm -v`: v6.14.12
6. `yarn --version`: v1.22.4
7. `xcodebuild -version`: v12.5.1

### Issue
![Kapture 2021-08-24 at 14 16 56](https://user-images.githubusercontent.com/4313235/130565966-af6934b2-cd17-469f-bab0-25a4a3c24b9e.gif)

### Steps to Reproduce

The React Navigation has run perfect so far, but when I resize the window, I found that other  tab will show an empty view, and when I resize again the content will appear, but other tabs will disappear. Like the GIF shows. 

I don't know what was happen when resizing the window.

Hope anyone could help me out, Thanks!😁

Is it a bug or I used it in a wrong way?

**Comment by nikgraf** [comment]
I ran into the same issue and reported it here https://github.com/react-navigation/react-navigation/issues/9889

**Comment by nikgraf** [comment]
I solved the issue and opened a PR which got merged and released. We can close this issue.

**Comment by Saadnajmi** [comment]
@nikgraf just curious, what PR did you submit to solve the issue?
