### ISSUE TITLE
Password bullets disappear when out of focus (only in Dark mode)

### ISSUE THREAD

**Issue by mayyaab** [microsoft/react-native-macos#820]
### Environment

1. `react-native -v`:  0.64.1
3. `npm ls react-native-macos`: 0.63.0-0
4. `node -v`:v14.17.3
5. `npm -v`: 6.14.13
6. `yarn --version`: 1.22.10
7. `xcodebuild -version`:Xcode 12.5.1
Build version 12E507

### Issue

Password bullets are disappears when out of focus (only in Dark mode)

### Steps to Reproduce

```
const style = StyleSheet.create({
 input: {
    marginTop: 16,
    height: 40,
    width: 400,
    borderWidth: 1,
    borderRadius: 12,
    padding: 10,
    borderColor: colors.innerBorder,
    color: colors.plainBlack,
  },})

<TextInput
          style={style.input}
          secureTextEntry={true}
          onChangeText={(text) => setUserPassword(text)}
        />

```

1. Change System preferences -> General -> Appearance in Dark mode
2. Open your application
3. Type password in the TextInput 
<img width="853" alt="Screen Shot 2021-08-26 at 11 00 20 AM" src="https://user-images.githubusercontent.com/41024017/131013882-42eee9bd-d6b8-41ce-9f51-5443919b28a1.png">
4. Click on the first TextInput (email text input)

### Expected Behavior

Bullets not disappeared

### Actual Behavior

Observe that bullets disappeared
<img width="841" alt="Screen Shot 2021-08-26 at 11 00 11 AM" src="https://user-images.githubusercontent.com/41024017/131014001-251e5459-b964-491c-8c42-1d03bb137440.png">

### Additional context

Reproducible only in **Dark** mode for **TextInput** with **secureTextEntry={true}**

**Comment by chrisglein** [comment]
You have a color overridden here:
```js
    borderColor: colors.innerBorder,
    color: colors.plainBlack,
```
Does it repro without that set?

Also a bit confused because you mention dark mode but the screenshot is definitely not dark mode. Looks pure white. But the guess is that you're getting white bullets on a white background and that's the problem.

Are you using `PlatformColor` for any of this?

**Comment by mayyaab** [comment]
@chrisglein,

This is a screen with a dark mode.

The problem is that when TextInput is in focus the color is correct:
<img width="592" alt="Screen Shot 2021-09-14 at 4 08 42 PM" src="https://user-images.githubusercontent.com/41024017/133345568-298ec08f-f39e-4b13-9d73-e27c5236b94f.png">
But when the TextInput is out of focus the color resets to default (white) 
<img width="592" alt="Screen Shot 2021-09-14 at 4 08 45 PM" src="https://user-images.githubusercontent.com/41024017/133345644-39eb3bda-472e-48b3-bc9e-0fc79a1eaaa7.png">


This problem is reproducible only for bullets `secureTextEntry={true}`

**Comment by jbcullis** [comment]
We have the same issue.

**Comment by rafi16jan** [comment]
We also have the same issue

**Comment by rafi16jan** [comment]
Ugly solution but works

```javascript
const Text = require('react-native').Text;
const TextInput = require('react-native').TextInput;

if (require('react-native').Platform.OS == 'macos') {
  const originalRender = TextInput.render;
  const render = function render(props) {
    const override = {};
    const [value, setValue] = React.useState(() => props.value || '');
    if (props.secureTextEntry) {
      override.secureTextEntry = false;
      override.value = [...Array((value || '').length).keys()].map(() => '●').join('');
      override.onChangeText = (newValue) => {
        if (newValue.length > value.length) newValue = value + newValue.slice(value.length, newValue.length);
        else if (newValue.length < value.length) newValue = value.slice(0, newValue.length);
        setValue(newValue);
        if (props.onChangeText) props.onChangeText(newValue);
      }
      if (value) override.marginTop = (props.marginTop || 0) - 2;
    }
    return originalRender.bind(this)({...props, ...override});
  }
  require('react-native').TextInput.render = render;
}
```
