### ISSUE TITLE
Component shadows do not always applies in 0.63.37

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-macos#824]
### Environment
react-native -v: 0.63.4
npm ls react-native-macos: 0.63.37
node -v: 15.14.0
npm -v: 7.7.8
yarn --version: -
xcodebuild -version: 12.5.1

### Issue
Component shadows will not be visible half of the time starting the app

### Steps to Reproduce
1. Init a new project using the docs
2. Add a view component with shadow property
```
const App = () => {
  return (
    <>
      <View style={s.view}>
        <View style={s.shadow} />
      </View>
    </>
  );
};

const s = StyleSheet.create({
  view: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  viewWithShadow: {
    width: 200,
    height: 100,
    backgroundColor: 'blue',
    shadowRadius: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.6,
    shadowOffset: {
      height: 6,
      width: 0,
    },
  },
});
```
3. Either build the app using development mode or production mode
4. Start the app multiple times and watch the shadow not working about half of the time

### Expected Behavior
Shadows always being applied

### Actual Behavior
Shadows only being applied 50% of the time

**Comment by chrisglein** [comment]
@hawkmeister Since you're seeing this on latest by chance do you know if this was reproducing previously? Looking to see if this is a regression or not. Given the lack of consistency maybe it was broken earlier and got missed.

**Comment by k1mmm** [comment]
@chrisglein This seems to be working as intended on 62, so looks like regression

**Comment by k1mmm** [comment]
Can confirm this is still an issue in 0.66.58, but my previous comment about creating a custom NSEffectView with shadow do no longer applies, this works.

**Comment by Saadnajmi** [comment]
Yeah, this bug is on our radar that the shadow props don't always render a shadow. I _think_ I know the root cause on the native side.

**Comment by appden** [comment]
cc @lyahdav – I left a possible fix for this on our internal fork

**Comment by Saadnajmi** [comment]
This should show up when we release React Native macOS 0.70
