### ISSUE TITLE
process.env Support

### ISSUE THREAD

**Issue by ericvicenti** [microsoft/react-native-macos#904]
### Summary

In my App I need to know the User's home directory, usually stored in $HOME

But `process.env` is basically empty in RN-MacOS

### Motivation

I expect process.env to work in a framework like RN-MacOS. Otherwise, how would I be able to determine the user's name and home dir location?

### Basic Example

When I render `{JSON.stringify(process.env)}` in my App.js, it prints `{"NODE_ENV":"development"}`

**Comment by Saadnajmi** [comment]
I think this is an issue with node.js ? If you use the same API outside of React Native on macOS, do you get a useful return?

**Comment by ericvicenti** [comment]
NodeJS always has the process.env set. (That is why I expect it to work)

To test on your terminal: `node -e "console.log(JSON.stringify(process.env))"`

**Comment by ericvicenti** [comment]
Is there any workaround to determine the user's home directory? Right now, that is the only env variable I need 🤷‍♂️

**Comment by acoates-ms** [comment]
process is a node object.  Its not something available in react-native - on any platform.

I assume it would be relatively trivial to write a nativemodule to provide the information you need to the JS.

**Comment by HeyImChris** [comment]
Closing as this seems resolved. The best course of action is to write a native module to support the desired behavior as it's unlikely React-Native will want to support this.
