### ISSUE TITLE
Warning Box should not be visible in Release mode

### ISSUE THREAD

**Issue by ericvicenti** [microsoft/react-native-macos#905]
### Environment

```markdown
react-native-macos: 0.64.10
```

### Steps to reproduce the bug

Build an app in release mode with `npx react-native run-macos --configuration Release`. Then cause a warning to happen

One easy way to trigger a warning (this should probably be a separate issue):
- Set a Text component to selectable=true
- Right click on the text component so the "copy" option is visible
- Click elsewhere in the application
- The following warning will appear (even in release mode!)

<img width="841" alt="Screen Shot 2021-11-18 at 11 17 18 AM" src="https://user-images.githubusercontent.com/1483597/142482590-2ee8e95e-e757-4356-9f4a-2868ae56cf36.png">

### Expected Behavior

Warnings should be silently ignored in release mode

### Actual Behavior

<img width="841" alt="Screen Shot 2021-11-18 at 11 17 18 AM" src="https://user-images.githubusercontent.com/1483597/142482590-2ee8e95e-e757-4356-9f4a-2868ae56cf36.png">

**Comment by HeyImChris** [comment]
Thanks for filing this! I'm seeing this behavior too in the rn-tester project. Seems like a good bug worth looking in to.

**Comment by HeyImChris** [comment]
Could you try to repro this again on 0.64.14 or later? A [fix](https://github.com/microsoft/react-native-macos/pull/903) went in to disable dev mode in release builds recently that might impact this.

**Comment by HeyImChris** [comment]
Just verified that we no longer show debug LogBoxes in release builds as of commit `2bb6d93ed6443c0fbbddf2748deb2945316cb7ce` so closing this issue.
