### ISSUE TITLE
Run CLI commands?

### ISSUE THREAD

**Issue by ericvicenti** [microsoft/react-native-macos#907]
### Summary

In node.js we have [child_process](https://nodejs.org/api/child_process.html) to create sub-processes and basically call into the command line.

Is there an equivalent for react-native-macos? Maybe there is a 3rd-party module?

### Motivation

In Electron we have full access to node.js and child_process. Without writing any native code.

Hard to move serious projects to RN-macOS when there is no support for external commands like `ssh-keygen` without writing a native module.

### Basic Example

```js
import { execFileSync } from "child_process"

const signatureOutput = execFileSync(
  'ssh-keygen',
  ['-Y', 'sign', '-n', 'file', '-f', '/Users/me/.ssh/id_rsa'],
  {
    input: 'my string to sign2',
    stdio: ['pipe', 'pipe', 'ignore'],
  },
);
```

**Comment by HeyImChris** [comment]
Closing as per described in #904
