### ISSUE TITLE
lineHeight display issue

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-macos#912]
### Environment

```markdown
react-native 0.64.0:
npm ls react-native-macos: 0.64.13
node: 17.0.1
npm: 8.1.0
yarn: N/A
xcodebuild: 13A1030d
```

### Steps to reproduce the bug

Create a TextInput and set the lineHeight to 40, and the text gets pushed too far down but if you focus the field the cursor remains at the top of the field.

<TextInput style={[{lineHeight: 40}]} placeholder='Search...' autoCompleteType={'off'} autoCorrect={false} underlineColorAndroid='transparent' />

Workaround is to use padding but this will cause inconsistent results depending on the font used by the client.

### Expected Behavior

It's expected that the text and cursor will be centered in the lineHeight.

### Actual Behavior

Text gets pushed too far down but cursor is at the top of the field.

<img width="595" alt="Screen Shot 2021-11-24 at 2 16 15 AM" src="https://user-images.githubusercontent.com/27532334/143192383-687f8599-7a32-4ce0-bd51-06a156747cc7.png">

**Comment by HeyImChris** [comment]
We've hit line height issues across all platforms. Does this [expo snack](https://snack.expo.dev/e1lS9xm65) match the behavior you're seeing?

**Comment by jbcullis** [comment]
I'm closing this issue cause it's low priority, and RN Windows yields the same result as RN macOS.
Easy enough workaround is to either use padding or justifyContent which works consistently on all platforms.
