### ISSUE TITLE
TextInput autoCapitalize doesn't work

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-macos#918]
### Environment

```markdown
react-native 0.64.0:
npm ls react-native-macos: 0.64.13
node: 17.0.1
npm: 8.1.0
yarn: N/A
xcodebuild: 13A1030d
```

### Steps to reproduce the bug

Create a TextInput and add autoCapitalize={'characters'}

### Expected Behavior

Characters should display capitalized.

### Actual Behavior

Characters display lower case.

**Comment by HeyImChris** [comment]
Thanks for filing this- it seems like another engineer has hit this too so seems like a great candidate to get support for.

**Comment by SPBabbar** [comment]
I'm ready for support. I need to understand the structure. Would be glad to get some documentation on the code base before getting started. Although I'm exploring this myself for now. @HeyImChris @jbcullis @sahrens @shergin 😃

**Comment by jbcullis** [comment]
@SPBabbar I've got no experience with making edits to RN so take this with a grain of salt.

What I've found so far, it seems the property is not mapped in the following file:
/node_modules/react-native-macos/Libraries/Text/TextInput/RCTBaseTextInputViewManager.m

At Line 39:
RCT_REMAP_NOT_OSX_VIEW_PROPERTY(autoCapitalize, backedTextInputView.autocapitalizationType, UITextAutocapitalizationType) // TODO(macOS GH#774)

backedTextInputView is defined at node_modules\react-native\Libraries\Text\TextInput\RCTBaseTextInputView.m and looks like autocapitalizationType is not a supported prop for UIView on OSX.

**Comment by harrieshin** [comment]
I think this is addressed withhttps://github.com/microsoft/react-native-macos/pull/1292 @saadnajmi?

**Comment by Saadnajmi** [comment]
Yes I think so. That is checked into our main branch and should be in our next major release (0.70) :)
