### ISSUE TITLE
Image component unloads network image after some time of inactivity

### ISSUE THREAD

**Issue by k1mmm** [microsoft/react-native-macos#921]
### Environment

```markdown
react-native -v: 0.64.10
npm ls react-native-macos: 0.63.37
node -v: 15.14.0
npm -v: 7.7.8
yarn --version: -
xcodebuild -version: 12.5.1
```

### Steps to reproduce the bug

<Image source={{uri: 'http-image-url'}} />

### Expected Behavior

The image stays loaded even after days of inactivity

### Actual Behavior

The image unloads after a day or two and showing a blank space

### Additional context

I've noticed this issue when leaving the laptop for the weekend, and coming back just shows blank images if they are network images. This issue has been found in both 63 and 64. The memory consumption stays the same even after the images has been unloaded.

**Comment by HeyImChris** [comment]
@k1mmm does this repro with the [upstream repo](https://github.com/facebook/react-native) as well? If so we should file there instead

**Comment by k1mmm** [comment]
@HeyImChris I don't think so, I've been doing react-native for mobile previously and never experienced this issue, also I couldn't find anything related to this issue on the upstream repos issue tracker.

**Comment by k1mmm** [comment]
@HeyImChris I have not been able to reproduce this in 0.66 so we can close this
