### ISSUE TITLE
[CI] Integration test fails on main

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-macos#948]
### Environment

```markdown
react-native -v:
npm ls react-native-macos:
node -v:
npm -v:
yarn --version:
xcodebuild -version:
```

### Steps to reproduce the bug

We added a check to our CI called `Integration` that fails on main but passes in `0.64-stable`. We should fix this, bug is to track 

### Expected Behavior

Test passes

### Actual Behavior

Test fails

**Comment by HeyImChris** [comment]
This is fixed in a PR I have out for 0.66. Should be resolved soon!
