### ISSUE TITLE
[CircleCI] E2E Tests fail

### ISSUE THREAD

**Issue by Saadnajmi** [microsoft/react-native-macos#949]
### Environment

```markdown
react-native -v:
npm ls react-native-macos:
node -v:
npm -v:
yarn --version:
xcodebuild -version:
```

### Steps to reproduce the bug

This seems to be because the E2E tests are downloading react-native version 0.63 from NPM and testing against that, instead of using the local copy. #944 Might help with this, but I commented out the failing check in #945 . This bug is to track.

**Comment by kelset** [comment]
@Saadnajmi I think we can close this one, as far as I can tell it's fixed right?

**Comment by Saadnajmi** [comment]
I only disabled the tests, I didn't fix them.

**Comment by kelset** [comment]
commit with the actual disabling of the test: https://github.com/microsoft/react-native-macos/pull/1052/files (posting for cross-reference)

**Comment by kelset** [comment]
update on this: I've investigated this problem a bit more with https://github.com/microsoft/react-native-macos/pull/1106. The long story short is that this is a problem that spawns from upstream, and that was only tackled in the react-native core repo in December 2021. So we'll only get access to the fixes around ~68. So basically we should not look into this problem until after react-native-macos has caught up to that.

**Comment by Saadnajmi** [comment]
Thanks for the update @kelset !
