### ISSUE TITLE
rn-macos's Hermes support: RNTester on 0.64 & 0.66

### ISSUE THREAD

**Issue by kelset** [microsoft/react-native-macos#952]
### Environment

```markdown
react-native-macos: 0.64, 0.66
node -v: 14.8.1
npm -v: 6.14.15
yarn --version: 1.22.17
xcodebuild -version: Xcode 13.2 - Build version 13C90
```
*(0.64-stable branch of this repo, fb66merge branch by @heyimchris: https://github.com/HeyImChris/react-native-macos/tree/fb66merge)*

### Steps to reproduce the bug

After doing the basic `yarn` from root of the repo, I go into `packages/rn-tester` and do `pod install`.
Then open RNTesterPods.xcworkspace, select "RNTester-macOS" -> "My Mac" and press play.

Without any changes, it works for both 0.64 and 0.66 versions. An app is created, metro instance loaded and RNTester app is usable.

If I try to enable Hermes by going in `scripts/react_native_pods.rb` and changing L17 from
```rb
  hermes_enabled = options[:hermes_enabled] ||= false
```

to
```rb
  hermes_enabled = options[:hermes_enabled] ||= true
```

Note: this is quickest way of enabling Hermes, there are others but this does the work as far as I can tell. After cleaning build folder, closing Xcode, doing a new `pod install`, the hermes-engine pod also gets pulled in correctly.

Then, when I open RNTesterPods.xcworkspace, select "RNTester-macOS" -> "My Mac" and press play, this time around the build fails, for both 0.64 and 0.66.

Details of the failures in the "Actual Behaviour" section.

### Expected Behavior

That RNTester loads up correctly, and shows the "Hermes engine" line in the top right corner just like it happens with Android and iOS.

#### For 0.64

In 0.64, the build error is as shown in the screenshot:
<img width="1719" alt="Screenshot 2022-01-12 at 17 23 36" src="https://user-images.githubusercontent.com/16104054/149366452-501922c9-dfbc-4e2e-9c8d-6bfa6036c84c.png">

This was a known error in 0.64, and there are issues opened about it: https://github.com/facebook/flipper/issues/2281 but for some reason, updating the Flipper dependencies in the Podfile as per the resolution offered there didn't lead to the Xcode project building.

#### For 0.66
In 0.66 the error is different (correctly, the issue hit above is solved in this newer version). See screenshot:
<img width="1640" alt="Screenshot 2022-01-13 at 16 14 05" src="https://user-images.githubusercontent.com/16104054/149367129-f5ae6867-2fe3-4cf2-8c42-1fee925f6edb.png">

This Linker level error:
```
Undefined symbols for architecture x86_64:
  "folly::exception_ptr_get_type(std::exception_ptr const&)", referenced from:
      folly::exception_wrapper::ExceptionPtr::type_(folly::exception_wrapper const*) in libRCT-Folly-macOS.a(ExceptionWrapper.o)
      folly::exceptionStr(std::exception_ptr const&) in libRCT-Folly-macOS.a(ExceptionString.o)
  "folly::exception_ptr_get_object(std::exception_ptr const&, std::type_info const*)", referenced from:
      std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libReact-hermes-macOS.a(Connection.o)
      std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libRCT-Folly-macOS.a(ExceptionWrapper.o)
      std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libRCT-Folly-macOS.a(ExceptionString.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Resembled another error that was reported during the RC phase of 0.66: https://github.com/react-native-community/releases/issues/251

In that case, the problem was with the arm64; still, I kept digging and basically it was caused by the fact that Folly needed one extra library `c++abi`, which was added to Folly's requirements (https://github.com/facebook/folly/commit/0fee9dfce93e42b33ca8fb2c455b1d7cce8bebce) for Apple's Cmake but that version of Folly wasn't getting consumed by RN correctly, which lead to https://github.com/facebook/flipper/issues/2600 and in turn https://github.com/facebook/react-native/commit/8b6d7fddd65a9b5caf599e8ff7b090a176a6f11f

This last commit is present in the `fb66merge` branch - so I dug a bit deeper and realized that even despite that, the dependency of Flipper-Folly had to be bumped to 2.6.10 to get the right version of Folly.
I tried to do that too, but the build error is still present.

At this point I'm kind-of running out of ideas, which is why I've decided to open this to document all my findings in the hope that someone can point out what I need to do to get Hermes to work against react-native-macos's RNTester (which I hope in turn will lead to it working in any react-native-macos project).

### Reproducible Demo

(see repro steps section)

#### about hermes-darwin-engine

One extra rabbithole of this whole story is the extra dependency `hermes-engine-darwin`. I found it mentioned in a few places, and in the docs for RN-macos too: https://microsoft.github.io/react-native-windows/docs/hermes#hermes-on-macos

But it turns out, this entire npm package was removed entirely from the Hermes repo: https://github.com/facebook/hermes/commit/dbc1e285707902f34d32be1e36ddb0855c3ae941

So I tried to understand a bit more of what that package was all about: it seems that it was created as a "quick and dirty" add on during the early stages of Hermes for iOS work: https://github.com/facebook/hermes/pull/297

Then one of the Hermes developers realized that ios & macos impl could have been together here 
https://github.com/facebook/hermes/pull/385/files
so it's been "hermes-engine" only since 0.7 (the version paired with 0.64).

All of this seems to point in the direction of `hermes-engine` being the only dependency needed to get Hermes to work on macos.

---

In closure - this issue seems to be related to mine, so linking here for cross-ref: https://github.com/microsoft/react-native-macos/issues/931

**Comment by HeyImChris** [comment]
Thanks for filing this @kelset. It looks like you're not the only one who's hit this issue, so probably a good candidate to look at, especially if Apple explicitly gives approval to use this.

**Comment by HeyImChris** [comment]
Thanks for filing this @kelset. It seems like an issue other folks have hit as well so probably a reasonable candidate to get fixed.

**Comment by Saadnajmi** [comment]
Based on the error I'm seeing in your screenshots, the extra script @ospfranco listed in https://github.com/microsoft/react-native-macos/issues/931 seems promising?

**Comment by kelset** [comment]
@Saadnajmi potentially - but since that error is not present in the 0.66 branch I'm not really interested in fixing it. My main interest is understanding what it takes to make sure that Hermes works on macos :)

**Comment by kelset** [comment]
quick update: I went for this problem from another angle, testing RNTA's macos example app and turning Hermes on there - it works correctly (it's still on rn-macos 64):
<img width="1125" alt="Screenshot 2022-01-17 at 16 56 55" src="https://user-images.githubusercontent.com/16104054/149811663-b4d8aaf7-7d4f-49aa-b3e6-03360d3d441c.png">

So it looks like it might be more of a RNTester problem locally in this repo than Hermes not working properly with rn-macos.

**Comment by tido64** [comment]
Testing out react-native-macos 0.66.4 in react-native-test-app right now, and I'm getting the following linker errors with Hermes enabled:
```
Undefined symbols for architecture x86_64:
  "folly::exception_ptr_get_type(std::exception_ptr const&)", referenced from:
      folly::exception_wrapper::ExceptionPtr::type_(folly::exception_wrapper const*) in libRCT-Folly.a(ExceptionWrapper.o)
      folly::exceptionStr(std::exception_ptr const&) in libRCT-Folly.a(ExceptionString.o)
  "folly::exception_ptr_get_object(std::exception_ptr const&, std::type_info const*)", referenced from:
      std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libReact-hermes.a(Connection.o)
      std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libRCT-Folly.a(ExceptionWrapper.o)
      std::exception* folly::exception_ptr_get_object<std::exception>(std::exception_ptr const&) in libRCT-Folly.a(ExceptionString.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by tido64** [comment]
It looks like the linker errors are caused by this line:
https://github.com/microsoft/react-native-macos/blob/643b056e89d2adf01f77ea7498618cb796a79f9e/third-party-podspecs/RCT-Folly.podspec#L43

Uncommenting and rebuilding seems to work:

![image](https://user-images.githubusercontent.com/4123478/151042249-6bbf87a9-db30-46c0-8d3d-02108456eecc.png)

@HeyImChris, @Saadnajmi: If there are no objections, I'll submit a PR later.

**Comment by ospfranco** [comment]
I'm on react-native-macos: 0.66.10 and "hermes-engine-darwin": "~0.5.3" and my app is still not compiling:
<img width="1280" alt="Screen Shot 2022-02-14 at 08 36 59" src="https://user-images.githubusercontent.com/1634213/153820175-2eedb0c7-0f01-4e8e-9195-72a10aa444e4.png">

I also added the following post-install script in my Podfile:

```ruby
require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'sol-macOS' do
  platform :macos, '10.15'
  use_native_modules!
  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
```

Any pointers on what could be wrong? thanks a lot!

**Comment by kelset** [comment]
@ospfranco I am not sure, but I think you might have to drop the extra `hermes-engine-darwin` and just use the standard `hermes-engine` on the RN66 specific version (which should be 0.9)

**Comment by ospfranco** [comment]
I tried swapping `hermes-engine-darwin` for `hermes-engine` 0.9.0 and I'm still getting the same error

**Comment by ospfranco** [comment]
If you want you can check-out the project where I'm trying to apply the update yourself

https://github.com/ospfranco/sol/tree/hermes

**Comment by kelset** [comment]
@ospfranco in this commit https://github.com/ospfranco/sol/commit/d96e551d6968d903a6ef85b6b79e09ed68f16f54 you have put Hermes at version 0.11, not 0.9. I am not sure that will fix, but you are currently on the wrong version of Hermes

**Comment by tido64** [comment]
@ospfranco: #982 should've fixed it. Looking at the `0.66-stable` branch, it looks like we didn't backport it. PR: #1021

**Comment by ospfranco** [comment]
I just updated to RN-macOS 0.66.10 and wanted to test if this is fixed, but I still get the same error #1021 was supposed to fix

![CleanShot 2022-03-11 at 14 19 36@2x](https://user-images.githubusercontent.com/1634213/157874673-d1fec1df-bcce-4d05-aa1b-dde6b68dd876.png)

**Comment by tido64** [comment]
<img width="576" alt="image" src="https://user-images.githubusercontent.com/4123478/157876467-b0649f60-1125-4e9e-826f-e0f355641f32.png">
Can you try 0.66.11 or higher?

**Comment by ospfranco** [comment]
oops, damn, I meant `0.66.30`, `0.66.10` was the version I was using

**Comment by tido64** [comment]
Can you verify that you've run `pod install` after upgrading, and that the RCT-Folly target includes `Exception.cpp`?

**Comment by ospfranco** [comment]
![CleanShot 2022-03-11 at 14 35 40@2x](https://user-images.githubusercontent.com/1634213/157878217-48ab80d8-0a5d-4e20-a03b-3d5643a30d9b.png)

I only see the header files in my project, where am I supposed to look at?

**Comment by tido64** [comment]
I use the filter at the bottom. Can you also check a few more things for me:

- Does `Pods/Local Podspecs/RCT-Folly.podspec.json` include `Exception.cpp`?
- Does `node_modules/react-native-macos/third-party-podspecs/RCT-Folly.podspec` include `Exception.cpp`?
- What is the version number in `node_modules/react-native-macos/package.json`?

**Comment by ospfranco** [comment]
Ah, apparently my pods had a cached version, I removed the Pods folder and the Podfile.lock and did a clean install (with hermes-engine 0.9.0) and it works! Thanks a lot!

Also, I'm getting a Intl error, I thought hermes was supposed to add Intl support by now? :P

**Comment by tido64** [comment]
According to the Hermes docs, it's only implemented on Android: https://hermesengine.dev/docs/language-features/#supported 😕
