### ISSUE TITLE
onKeyPressed / onSubmitEditing inconsistency with rn-windows

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-macos#964]
### Environment

```markdown
react-native 0.64.0:
npm ls react-native-macos: 0.64.13
node: 17.0.1
npm: 8.1.0
yarn: N/A
xcodebuild: 13A1030d
```

### Steps to reproduce the bug

Not sure if this is a bug or by design, but TextInput onKeyPressed={} will not capture 'Return' on macos, but does capture 'Enter' on windows.
On mac, return triggers onSubmitEditing but will not register as a key press.

Ideally, behavior would be identical on both platforms to reduce the amount of platform specific code.

### Expected Behavior

Return should register as a keypress as well as triggering onSubmitEditing to match react-native-windows.

### Actual Behavior

return does not trigger as a keypress.

**Comment by Saadnajmi** [comment]
Does it capture 'Enter' ?

**Comment by jbcullis** [comment]
@Saadnajmi No, on macos it doesn't capture 'Enter', 'Return', or 'Tab'.

These are the only ones I tried, but I suspect it's because the OS behavior is to submit on enter?

**Comment by HeyImChris** [comment]
@jcbullis thanks for noting this! When we added onKeyUp/onKeyDown support to RCTView, text inputs never got that support. It's something we should look into migrating over to better align with Windows. Would adding support for those APIs resolve this for you?

**Comment by jbcullis** [comment]
@HeyImChris I think it would be helpful, we were able to get the control going by using onSubmitEditing though so it's not a high priority, more just noting an inconsistency.

I also noted that the timing was different between windows and mac...I'll have to double check this but I think on windows it onKeyPress was firing before onTextChanged, but on mac it was opposite.
