### ISSUE TITLE
React native bluetooth printing

### ISSUE THREAD

**Issue by AyishmAzeem** [microsoft/react-native-macos#965]
### Summary

Is there any library supporting the functionality of printing a receipt through react native macOS app?

### Motivation

It is required for POS system

**Comment by jbcullis** [comment]
You'll probably need to create your own, this one used to work on ios https://github.com/rusel1989/react-native-bluetooth-serial however it uses EAF (https://developer.apple.com/documentation/externalaccessory) which I doubt would be required for macos.

Read up on creating native modules and core bluetooth:
https://reactnative.dev/docs/native-modules-intro
https://developer.apple.com/documentation/corebluetooth

Unfortunately there is very little documentation out there for what you're doing, we have thermal printer support for ios and android but have no need for it on windows or mac cause mobile devices are better suited to the job.

**Comment by HeyImChris** [comment]
Agree that the best approach here is to write your own native module to do this. It's unlikely we'd want support for this module in core as is since there's on ongoing effort to move non-essential modules _out_ of core.
