### ISSUE TITLE
Run script sh with data passing

### ISSUE THREAD

**Issue by Angelk90** [microsoft/react-native-macos#976]
### Summary

Being able to run script sh.

### Motivation

By creating apps for Macos, it would be nice to be able to run sh scripts.

### Basic Example

Example having some input fields to put the data, when the send button is pressed, the sh script is executed, passing the input data.

![image](https://user-images.githubusercontent.com/20476002/150343333-7a26c9f0-64b0-428b-80b8-ac2900b858cd.png)

File Sh:

```
git clone --progress $project
open ~/$path/$name
```

### Open Questions

I thought I was using `child_process`, but it seems to only work on node.

**Comment by HeyImChris** [comment]
The best bet is to write a native module to add support for this. It's unlikely we take something like this in to core any time soon.
